import 'package:flutter_test/flutter_test.dart';
import 'package:maintaniac/screens/expenses/data/expense_screen_telemetry.dart';
import 'package:maintaniac/shared/firebase/maintainiac_firestore_documents.dart';

void main() {
  test('rejects invalid expense telemetry scalar values before Firestore', () {
    final negativeCountSnapshot = _expenseTelemetrySnapshotForSanitizer(
      totalEventCount: -1,
    );
    final negativeRateSnapshot = _expenseTelemetrySnapshotForSanitizer(
      timeSpentEventCount: 1,
      totalTimeSpentMs: -1000,
    );

    expect(
      () => MaintainiacFirestoreDocumentBuilder.expenseTelemetrySummaryDocument(
        orgId: 'ORG-1',
        snapshot: negativeCountSnapshot,
      ),
      throwsA(
        isA<ArgumentError>().having(
          (error) => error.message,
          'message',
          contains('Counts must be positive'),
        ),
      ),
    );
    expect(
      () => MaintainiacFirestoreDocumentBuilder.expenseTelemetrySummaryDocument(
        orgId: 'ORG-1',
        snapshot: negativeRateSnapshot,
      ),
      throwsA(
        isA<ArgumentError>().having(
          (error) => error.message,
          'message',
          contains('Rates must be finite'),
        ),
      ),
    );
  });

  test('sanitizes expense telemetry maps and drill-down labels', () {
    final snapshot = _expenseTelemetrySnapshotForSanitizer(
      eventCounts: const {
        'Receipt Text Private Store Total 3.24': 2,
        'negative count': -1,
      },
      ocrFailureSourceCounts: const {
        'Photo Import Private Store': 3,
        'bad negative': -9,
      },
      topOcrFailureSource: 'Photo Import Private Store',
      topOcrFailureStage: 'after import before parser',
    );

    final doc =
        MaintainiacFirestoreDocumentBuilder.expenseTelemetrySummaryDocument(
          orgId: 'ORG-1',
          summaryId: 'latest',
          snapshot: snapshot,
        );

    expect(doc.data['eventCounts'], {
      'receipt_text_private_store_total_3_24': 2,
    });
    expect(doc.data['ocrFailureSourceCounts'], {
      'photo_import_private_store': 3,
    });
    expect(doc.data['topOcrFailureSource'], 'photo_import_private_store');
    expect(doc.data['topOcrFailureStageLabel'], 'After import before parser');
    expect(doc.data.toString(), isNot(contains('3.24')));
    expect(doc.data.toString().toLowerCase(), isNot(contains('private store')));
  });
}

ExpenseTelemetryHealthSnapshot _expenseTelemetrySnapshotForSanitizer({
  int totalEventCount = 1,
  int timeSpentEventCount = 0,
  int totalTimeSpentMs = 0,
  Map<String, int> eventCounts = const {'screenOpened': 1},
  Map<String, int> ocrFailureSourceCounts = const {},
  String topOcrFailureSource = '',
  String topOcrFailureStage = '',
}) {
  return ExpenseTelemetryHealthSnapshot(
    generatedAtUtc: DateTime.utc(2026, 6, 24, 13),
    totalEventCount: totalEventCount,
    pendingUploadCount: 1,
    uploadedEventCount: 0,
    eventCounts: eventCounts,
    platformCounts: const {'android': 1},
    deviceTierCounts: const {'high': 1},
    storageModeCounts: const {'normal': 1},
    planStatusCounts: const {'paid': 1},
    connectionStatusCounts: const {'online': 1},
    screenOpenCount: 1,
    timeSpentEventCount: timeSpentEventCount,
    totalTimeSpentMs: totalTimeSpentMs,
    addExpenseStartedCount: 1,
    addExpenseCompletedCount: 1,
    addExpenseAbandonedCount: 0,
    validationErrorCount: 0,
    saveFailureCount: 0,
    imageAttachSuccessCount: 1,
    imageAttachFailureCount: 0,
    ocrStartedCount: 1,
    ocrCompletedCount: 1,
    ocrFailedCount: 0,
    parserStartedCount: 1,
    parserCompletedCount: 1,
    parserNeedsReviewCount: 0,
    parserFailedCount: 0,
    parserCategoryCounts: const {},
    parserNeedsReviewCategoryCounts: const {},
    parserFailedCategoryCounts: const {},
    parserFieldConfidenceCounts: const {},
    parserCategoryHealthCounts: const {'category_fuel_ready': 1},
    parserCategoryReviewActionCounts: const {},
    parserPackPressureStatusCounts: const {},
    receiptBrainParserLimitOutcomeCounts: const {},
    receiptBrainLowStorageDownloadRiskCounts: const {},
    receiptBrainFullOfflineMustStayOptionalCounts: const {},
    receiptBrainFullOfflineExceedsBaseGuardrailCounts: const {},
    receiptBrainBaseLocalReadingAvailableCounts: const {},
    receiptBrainBaseWorksWithoutCloudAssistCounts: const {},
    receiptBrainLocalFirstReadinessCounts: const {},
    receiptBrainLocalFirstReadinessActionCounts: const {},
    receiptBrainLocalFirstReadinessSummaryCounts: const {},
    receiptBrainFirstInstallBoundaryCounts: const {},
    receiptBrainFirstInstallBoundaryActionCounts: const {},
    receiptBrainFirstInstallCanRunLowStorageCounts: const {},
    receiptBrainFirstInstallRequiresBaseCapabilityCounts: const {},
    receiptBrainFirstInstallBoundarySummaryCounts: const {},
    receiptInstallRequiredSegmentCounts: const {},
    receiptInstallFullOfflineSegmentCounts: const {},
    receiptInstallLowStorageImpactCounts: const {},
    receiptInstallRecommendedDistributionCounts: const {},
    receiptInstallCameraShellParserFreeCounts: const {},
    receiptInstallBaseUsefulOnTinyPhonesCounts: const {},
    receiptInstallOptionalPacksRequireConsentCounts: const {},
    receiptLocalOnlyAcceptanceStatusCounts: const {},
    receiptLocalOnlyAcceptanceActionCounts: const {},
    receiptLocalOnlyBaseFlowCanRunCounts: const {},
    receiptLocalOnlyBlocksLowStorageCounts: const {},
    receiptLocalOnlyEvidenceCounts: const {},
    nativeLocalOnlyCapturePolicyCounts: const {},
    nativeLocalOnlyBaseFlowCanRunCounts: const {},
    nativeLocalOnlyHeavyPacksMayBlockCaptureCounts: const {},
    nativeLocalOnlyCloudAssistMayBlockCaptureCounts: const {},
    receiptRequiredBaseFootprintStatusCounts: const {},
    receiptRequiredBaseFootprintCanShipCounts: const {},
    receiptRequiredBaseFootprintReviewCounts: const {},
    receiptRequiredBaseFootprintBlockingReasonCounts: const {},
    receiptRequiredBaseFootprintReviewReasonCounts: const {},
    ocrStoragePolicyCounts: const {},
    ocrUsesPreparedSourceBeforeSavedProofCounts: const {},
    ocrUsesSavedProofFallbackCounts: const {},
    parserRequiredFieldStatusCounts: const {'vendor_ready': 1},
    parserDownstreamReadinessStatusCounts: const {'expense_lines_ready': 1},
    parserDownstreamReadinessCounts: const {
      'parser_downstream_expense_lines_ready': 1,
    },
    parserReviewRootCauseCounts: const {},
    localReceiptParserRoutingCounts: const {},
    localParserEvidenceOutcomeCounts: const {},
    localReceiptParserKeptLocalCount: 0,
    localReceiptParserOptionalPackOfferCount: 0,
    ocrParserTaskCounts: const {'vendor_candidate': 1},
    ocrFieldReadinessCounts: const {'vendor_ready': 1},
    ocrSourceHandoffStatusCounts: const {},
    ocrSourceHandoffSignalCounts: const {},
    ocrSourceStitchSignalCounts: const {},
    ocrSourceScannerDecisionCounts: const {},
    ocrSourceCaptureSourceSignalCounts: const {},
    ocrSourcePhotoQualityRiskCounts: const {},
    ocrSourceQualityReviewStatusCounts: const {},
    ocrSourceQualityReviewActionCounts: const {},
    clientProofRedactionStatusCounts: const {},
    clientProofVisibilityCounts: const {},
    receiptSelectedLinePurposeCounts: const {},
    receiptSelectedLineCountTotal: 0,
    receiptExcludedLineCountTotal: 0,
    receiptClientProofReviewLineCountTotal: 0,
    receiptRedactedLineCountTotal: 0,
    clientProofRedactionPlanStatusCounts: const {},
    clientProofVisibleLineCountTotal: 0,
    clientProofHiddenLineCountTotal: 0,
    clientProofPlanReviewLineCountTotal: 0,
    topParserCategory: '',
    topParserNeedsReviewCategory: '',
    topParserFailedCategory: '',
    topParserCategoryHealth: 'category_fuel_ready',
    topParserCategoryReviewAction: '',
    topParserPackPressureStatus: '',
    topReceiptBrainParserLimitOutcome: '',
    topReceiptBrainLowStorageDownloadRisk: '',
    topReceiptBrainLocalFirstReadiness: '',
    topReceiptBrainLocalFirstReadinessAction: '',
    topReceiptBrainFirstInstallBoundary: '',
    topReceiptBrainFirstInstallBoundaryAction: '',
    topReceiptInstallRecommendedDistribution: '',
    topReceiptInstallLowStorageImpact: '',
    topReceiptLocalOnlyAcceptanceStatus: '',
    topReceiptLocalOnlyAcceptanceAction: '',
    topNativeLocalOnlyCapturePolicy: '',
    topReceiptRequiredBaseFootprintStatus: '',
    topReceiptRequiredBaseFootprintBlockingReason: '',
    topReceiptRequiredBaseFootprintReviewReason: '',
    topOcrStoragePolicy: '',
    topOcrUsesPreparedSourceBeforeSavedProof: '',
    topOcrUsesSavedProofFallback: '',
    topParserRequiredFieldStatus: 'vendor_ready',
    topParserDownstreamReadinessStatus: 'expense_lines_ready',
    topParserDownstreamReadiness: 'parser_downstream_expense_lines_ready',
    topParserReviewRootCause: '',
    topLocalReceiptParserRouting: '',
    topLocalParserEvidenceOutcome: '',
    topOcrParserTask: 'vendor_candidate',
    topOcrFieldReadiness: 'vendor_ready',
    topOcrSourceHandoffStatus: '',
    topOcrSourceHandoffSignal: '',
    topOcrSourceStitchSignal: '',
    topOcrSourceScannerDecision: '',
    topOcrSourceCaptureSourceSignal: '',
    topOcrSourcePhotoQualityRisk: '',
    topOcrSourceQualityReviewStatus: '',
    topOcrSourceQualityReviewAction: '',
    topClientProofRedactionStatus: '',
    topClientProofVisibility: '',
    topReceiptSelectedLinePurpose: '',
    topClientProofRedactionPlanStatus: '',
    receiptPhotoCoverageStatusCounts: const {},
    receiptPhotoCoverageReasonCounts: const {},
    receiptPhotoCoverageNeedsMoreCount: 0,
    topReceiptPhotoCoverageStatus: '',
    topReceiptPhotoCoverageReason: '',
    savedPhotoWarningCounts: const {},
    savedPhotoWarningCauseCounts: const {'missing_bottom_edge': 1},
    savedPhotoWarningSeverityCounts: const {},
    savedPhotoWarningActionCounts: const {},
    savedPhotoParserRiskCounts: const {},
    savedPhotoQualityWarningCount: 0,
    savedPhotoCriticalWarningCount: 0,
    topSavedPhotoWarning: '',
    topSavedPhotoWarningCause: 'missing_bottom_edge',
    topSavedPhotoWarningSeverity: '',
    topSavedPhotoWarningActionCode: '',
    topSavedPhotoWarningAction: '',
    topSavedPhotoParserRisk: '',
    preCaptureExposureDecisionCounts: const {},
    preCaptureExposureAdjustmentCount: 0,
    topPreCaptureExposureDecision: '',
    autoExposureDecisionCounts: const {'brightened_preview': 1},
    autoExposureBrightnessCounts: const {'preview_dim': 1},
    autoExposureCandidateCounts: const {'stable_receipt_text': 1},
    exposureAssistStatusCounts: const {'active': 1},
    autoExposureCandidateFrameCount: 4,
    manualBrightnessChangeCount: 1,
    topAutoExposureDecision: 'brightened_preview',
    topAutoExposureBrightness: 'preview_dim',
    topAutoExposureCandidate: 'stable_receipt_text',
    topExposureAssistStatus: 'active',
    acceptedPhotoQualityOutcomeCounts: const {'needs_review_before_ocr': 1},
    topAcceptedPhotoQualityOutcome: 'needs_review_before_ocr',
    capturedPhotoBrightnessCounts: const {'captured_dim': 1},
    capturedPhotoSharpnessCounts: const {'captured_sharp': 1},
    capturedPhotoExposureMismatchCounts: const {'live_ok_capture_dim': 1},
    capturedPhotoQualitySignalCounts: const {'review_before_saving': 1},
    capturedPhotoBottomBrightnessCounts: const {'bottom_dim': 1},
    capturedPhotoBottomEdgeScoreCounts: const {'bottom_edge_usable': 1},
    capturedPhotoVerticalQualitySignalCounts: const {
      'bottom_darker_than_upper': 1,
    },
    topCapturedPhotoBrightness: 'captured_dim',
    topCapturedPhotoSharpness: 'captured_sharp',
    topCapturedPhotoExposureMismatch: 'live_ok_capture_dim',
    topCapturedPhotoQualitySignal: 'review_before_saving',
    topCapturedPhotoBottomBrightness: 'bottom_dim',
    topCapturedPhotoBottomEdgeScore: 'bottom_edge_usable',
    topCapturedPhotoVerticalQualitySignal: 'bottom_darker_than_upper',
    nativeCameraEngineCounts: const {'camerax': 1},
    nativeReceiptCameraSurfaceActualCounts: const {},
    nativeReceiptCameraSurfaceVerificationCounts: const {},
    nativeCameraIdentityCounts: const {},
    nativeSettingsContractVersionCounts: const {
      'receipt_native_camera_settings_v1': 1,
    },
    nativeControlContractVersionCounts: const {'receipt_native_controls_v1': 1},
    receiptCloudAssistPlanCounts: const {
      'local_ocr_cloud_ocr_cloud_inventory_optional': 1,
    },
    receiptLocalOcrModeCounts: const {'lean_local_ocr': 1},
    receiptParserDepthCounts: const {'price_only': 1},
    receiptParserPackCodeCounts: const {'core_receipt_text_v1': 1},
    receiptOptionalLocalParserPackCodeCounts: const {
      'general_expense_lines_v1': 1,
    },
    receiptCloudFallbackParserPackCodeCounts: const {'cloud_ocr_assist_v1': 1},
    receiptParserPackAccuracyBandCounts: const {
      'ocr_text_95_99_when_photo_readable': 1,
    },
    receiptEstimatedOptionalLocalPackBytesTotal: 25165824,
    receiptEstimatedOptionalLocalPackBytesMax: 25165824,
    receiptCloudOcrOptionalCount: 1,
    receiptCloudInventoryOptionalCount: 1,
    topReceiptParserPackDisclosureLabel:
        'Optional local parser add-ons use about 24.0 MB. Cloud OCR/parser fallback needs internet and must be chosen by the user. Accuracy disclosures: core_receipt_text_v1: ocr_text_95_99_when_photo_readable.',
    nativeDevicePolicyCounts: const {'storage_saver_receipt_camera': 1},
    nativeCameraWorkloadTierCounts: const {'light': 1},
    nativeCameraResolutionTierCounts: const {'medium': 1},
    nativeRecoveryResumeStatusCounts: const {'resume_review_started': 1},
    nativeRecoveryFreshnessCounts: const {'stale': 1},
    nativeRecoveryStorageStatusCounts: const {'partial_photos_available': 1},
    nativeRecoveryRecoveredPhotoCount: 2,
    nativeRecoveryMultipleSectionCount: 1,
    nativeTapFocusControlExpectedCount: 0,
    nativeContinuousFocusExpectedCount: 1,
    nativePinchZoomControlExpectedCount: 1,
    nativeExposureSliderControlExpectedCount: 1,
    nativeExposureResetControlExpectedCount: 1,
    nativeSettingsControlExpectedCount: 1,
    nativeBackControlExpectedCount: 1,
    nativeTorchControlExpectedCount: 1,
    nativeSettingsOpenCount: 2,
    nativePreCaptureExposureAbortCount: 0,
    nativePreCaptureExposureAbortReasonCounts: const {},
    nativeZoomGestureStartCount: 0,
    nativeZoomChangeCount: 0,
    nativeZoomUnavailableCount: 0,
    nativeZoomStatusCounts: const {},
    nativeBackDispatchPathCounts: const {},
    topNativeCameraEngine: 'camerax',
    topNativeZoomStatus: '',
    topNativePreCaptureExposureAbortReason: '',
    topNativeBackDispatchPath: '',
    topNativeReceiptCameraSurfaceActual: '',
    topNativeReceiptCameraSurfaceVerification: '',
    topNativeCameraIdentity: '',
    topNativeSettingsContractVersion: 'receipt_native_camera_settings_v1',
    topNativeControlContractVersion: 'receipt_native_controls_v1',
    topReceiptCloudAssistPlan: 'local_ocr_cloud_ocr_cloud_inventory_optional',
    topReceiptLocalOcrMode: 'lean_local_ocr',
    topReceiptParserDepth: 'price_only',
    topReceiptParserPackCode: 'core_receipt_text_v1',
    topReceiptOptionalLocalParserPackCode: 'general_expense_lines_v1',
    topReceiptCloudFallbackParserPackCode: 'cloud_ocr_assist_v1',
    topReceiptParserPackAccuracyBand: 'ocr_text_95_99_when_photo_readable',
    topNativeDevicePolicy: 'storage_saver_receipt_camera',
    topNativeCameraWorkloadTier: 'light',
    topNativeCameraResolutionTier: 'medium',
    topNativeRecoveryResumeStatus: 'resume_review_started',
    topNativeRecoveryFreshness: 'stale',
    topNativeRecoveryStorageStatus: 'partial_photos_available',
    topNativeRecoveryAction:
        'Review the interrupted receipt recovery before OCR. Some saved sections are available, but the user may need to add the missing receipt photos or retake the full receipt.',
    capabilityPolicyCodeCounts: const {'storage_constrained_small_proofs': 1},
    topCapabilityPolicyCode: 'storage_constrained_small_proofs',
    nativeCaptureSourcePolicyCounts: const {'storage_saver_native': 1},
    topNativeCaptureSourcePolicy: 'storage_saver_native',
    stitchStatusCounts: const {'stitched': 1},
    stitchFallbackReasonCounts: const {'stitched': 1},
    stitchConfidenceBucketCounts: const {'high': 1},
    stitchPairDiagnosticCounts: const {'zoom_adjusted': 1},
    topStitchStatus: 'stitched',
    topStitchFallbackReason: 'stitched',
    topStitchConfidenceBucket: 'high',
    topStitchPairDiagnostic: 'zoom_adjusted',
    ocrCorrectionOpenedCount: 0,
    appFilledReceiptLineConfirmedCount: 1,
    appFilledReceiptLineCorrectedCount: 0,
    userCorrectionCount: 0,
    cloudBackupSuccessCount: 1,
    cloudBackupFailureCount: 0,
    syncPendingCount: 1,
    syncedCount: 1,
    syncFailedCount: 0,
    expenseSummaryQueuedCount: 1,
    expenseSummaryOcrContractQueuedCount: 1,
    expenseSummaryOcrContractSkippedCount: 0,
    expenseSummaryOcrContractSourceCounts: const {'rolling_local_ledger': 1},
    topExpenseSummaryOcrContractSource: 'rolling_local_ledger',
    expenseSummaryOcrContractSkippedReasonCounts: const {},
    topExpenseSummaryOcrContractSkippedReason: '',
    exportStartedCount: 1,
    exportCompletedCount: 1,
    exportBlockedCount: 0,
    exportFailedCount: 0,
    ocrFailureCauseCounts: const {},
    topOcrFailureCause: '',
    ocrFailureSourceCounts: ocrFailureSourceCounts,
    topOcrFailureSource: topOcrFailureSource,
    ocrFailureStageCounts: topOcrFailureStage.isEmpty
        ? const {}
        : {topOcrFailureStage: 1},
    topOcrFailureStage: topOcrFailureStage,
    failureBreakdowns: const [],
    recentFailureDetails: const [],
  );
}
