import 'package:flutter_test/flutter_test.dart';
import 'package:maintaniac/screens/work_supplies/data/work_supply_catalog.dart';
import 'package:maintaniac/screens/work_supplies/data/work_supply_models.dart';

void main() {
  test('real catalog items are hydrated with parser intelligence', () {
    final pexElbow = workSupplyCatalogItems.firstWhere(
      (item) =>
          item.trade == 'Plumbing' &&
          item.system == 'PEX' &&
          item.itemType == '90 Elbows' &&
          item.variant == '1/2 in',
    );
    final castIronCoupling = workSupplyCatalogItems.firstWhere(
      (item) =>
          item.trade == 'Plumbing' &&
          item.system == 'Cast Iron and No-Hub' &&
          item.itemType == 'No-Hub Couplings',
    );

    expect(pexElbow.marketScopes, contains(WorkSupplyMarketScope.residential));
    expect(pexElbow.packTier, WorkSupplyPackTier.core);
    expect(pexElbow.parserPriority, WorkSupplyParserPriority.everydayCore);
    expect(pexElbow.intelligence.material, 'PEX');
    expect(pexElbow.intelligence.size, '1/2 in');
    expect(pexElbow.intelligence.shapeOrStyle, contains('elbow'));
    expect(pexElbow.intelligence.receiptPatterns, isNotEmpty);
    expect(pexElbow.intelligence.ocrMistakePatterns, contains('PEX->PFX'));
    expect(pexElbow.intelligence.negativeMatchTokens, contains('PVC 90 elbow'));
    expect(
      pexElbow.intelligence.classification.inventoryCategory,
      pexElbow.category,
    );
    expect(pexElbow.intelligence.autoGenerated, isTrue);
    expect(
      castIronCoupling.marketScopes,
      contains(WorkSupplyMarketScope.lightIndustrial),
    );
    expect(
      castIronCoupling.marketScopes,
      contains(WorkSupplyMarketScope.commercial),
    );
    expect(castIronCoupling.packTier, WorkSupplyPackTier.professional);
  });
}
