import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../tool/work_supply_catalog_blueprint_generator.dart';

void main() {
  test(
    'catalog blueprint generator writes review-only plumbing blueprints',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_catalog_blueprints_',
      );
      addTearDown(() => output.delete(recursive: true));

      final stdout = _MemorySink();
      final stderr = _MemorySink();
      final exit = await runWorkSupplyCatalogBlueprintGenerator(
        [
          '--trade',
          'plumbing',
          '--scope',
          'residential',
          '--tier',
          'core',
          '--locale',
          'en-US',
          '--limit',
          '20',
          '--output-dir',
          output.path,
        ],
        stdout: stdout,
        stderr: stderr,
      );

      expect(exit, 0, reason: stderr.content);
      expect(stdout.content, contains('QA_CATALOG_BLUEPRINTS'));

      final root = Directory(
        '${output.path}/work_supply_catalog/plumbing/residential/core/en-US',
      );
      final blueprints =
          jsonDecode(
                File('${root.path}/item_blueprints.json').readAsStringSync(),
              )
              as List;
      final manifest =
          jsonDecode(File('${root.path}/manifest.json').readAsStringSync())
              as Map;

      expect(blueprints, hasLength(20));
      expect(manifest['generatedCount'], 20);
      expect(manifest['promotionMode'], 'review-required');
      expect(manifest['writesProductionCatalog'], isFalse);
      expect(manifest['liveServicesAllowed'], isFalse);

      final first = blueprints.first as Map;
      expect(first['id'].toString(), startsWith('QA_PLUMBING'));
      expect(first['aliases'], isNotEmpty);
      expect(first['receiptPatterns'], isNotEmpty);
      expect(first['negativeMatchTokens'], isNotEmpty);
      expect(first['sourceType'], 'synthetic-blueprint');
      expect(first['verifiedManually'], isFalse);
      expect(first['autoGenerated'], isTrue);
      expect(first['needsReview'], isTrue);
      expect(first['promotionMode'], 'manual-review-required');
      expect(first['classification'], isA<Map>());
    },
  );

  test(
    'catalog blueprint generator supports top residential core trades',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_catalog_blueprints_trades_',
      );
      addTearDown(() => output.delete(recursive: true));

      for (final trade in ['plumbing', 'electrical', 'hvac']) {
        final exit = await runWorkSupplyCatalogBlueprintGenerator(
          [
            '--trade',
            trade,
            '--scope',
            'residential',
            '--tier',
            'core',
            '--locale',
            'en-US',
            '--limit',
            '8',
            '--output-dir',
            output.path,
          ],
          stdout: _MemorySink(),
          stderr: _MemorySink(),
        );
        expect(exit, 0);
        final blueprintFile = File(
          '${output.path}/work_supply_catalog/$trade/residential/core/en-US/'
          'item_blueprints.json',
        );
        final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
        expect(blueprints, hasLength(8));
        expect(
          blueprints.every(
            (entry) => entry['promotionMode'] == 'manual-review-required',
          ),
          isTrue,
        );
        expect(
          blueprints.every(
            (entry) => entry['trade'] != 'Plumbing' || trade == 'plumbing',
          ),
          isTrue,
        );
      }
    },
  );

  test('catalog blueprint generator rejects empty batches', () async {
    final stderr = _MemorySink();
    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      ['--limit', '0'],
      stdout: _MemorySink(),
      stderr: stderr,
    );

    expect(exit, 64);
    expect(stderr.content, contains('--limit must be greater than zero'));
  });

  test('catalog blueprint generator supports plumbing standard tier', () async {
    final output = await Directory.systemTemp.createTemp(
      'maintainiac_catalog_blueprints_standard_',
    );
    addTearDown(() => output.delete(recursive: true));

    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      [
        '--trade',
        'plumbing',
        '--scope',
        'residential',
        '--tier',
        'standard',
        '--limit',
        '12',
        '--output-dir',
        output.path,
      ],
      stdout: _MemorySink(),
      stderr: _MemorySink(),
    );

    expect(exit, 0);
    final blueprintFile = File(
      '${output.path}/work_supply_catalog/plumbing/residential/standard/en-US/'
      'item_blueprints.json',
    );
    final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
    expect(blueprints, hasLength(12));
    expect(blueprints.toString(), contains('toilet_wax_ring_with_bolts'));
    expect(blueprints.toString(), contains('manual-review-required'));
  });

  test('catalog blueprint generator supports electrical standard tier', () async {
    final output = await Directory.systemTemp.createTemp(
      'maintainiac_catalog_blueprints_electrical_standard_',
    );
    addTearDown(() => output.delete(recursive: true));

    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      [
        '--trade',
        'electrical',
        '--scope',
        'residential',
        '--tier',
        'standard',
        '--limit',
        '15',
        '--output-dir',
        output.path,
      ],
      stdout: _MemorySink(),
      stderr: _MemorySink(),
    );

    expect(exit, 0);
    final blueprintFile = File(
      '${output.path}/work_supply_catalog/electrical/residential/standard/en-US/'
      'item_blueprints.json',
    );
    final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
    expect(blueprints, hasLength(15));
    expect(blueprints.toString(), contains('gfci_receptacle_white'));
    expect(blueprints.toString(), contains('grounding_rod_clamp'));
  });

  test('catalog blueprint generator supports hvac standard tier', () async {
    final output = await Directory.systemTemp.createTemp(
      'maintainiac_catalog_blueprints_hvac_standard_',
    );
    addTearDown(() => output.delete(recursive: true));

    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      [
        '--trade',
        'hvac',
        '--scope',
        'residential',
        '--tier',
        'standard',
        '--limit',
        '16',
        '--output-dir',
        output.path,
      ],
      stdout: _MemorySink(),
      stderr: _MemorySink(),
    );

    expect(exit, 0);
    final blueprintFile = File(
      '${output.path}/work_supply_catalog/hvac/residential/standard/en-US/'
      'item_blueprints.json',
    );
    final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
    expect(blueprints, hasLength(16));
    expect(blueprints.toString(), contains('dual_run_capacitor'));
    expect(blueprints.toString(), contains('start_collar'));
  });

  test('catalog blueprint generator supports hvac professional tier', () async {
    final output = await Directory.systemTemp.createTemp(
      'maintainiac_catalog_blueprints_hvac_professional_',
    );
    addTearDown(() => output.delete(recursive: true));

    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      [
        '--trade',
        'hvac',
        '--scope',
        'residential',
        '--tier',
        'professional',
        '--limit',
        '24',
        '--output-dir',
        output.path,
      ],
      stdout: _MemorySink(),
      stderr: _MemorySink(),
    );

    expect(exit, 0);
    final blueprintFile = File(
      '${output.path}/work_supply_catalog/hvac/residential/professional/'
      'en-US/item_blueprints.json',
    );
    final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
    expect(blueprints, hasLength(24));
    expect(blueprints.toString(), contains('furnace_flame_sensor'));
    expect(blueprints.toString(), contains('line_set_insulation'));
  });

  test('catalog blueprint generator supports hvac complete tier', () async {
    final output = await Directory.systemTemp.createTemp(
      'maintainiac_catalog_blueprints_hvac_complete_',
    );
    addTearDown(() => output.delete(recursive: true));

    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      [
        '--trade',
        'hvac',
        '--scope',
        'residential',
        '--tier',
        'complete',
        '--limit',
        '28',
        '--output-dir',
        output.path,
      ],
      stdout: _MemorySink(),
      stderr: _MemorySink(),
    );

    expect(exit, 0);
    final blueprintFile = File(
      '${output.path}/work_supply_catalog/hvac/residential/complete/'
      'en-US/item_blueprints.json',
    );
    final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
    expect(blueprints, hasLength(28));
    expect(blueprints.toString(), contains('inline_float_switch'));
    expect(blueprints.toString(), contains('heat_pump_defrost_board'));
  });

  test(
    'catalog blueprint generator supports plumbing professional tier',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_catalog_blueprints_plumbing_professional_',
      );
      addTearDown(() => output.delete(recursive: true));

      final exit = await runWorkSupplyCatalogBlueprintGenerator(
        [
          '--trade',
          'plumbing',
          '--scope',
          'residential',
          '--tier',
          'professional',
          '--limit',
          '28',
          '--output-dir',
          output.path,
        ],
        stdout: _MemorySink(),
        stderr: _MemorySink(),
      );

      expect(exit, 0);
      final blueprintFile = File(
        '${output.path}/work_supply_catalog/plumbing/residential/professional/'
        'en-US/item_blueprints.json',
      );
      final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
      expect(blueprints, hasLength(28));
      expect(blueprints.toString(), contains('tubular_p_trap'));
      expect(blueprints.toString(), contains('sump_pump_check_valve'));
    },
  );

  test('catalog blueprint generator supports plumbing complete tier', () async {
    final output = await Directory.systemTemp.createTemp(
      'maintainiac_catalog_blueprints_plumbing_complete_',
    );
    addTearDown(() => output.delete(recursive: true));

    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      [
        '--trade',
        'plumbing',
        '--scope',
        'residential',
        '--tier',
        'complete',
        '--limit',
        '40',
        '--output-dir',
        output.path,
      ],
      stdout: _MemorySink(),
      stderr: _MemorySink(),
    );

    expect(exit, 0);
    final blueprintFile = File(
      '${output.path}/work_supply_catalog/plumbing/residential/complete/'
      'en-US/item_blueprints.json',
    );
    final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
    expect(blueprints, hasLength(40));
    expect(blueprints.toString(), contains('cleanout_plug_cover'));
    expect(blueprints.toString(), contains('pressure_reducing_valve'));
  });

  test(
    'catalog blueprint generator supports electrical professional tier',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_catalog_blueprints_electrical_professional_',
      );
      addTearDown(() => output.delete(recursive: true));

      final exit = await runWorkSupplyCatalogBlueprintGenerator(
        [
          '--trade',
          'electrical',
          '--scope',
          'residential',
          '--tier',
          'professional',
          '--limit',
          '22',
          '--output-dir',
          output.path,
        ],
        stdout: _MemorySink(),
        stderr: _MemorySink(),
      );

      expect(exit, 0);
      final blueprintFile = File(
        '${output.path}/work_supply_catalog/electrical/residential/'
        'professional/en-US/item_blueprints.json',
      );
      final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
      expect(blueprints, hasLength(22));
      expect(blueprints.toString(), contains('double_pole_breaker'));
      expect(blueprints.toString(), contains('ground_rod_copper'));
    },
  );

  test(
    'catalog blueprint generator supports electrical complete tier',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_catalog_blueprints_electrical_complete_',
      );
      addTearDown(() => output.delete(recursive: true));

      final exit = await runWorkSupplyCatalogBlueprintGenerator(
        [
          '--trade',
          'electrical',
          '--scope',
          'residential',
          '--tier',
          'complete',
          '--limit',
          '28',
          '--output-dir',
          output.path,
        ],
        stdout: _MemorySink(),
        stderr: _MemorySink(),
      );

      expect(exit, 0);
      final blueprintFile = File(
        '${output.path}/work_supply_catalog/electrical/residential/complete/'
        'en-US/item_blueprints.json',
      );
      final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
      expect(blueprints, hasLength(28));
      expect(blueprints.toString(), contains('weatherproof_in_use_cover'));
      expect(blueprints.toString(), contains('conduit_body_lb'));
    },
  );

  test(
    'catalog blueprint generator covers release-one Core service families',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_catalog_blueprints_core_service_families_',
      );
      addTearDown(() => output.delete(recursive: true));

      const expectedFamiliesByTrade = {
        'plumbing': [
          'toilet_fill_valve',
          'lavatory_p_trap',
          'water_softener_salt_pellets',
          'well_pressure_switch',
        ],
        'electrical': [
          'gfci_receptacle_white',
          'single_pole_breaker',
          'lever_wire_connector',
          'anti_short_bushing',
        ],
        'hvac': [
          'dual_run_capacitor',
          'definite_purpose_contactor',
          'condensate_pump',
          'furnace_flame_sensor',
          'humidifier_water_panel',
        ],
      };

      for (final entry in expectedFamiliesByTrade.entries) {
        final exit = await runWorkSupplyCatalogBlueprintGenerator(
          [
            '--trade',
            entry.key,
            '--scope',
            'residential',
            '--tier',
            'core',
            '--locale',
            'en-US',
            '--limit',
            '120',
            '--output-dir',
            output.path,
          ],
          stdout: _MemorySink(),
          stderr: _MemorySink(),
        );

        expect(exit, 0, reason: entry.key);
        final blueprintFile = File(
          '${output.path}/work_supply_catalog/${entry.key}/residential/'
          'core/en-US/item_blueprints.json',
        );
        final blueprints = jsonDecode(blueprintFile.readAsStringSync()) as List;
        final families = {
          for (final row in blueprints.cast<Map>())
            row['itemFamily'].toString(),
        };

        expect(
          families,
          containsAll(entry.value),
          reason:
              '${entry.key} Core blueprints must cover daily residential '
              'service families, not just legacy starter examples.',
        );
      }
    },
  );

  test('catalog blueprint generator rejects unsupported tier cells', () async {
    final stderr = _MemorySink();
    final exit = await runWorkSupplyCatalogBlueprintGenerator(
      ['--trade', 'garage', '--scope', 'residential', '--tier', 'standard'],
      stdout: _MemorySink(),
      stderr: stderr,
    );

    expect(exit, 65);
    expect(stderr.content, contains('trade=garage'));
    expect(stderr.content, contains('tier=standard'));
  });
}

class _MemorySink implements IOSink {
  final _buffer = StringBuffer();

  String get content => _buffer.toString();

  @override
  void write(Object? object) => _buffer.write(object);

  @override
  void writeln([Object? object = '']) => _buffer.writeln(object);

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
