import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../tool/work_supply_catalog_blueprint_validate.dart';
import '../tool/work_supply_catalog_blueprint_generator.dart';

void main() {
  test(
    'blueprint validator accepts generated review-only blueprints',
    () async {
      final output = await Directory.systemTemp.createTemp(
        'maintainiac_blueprint_validator_ok_',
      );
      addTearDown(() => output.delete(recursive: true));

      await runWorkSupplyCatalogBlueprintGenerator(
        ['--limit', '8', '--output-dir', output.path],
        stdout: _MemorySink(),
        stderr: _MemorySink(),
      );

      final blueprintPath =
          '${output.path}/work_supply_catalog/plumbing/residential/core/en-US/'
          'item_blueprints.json';
      final stdout = _MemorySink();
      final exit = await runWorkSupplyCatalogBlueprintValidator(
        ['--input', blueprintPath],
        stdout: stdout,
        stderr: _MemorySink(),
      );

      expect(exit, 0);
      expect(stdout.content, contains('QA_CATALOG_BLUEPRINT_VALIDATION'));
      expect(stdout.content, contains('"issueCount": 0'));
      expect(stdout.content, contains('"promotionAllowed": true'));
      expect(stdout.content, contains('"liveServicesAllowed": false'));
    },
  );

  test(
    'blueprint validator rejects unsafe promotion and missing metadata',
    () async {
      final directory = await Directory.systemTemp.createTemp(
        'maintainiac_blueprint_validator_bad_',
      );
      addTearDown(() => directory.delete(recursive: true));
      final file = File('${directory.path}/bad_blueprints.json');
      file.writeAsStringSync(
        jsonEncode([
          {
            'id': 'BAD-1',
            'canonicalName': 'Bad Item',
            'trade': 'Plumbing',
            'category': 'Fittings',
            'system': 'PEX',
            'itemType': 'Elbow',
            'itemFamily': 'bad',
            'material': 'brass',
            'size': '1/2 in',
            'unit': 'each',
            'aliases': <String>[],
            'receiptPatterns': <String>[],
            'negativeMatchTokens': <String>[],
            'highImportanceTokens': ['1/2 in'],
            'classification': <String, Object?>{},
            'sourceConfidence': 'generated-needs-review',
            'verifiedManually': true,
            'autoGenerated': false,
            'needsReview': false,
            'promotionMode': 'auto-promote',
          },
        ]),
      );

      final stdout = _MemorySink();
      final exit = await runWorkSupplyCatalogBlueprintValidator(
        ['--input', file.path],
        stdout: stdout,
        stderr: _MemorySink(),
      );

      expect(exit, 1);
      expect(stdout.content, contains('empty_aliases'));
      expect(stdout.content, contains('empty_receiptPatterns'));
      expect(stdout.content, contains('empty_negativeMatchTokens'));
      expect(
        stdout.content,
        contains('generated_blueprint_cannot_be_verified'),
      );
      expect(stdout.content, contains('promotion_must_require_manual_review'));
    },
  );
}

class _MemorySink implements IOSink {
  final _buffer = StringBuffer();

  String get content => _buffer.toString();

  @override
  void write(Object? object) => _buffer.write(object);

  @override
  void writeln([Object? object = '']) => _buffer.writeln(object);

  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}
