part of 'maintenance_models.dart';

const maintenanceCatalog = <MaintenanceCatalogItem>[
  MaintenanceCatalogItem(
    name: 'Engine Oil',
    icon: '🛢️',
    importance: 100,
    defaultMiles: 5000,
    defaultMonths: 6,
    detailA: 'Oil type',
    detailB: 'Oil weight',
  ),
  MaintenanceCatalogItem(
    name: 'Oil Filter',
    icon: '🧰',
    importance: 92,
    defaultMiles: 5000,
    defaultMonths: 6,
    detailA: 'Filter type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Transmission Fluid and Filter',
    icon: '⚙️',
    importance: 96,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Fluid family',
    detailB: 'Specification',
  ),
  MaintenanceCatalogItem(
    name: 'Coolant',
    icon: '🌡️',
    importance: 88,
    defaultMiles: 30000,
    defaultMonths: 36,
    detailA: 'Coolant type',
    detailB: 'Mix',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Fluid',
    icon: '🛑',
    importance: 94,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Fluid rating',
    detailB: 'Container detail',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Pads',
    icon: '🛑',
    importance: 90,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Axle',
    detailB: 'Pad material',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Rotors',
    icon: '🛑',
    importance: 90,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Axle',
    detailB: 'Service type',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Shoes',
    icon: '🛑',
    importance: 90,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Axle',
    detailB: 'Shoe type',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Drums',
    icon: '🛑',
    importance: 90,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Axle',
    detailB: 'Service type',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Calipers',
    icon: '🛑',
    importance: 92,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Axle',
    detailB: 'Service type',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Hoses and Lines',
    icon: '🛑',
    importance: 96,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Position',
    detailB: 'Material / notes',
  ),
  MaintenanceCatalogItem(
    name: 'Brake Inspection',
    icon: '🛑',
    importance: 94,
    defaultMiles: 0,
    defaultMonths: 12,
    detailA: 'Inspection scope',
    detailB: 'Findings / notes',
  ),
  MaintenanceCatalogItem(
    name: 'Engine Air Filter',
    icon: '🌬️',
    importance: 72,
    defaultMiles: 12000,
    defaultMonths: 12,
    detailA: 'Filter style',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Cabin Air Filter',
    icon: '🌬️',
    importance: 55,
    defaultMiles: 12000,
    defaultMonths: 12,
    detailA: 'Filter style',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Spark Plugs',
    icon: '⚡',
    importance: 84,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Plug type',
    detailB: 'Gap',
  ),
  MaintenanceCatalogItem(
    name: 'Ignition Coils',
    icon: '⚡',
    importance: 82,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Coil type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Spark Plug Wires',
    icon: '⚡',
    importance: 68,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Wire type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'PCV Valve',
    icon: '🔧',
    importance: 74,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Valve type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Oxygen Sensors',
    icon: '🔧',
    importance: 80,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Sensor position',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Catalytic Converter',
    icon: '🔧',
    importance: 90,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Converter type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'EGR Valve',
    icon: '🔧',
    importance: 76,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Valve type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Mass Air Flow Sensor',
    icon: '🌬️',
    importance: 78,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Sensor type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Valve Cover Gasket',
    icon: '🔧',
    importance: 78,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Cover position',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Oil Pan Gasket',
    icon: '🛢️',
    importance: 80,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Pan type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Serpentine Belt',
    icon: '🔁',
    importance: 86,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Belt type',
    detailB: 'Length/detail',
  ),
  MaintenanceCatalogItem(
    name: 'Belt Tensioner',
    icon: '🔁',
    importance: 82,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Tensioner type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Idler Pulley',
    icon: '🔁',
    importance: 76,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Pulley type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Timing Belt',
    icon: '⏱️',
    importance: 96,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Belt type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Radiator Hose',
    icon: '〰️',
    importance: 82,
    defaultMiles: 60000,
    defaultMonths: 48,
    detailA: 'Hose position',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Radiator',
    icon: '🌡️',
    importance: 90,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Radiator type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Radiator Cap',
    icon: '🌡️',
    importance: 62,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Pressure rating',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Water Pump',
    icon: '💧',
    importance: 94,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Pump type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Thermostat',
    icon: '🌡️',
    importance: 88,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Temperature rating',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Steering and Suspension Inspection',
    icon: '🔧',
    importance: 88,
    defaultMiles: 0,
    defaultMonths: 12,
    detailA: 'Inspection scope',
    detailB: 'Findings / notes',
  ),
  MaintenanceCatalogItem(
    name: 'Shocks and Struts',
    icon: '🔧',
    importance: 86,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Position',
    detailB: 'Component',
  ),
  MaintenanceCatalogItem(
    name: 'Ball Joints',
    icon: '🔧',
    importance: 90,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Position',
    detailB: 'Joint position',
  ),
  MaintenanceCatalogItem(
    name: 'Tie Rod Ends',
    icon: '🔧',
    importance: 90,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Position',
    detailB: 'Rod position',
  ),
  MaintenanceCatalogItem(
    name: 'Sway Bar Links',
    icon: '🔧',
    importance: 78,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Position',
    detailB: 'Link detail',
  ),
  MaintenanceCatalogItem(
    name: 'Wheel Bearings',
    icon: '🛞',
    importance: 90,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Position',
    detailB: 'Component',
  ),
  MaintenanceCatalogItem(
    name: 'CV Axles',
    icon: '⚙️',
    importance: 88,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Position',
    detailB: 'Axle detail',
  ),
  MaintenanceCatalogItem(
    name: 'Engine Mounts',
    icon: '🔧',
    importance: 78,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Mount type',
    detailB: 'Position / notes',
  ),
  ...maintenanceCatalogUtilityItems,
];
