part of 'maintenance_models.dart';

const maintenanceCatalogUtilityItems = <MaintenanceCatalogItem>[
  MaintenanceCatalogItem(
    name: 'Wiper Blades',
    icon: '🌧️',
    importance: 70,
    defaultMiles: 12000,
    defaultMonths: 12,
    detailA: 'Blade position',
    detailB: 'Blade size',
  ),
  MaintenanceCatalogItem(
    name: 'Battery',
    icon: '🔋',
    importance: 86,
    defaultMiles: 0,
    defaultMonths: 48,
    detailA: 'Battery type',
    detailB: 'Group size',
    timeOnly: true,
  ),
  MaintenanceCatalogItem(
    name: 'Alternator',
    icon: '⚡',
    importance: 88,
    defaultMiles: 50000,
    defaultMonths: 60,
    detailA: 'Component type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Starter',
    icon: '⚡',
    importance: 88,
    defaultMiles: 50000,
    defaultMonths: 60,
    detailA: 'Component type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Power Steering Fluid',
    icon: '💧',
    importance: 78,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Fluid type',
    detailB: 'Specification',
  ),
  MaintenanceCatalogItem(
    name: 'Differential Fluid',
    icon: '⚙️',
    importance: 82,
    defaultMiles: 50000,
    defaultMonths: 48,
    detailA: 'Fluid type',
    detailB: 'Viscosity',
  ),
  MaintenanceCatalogItem(
    name: 'Transfer Case Fluid',
    icon: '⚙️',
    importance: 84,
    defaultMiles: 30000,
    defaultMonths: 36,
    detailA: 'Fluid type',
    detailB: 'Specification',
  ),
  MaintenanceCatalogItem(
    name: 'Fuel Filter',
    icon: '⛽',
    importance: 76,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Filter type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Fuel Pump',
    icon: '⛽',
    importance: 92,
    defaultMiles: 60000,
    defaultMonths: 60,
    detailA: 'Pump type',
    detailB: 'Part detail',
  ),
  MaintenanceCatalogItem(
    name: 'Fuel System Service',
    icon: '⛽',
    importance: 72,
    defaultMiles: 30000,
    defaultMonths: 24,
    detailA: 'Service type',
    detailB: 'Product / notes',
  ),
  MaintenanceCatalogItem(
    name: 'Air Conditioning Service',
    icon: '❄️',
    importance: 68,
    defaultMiles: 0,
    defaultMonths: 24,
    detailA: 'Service type',
    detailB: 'Refrigerant',
    timeOnly: true,
  ),
  MaintenanceCatalogItem(
    name: 'Tires',
    icon: '🛞',
    importance: 92,
    defaultMiles: 50000,
    defaultMonths: 60,
    detailA: 'Brand / tire type',
    detailB: 'Tire size',
  ),
  MaintenanceCatalogItem(
    name: 'Tire Rotation',
    icon: '🛞',
    importance: 82,
    defaultMiles: 5000,
    defaultMonths: 6,
    detailA: 'Rotation pattern',
    detailB: 'Position notes',
  ),
  MaintenanceCatalogItem(
    name: 'Wheel Alignment',
    icon: '🛞',
    importance: 84,
    defaultMiles: 0,
    defaultMonths: 12,
    detailA: 'Alignment type',
    detailB: 'Measurement / notes',
  ),
  MaintenanceCatalogItem(
    name: 'Wheel Balancing',
    icon: '🛞',
    importance: 78,
    defaultMiles: 0,
    defaultMonths: 12,
    detailA: 'Balance type',
    detailB: 'Wheel / axle notes',
  ),
  MaintenanceCatalogItem(
    name: 'Washer Fluid',
    icon: '💧',
    importance: 45,
    defaultMiles: 0,
    defaultMonths: 3,
    detailA: 'Fluid type',
    detailB: 'Season rating',
    timeOnly: true,
  ),
  MaintenanceCatalogItem(
    name: 'Key Fob Battery',
    icon: '🔑',
    importance: 40,
    defaultMiles: 0,
    defaultMonths: 24,
    detailA: 'Battery type',
    detailB: 'Quantity',
    timeOnly: true,
  ),
  MaintenanceCatalogItem(
    name: 'Registration',
    icon: '📄',
    importance: 98,
    defaultMiles: 0,
    defaultMonths: 12,
    detailA: 'Renewal type',
    detailB: 'Renewal period',
    timeOnly: true,
  ),
  MaintenanceCatalogItem(
    name: 'Inspection',
    icon: '✅',
    importance: 97,
    defaultMiles: 0,
    defaultMonths: 12,
    detailA: 'Inspection type',
    detailB: 'Renewal period',
    timeOnly: true,
  ),
];
