Set<String> qaSuiteFilterFrom({
  required String suiteCsv,
  required String preset,
}) {
  final explicitSuites = suiteCsv
      .split(',')
      .map((suite) => suite.trim())
      .where((suite) => suite.isNotEmpty)
      .toSet();
  if (explicitSuites.isNotEmpty) return explicitSuites;
  switch (preset.trim().toLowerCase()) {
    case 'main':
    case 'backbone':
      return const {'maintainiac.qa_backbone_contract', 'qa.threshold_gate'};
    case 'quick':
      return const {
        'inventory.security_privacy',
        'inventory.boundary_guard',
        'inventory.no_live_services_contract',
        'inventory.review_safety_contract',
        'inventory.result_contract',
        'inventory.evidence_attribution',
        'inventory.pack_lifecycle',
        'inventory.pack_recovery_contract',
        'inventory.pack_health_score',
        'inventory.scalability',
        'inventory.runtime_profile_contract',
        'inventory.runtime_measurement',
        'inventory.generated_manifest_contract',
        'inventory.generated_fixture_performance_contract',
        'inventory.failure_taxonomy_contract',
        'inventory.fixture_governance',
        'inventory.fixture_coverage_matrix',
        'inventory.fixture_corpus_contract',
        'inventory.fake_user_review_workflow',
        'inventory.holdout_fixture_contract',
        'inventory.determinism',
        'inventory.metamorphic_variants',
        'inventory.property_cases',
        'inventory.separation_safety',
        'inventory.conflict_graph',
        'inventory.ranked_candidate_accuracy',
        'inventory.trade_context',
        'inventory.merchant_rules',
        'inventory.noise_lines',
        'inventory.accuracy_budget',
        'inventory.economics_contract',
        'inventory.estimate_section_ranking',
        'inventory.confidence_calibration',
        'inventory.math_reconciliation',
        'inventory.locale_contract',
        'inventory.telemetry_contract',
        'inventory.device_storage_contract',
        'inventory.correction_feedback_contract',
        'inventory.release_manifest',
        'inventory.release_one_scorecard_contract',
        'inventory.release_orchestration_contract',
        'inventory.release_shard_manifest',
        'inventory.release_signoff_manifest',
        'inventory.harness_registry',
        'inventory.known_debt_ledger',
        'inventory.artifact_contract',
        'inventory.artifact_retention_contract',
        'inventory.admin_report_contract',
        'inventory.execution_command_contract',
        'inventory.portability_contract',
        'inventory.harness_maintainability_contract',
        'inventory.parser_platform_contract',
        'inventory.category_reuse_contract',
        'inventory.data_provenance_contract',
        'inventory.legal_safety_contract',
        'inventory.validation_strategy_contract',
        'inventory.slo_metrics_contract',
        'inventory.mutation_contract',
        'inventory.mutation_scenario_matrix',
        'inventory.mutation_dry_run_plan',
        'inventory.mutation_fault_probe',
        'inventory.mutation_runner_contract',
        'inventory.requirement_coverage',
        'inventory.profile_matrix',
        'inventory.baseline_contract',
        'qa.threshold_gate',
      };
    case 'fixtures':
      return const {
        'inventory.golden_fixtures',
        'inventory.review_safety_contract',
        'inventory.result_contract',
        'inventory.evidence_attribution',
        'inventory.pack_lifecycle',
        'inventory.pack_recovery_contract',
        'inventory.pack_health_score',
        'inventory.scalability',
        'inventory.no_live_services_contract',
        'inventory.runtime_profile_contract',
        'inventory.runtime_measurement',
        'inventory.generated_manifest_contract',
        'inventory.generated_fixture_performance_contract',
        'inventory.failure_taxonomy_contract',
        'inventory.fixture_governance',
        'inventory.fixture_coverage_matrix',
        'inventory.fixture_corpus_contract',
        'inventory.fake_user_review_workflow',
        'inventory.holdout_fixture_contract',
        'inventory.changed_item_impact',
        'inventory.determinism',
        'inventory.metamorphic_variants',
        'inventory.separation_safety',
        'inventory.conflict_graph',
        'inventory.ranked_candidate_accuracy',
        'inventory.accuracy_budget',
        'inventory.estimate_section_ranking',
        'inventory.telemetry_contract',
        'inventory.device_storage_contract',
        'inventory.correction_feedback_contract',
        'inventory.release_manifest',
        'inventory.release_one_scorecard_contract',
        'inventory.release_orchestration_contract',
        'inventory.release_shard_manifest',
        'inventory.release_signoff_manifest',
        'inventory.harness_registry',
        'inventory.known_debt_ledger',
        'inventory.artifact_contract',
        'inventory.artifact_retention_contract',
        'inventory.admin_report_contract',
        'inventory.execution_command_contract',
        'inventory.portability_contract',
        'inventory.harness_maintainability_contract',
        'inventory.parser_platform_contract',
        'inventory.category_reuse_contract',
        'inventory.data_provenance_contract',
        'inventory.legal_safety_contract',
        'inventory.validation_strategy_contract',
        'inventory.slo_metrics_contract',
        'inventory.mutation_contract',
        'inventory.mutation_scenario_matrix',
        'inventory.mutation_dry_run_plan',
        'inventory.mutation_fault_probe',
        'inventory.mutation_runner_contract',
        'inventory.requirement_coverage',
        'inventory.profile_matrix',
        'inventory.baseline_contract',
        'qa.threshold_gate',
      };
    case 'catalog':
      return const {
        'inventory.catalog_schema',
        'inventory.catalog_coverage',
        'inventory.alias_conflicts',
        'inventory.changed_item_impact',
        'inventory.pack_lifecycle',
        'inventory.pack_health_score',
        'inventory.scalability',
        'qa.threshold_gate',
      };
    default:
      return const {};
  }
}
