import 'dart:io';

import '../qa_harness/qa_harness.dart';

class WorkSupplyParserDataProvenanceSuite extends QaSuite {
  const WorkSupplyParserDataProvenanceSuite()
    : super('inventory.data_provenance_contract');

  static const _planPath = 'docs/inventory_parser_qa_harness_plan.md';
  static const _intelligencePath =
      'lib/screens/work_supplies/data/work_supply_item_intelligence.dart';
  static const _packPayloadPath =
      'lib/screens/work_supplies/data/work_supply_catalog_pack_payload.dart';
  static const _fixtureGovernancePath =
      'test/support/work_supply_parser_qa/work_supply_parser_governance_qa.dart';
  static const _fixtureCorpusPath =
      'test/support/work_supply_parser_qa/work_supply_parser_fixture_corpus_contract_qa.dart';
  static const _correctionFeedbackPath =
      'test/support/work_supply_parser_qa/work_supply_parser_correction_feedback_qa.dart';

  static const _contracts = [
    _ProvenanceContract(
      name: 'ground_truth_governance_docs',
      path: _planPath,
      tokens: [
        'Ground-truth dataset governance',
        'synthetic/real flag',
        'source owner',
        'review date',
        'expected-answer confidence',
      ],
    ),
    _ProvenanceContract(
      name: 'catalog_item_source_metadata',
      path: _intelligencePath,
      tokens: [
        'sourceConfidence',
        'verifiedManually',
        'autoGenerated',
        'needsReview',
      ],
    ),
    _ProvenanceContract(
      name: 'pack_payload_source_metadata',
      path: _packPayloadPath,
      tokens: [
        "'sourceConfidence'",
        "'verifiedManually'",
        "'autoGenerated'",
        "'needsReview'",
        "'source'",
      ],
    ),
    _ProvenanceContract(
      name: 'fixture_identity_governance',
      path: _fixtureGovernancePath,
      tokens: [
        'fixture_missing_id',
        'fixture_duplicate_global_id',
        'fixture_missing_expected_outcome',
        'fixture_invalid_max_confidence',
      ],
    ),
    _ProvenanceContract(
      name: 'fixture_private_data_guard',
      path: _fixtureCorpusPath,
      tokens: [
        'card_like_number',
        'email',
        'phone',
        'address',
        'privacy-safe synthetic fixture text',
      ],
    ),
    _ProvenanceContract(
      name: 'manual_promotion_boundary',
      path: _correctionFeedbackPath,
      tokens: [
        'manual_promotion',
        'local_correction',
        'community_correction',
        'official_pack_mutation',
      ],
    ),
  ];

  @override
  Future<QaSuiteResult> run(QaContext context) async {
    final timer = QaStopwatch.start();
    final failures = <QaFailure>[];
    final present = <String>[];
    var checked = 0;

    for (final contract in _contracts) {
      checked += contract.tokens.length;
      final source = _read(contract.path, failures);
      final missing = [
        for (final token in contract.tokens)
          if (!source.contains(token)) token,
      ];
      if (missing.isEmpty) {
        present.add(contract.name);
        continue;
      }
      failures.add(
        QaFailure(
          suite: name,
          id: 'missing_data_provenance_contract:${contract.name}',
          message: 'Parser QA data provenance contract is incomplete.',
          expected: contract.tokens.join(' + '),
          actual: 'missing ${missing.join(' + ')}',
          suggestedFix:
              'Add source/provenance metadata before treating generated parser data as release-grade.',
          metadata: const {'triageCategory': QaFailureTriage.governance},
        ),
      );
    }

    return timer.finish(
      suite: name,
      checked: checked + _contracts.length,
      failures: failures,
      maxFailures: context.maxFailuresPerSuite,
      metrics: {
        'presentContracts': present,
        'contractCount': _contracts.length,
      },
    );
  }

  String _read(String path, List<QaFailure> failures) {
    final file = File(path);
    if (file.existsSync()) return file.readAsStringSync();
    failures.add(
      QaFailure(
        suite: name,
        id: 'missing_data_provenance_scan_file:$path',
        message: 'Data provenance scan file is missing.',
        expected: path,
        actual: 'not found',
        suggestedFix: 'Update this suite if provenance contract files move.',
        metadata: const {'triageCategory': QaFailureTriage.schema},
      ),
    );
    return '';
  }
}

class _ProvenanceContract {
  const _ProvenanceContract({
    required this.name,
    required this.path,
    required this.tokens,
  });

  final String name;
  final String path;
  final List<String> tokens;
}
