import 'dart:io';

import '../qa_harness/qa_harness.dart';

class WorkSupplyParserBlueprintPromotionSuite extends QaSuite {
  const WorkSupplyParserBlueprintPromotionSuite()
    : super('inventory.blueprint_promotion_contract');

  static const _requiredGeneratorTokens = {
    'manual-review-required',
    'generated-needs-review',
    'verifiedManually',
    'autoGenerated',
    'needsReview',
    'writesProductionCatalog',
    'liveServicesAllowed',
  };

  static const _requiredValidatorTokens = {
    'generated_blueprint_cannot_be_verified_manually',
    'autoGenerated_must_be_true',
    'needsReview_must_be_true',
    'promotion_must_require_manual_review',
    'promotionAllowed',
    'liveServicesAllowed',
  };

  @override
  Future<QaSuiteResult> run(QaContext context) async {
    final timer = QaStopwatch.start();
    final failures = <QaFailure>[];
    _checkTokens(
      failures,
      file: File('tool/work_supply_catalog_blueprint_generator.dart'),
      tokens: _requiredGeneratorTokens,
      prefix: 'generator',
    );
    _checkTokens(
      failures,
      file: File('tool/work_supply_catalog_blueprint_validate.dart'),
      tokens: _requiredValidatorTokens,
      prefix: 'validator',
    );

    return timer.finish(
      suite: name,
      checked:
          _requiredGeneratorTokens.length + _requiredValidatorTokens.length,
      failures: failures,
      maxFailures: context.maxFailuresPerSuite,
      metrics: {
        'requiredGeneratorTokens': _requiredGeneratorTokens.toList()..sort(),
        'requiredValidatorTokens': _requiredValidatorTokens.toList()..sort(),
        'contract':
            'Generated catalog blueprints are never production catalog writes and must remain manual-review-only until separately promoted.',
      },
    );
  }

  void _checkTokens(
    List<QaFailure> failures, {
    required File file,
    required Set<String> tokens,
    required String prefix,
  }) {
    final text = file.existsSync() ? file.readAsStringSync() : '';
    for (final token in tokens) {
      if (text.contains(token)) continue;
      failures.add(
        QaFailure(
          suite: name,
          id: 'missing_${prefix}_promotion_token:$token',
          message: 'Catalog blueprint promotion safety token is missing.',
          severity: QaSeverity.error,
          expected: token,
          actual: file.path,
          suggestedFix:
              'Keep generated catalog expansion review-only, local-only, and blocked from production promotion by default.',
          metadata: const {'triageCategory': QaFailureTriage.governance},
        ),
      );
    }
  }
}
