import 'dart:io';

import '../qa_harness/qa_harness.dart';

class WorkSupplyParserPackLifecycleSuite extends QaSuite {
  const WorkSupplyParserPackLifecycleSuite()
    : super('inventory.pack_lifecycle');

  static const _scannedFiles = [
    'lib/screens/work_supplies/data/work_supply_trade_pack_manifest.dart',
    'lib/screens/work_supplies/data/work_supply_trade_pack_import_validator.dart',
    'lib/screens/work_supplies/data/work_supply_catalog_pack_payload.dart',
    'lib/screens/work_supplies/data/work_supply_item_intelligence.dart',
    'docs/inventory_parser_qa_harness_plan.md',
  ];

  static const _contracts = [
    _LifecycleContract(
      name: 'manifest_schema_version',
      tokens: ['schemaVersion'],
      category: QaFailureTriage.schema,
      required: true,
    ),
    _LifecycleContract(
      name: 'pack_version',
      tokens: ['packVersion', 'workSupplyCatalogPackVersion'],
      category: QaFailureTriage.governance,
      required: true,
    ),
    _LifecycleContract(
      name: 'chunk_checksum',
      tokens: ['sha256', 'checksumMismatch'],
      category: QaFailureTriage.security,
      required: true,
    ),
    _LifecycleContract(
      name: 'safe_chunk_path',
      tokens: ['invalidChunkPath', 'storagePath.contains(\'..\')'],
      category: QaFailureTriage.security,
      required: true,
    ),
    _LifecycleContract(
      name: 'parser_metadata_validation',
      tokens: ['missingParserMetadata', 'canonicalKey', 'searchTerms'],
      category: QaFailureTriage.parserEngine,
      required: true,
    ),
    _LifecycleContract(
      name: 'generated_data_flags',
      tokens: ['autoGenerated', 'verifiedManually', 'needsReview'],
      category: QaFailureTriage.governance,
      required: true,
    ),
    _LifecycleContract(
      name: 'source_confidence',
      tokens: ['sourceConfidence'],
      category: QaFailureTriage.governance,
      required: true,
    ),
    _LifecycleContract(
      name: 'pack_dependency_rules',
      tokens: ['dependencies', 'requiredPacks', 'requiresPack'],
      category: QaFailureTriage.governance,
    ),
    _LifecycleContract(
      name: 'migration_contract',
      tokens: ['migration', 'migrate', 'fromSchemaVersion'],
      category: QaFailureTriage.governance,
    ),
    _LifecycleContract(
      name: 'rollback_contract',
      tokens: ['rollback', 'previousPackVersion', 'supersedesPackVersion'],
      category: QaFailureTriage.governance,
    ),
    _LifecycleContract(
      name: 'manual_promotion_gate',
      tokens: ['promote', 'manualOverride', 'reviewedCorrection'],
      category: QaFailureTriage.reviewSafety,
    ),
    _LifecycleContract(
      name: 'local_correction_isolation',
      tokens: ['localCorrection', 'userCorrection', 'learnedCorrection'],
      category: QaFailureTriage.reviewSafety,
    ),
  ];

  @override
  Future<QaSuiteResult> run(QaContext context) async {
    final timer = QaStopwatch.start();
    final failures = <QaFailure>[];
    final sourceByPath = <String, String>{};
    for (final path in _scannedFiles) {
      final file = File(path);
      if (!file.existsSync()) {
        failures.add(
          QaFailure(
            suite: name,
            id: 'missing_lifecycle_scan_file:$path',
            message: 'Pack lifecycle scan file is missing.',
            expected: path,
            actual: 'not found',
            suggestedFix:
                'Update this suite if pack lifecycle files are moved or renamed.',
            metadata: const {'triageCategory': QaFailureTriage.schema},
          ),
        );
        continue;
      }
      sourceByPath[path] = file.readAsStringSync();
    }
    final source = sourceByPath.values.join('\n');
    final present = <String>[];
    final missingRequired = <String>[];
    final missingRecommended = <String>[];

    for (final contract in _contracts) {
      if (contract.isPresentIn(source)) {
        present.add(contract.name);
        continue;
      }
      if (contract.required) {
        missingRequired.add(contract.name);
      } else {
        missingRecommended.add(contract.name);
      }
      failures.add(
        QaFailure(
          suite: name,
          id: 'missing_pack_lifecycle_contract:${contract.name}',
          message: contract.required
              ? 'Required pack lifecycle contract is missing.'
              : 'Recommended pack lifecycle contract is not represented yet.',
          severity: contract.required ? QaSeverity.error : QaSeverity.warning,
          expected: contract.name,
          actual: 'not found',
          suggestedFix:
              'Represent this pack lifecycle rule before hosted catalog packs are release-gated.',
          metadata: {'triageCategory': contract.category},
        ),
      );
    }

    return timer.finish(
      suite: name,
      checked: _contracts.length + _scannedFiles.length,
      failures: failures,
      maxFailures: context.maxFailuresPerSuite,
      metrics: {
        'presentContracts': present,
        'missingRequiredContracts': missingRequired,
        'missingRecommendedContracts': missingRecommended,
        'filesScanned': sourceByPath.keys.toList()..sort(),
      },
    );
  }
}

class _LifecycleContract {
  const _LifecycleContract({
    required this.name,
    required this.tokens,
    required this.category,
    this.required = false,
  });

  final String name;
  final List<String> tokens;
  final String category;
  final bool required;

  bool isPresentIn(String source) {
    return tokens.any(source.contains);
  }
}
