import AVFoundation
import CoreMedia
import CoreVideo
import UIKit

extension ReceiptCameraViewController {
  func nativeCaptureDiagnostics(
    photoByteSize: Int,
    capturedAt: String
  ) -> [String: Any] {
    let device = cameraDevice
    return [
      "engine": "avFoundation",
      "captureSurface": "maintainiac_native_ios",
      "nativeCameraIdentity": "maintainiac_in_app_receipt_camera",
      "nativeCaptureUiContract": "maintainiac_custom_receipt_capture_ui_v1",
      "stockCameraUiUsed": false,
      "nativeTouchControlPolicy": "continuous_focus_readability_and_pinch_zoom_v1",
      "readabilityGuidanceCoordinateSpace": "avfoundation_preview_layer_device_point",
      "tapToFocusPolicy": tapToFocusPolicy,
      "focusStrategyPolicy": focusStrategyPolicy,
      "continuousFocusEnabled": continuousFocusEnabled,
      "readabilityGuidancePolicy": readabilityGuidancePolicy,
      "receiptCameraQualityBaseline": receiptCameraQualityBaseline,
      "pinchZoomPolicy": zoomGesturePolicy,
      "zoomGesturePolicy": zoomGesturePolicy,
      "previewExposurePolicy": previewExposurePolicy,
      "previewBrightnessGuardPolicy": previewBrightnessGuardPolicy,
      "shutterSpeedPolicy": shutterSpeedPolicy,
      "autoCapturePolicy": autoCapturePolicy,
      "settingsButtonPlacement": "top_bar_right",
      "backButtonPlacement": "top_bar_left",
      "torchButtonPlacement": "top_bar_right",
      "shutterButtonPlacement": "bottom_center",
      "reviewNextButtonPlacement": "bottom_only_after_capture",
      "nativeCaptureReviewTransitionPolicy": "captured_photos_must_open_review_then_receipt_details",
      "nativeCaptureReviewTransitionTarget": "receipt_photo_review_next_to_receipt_details",
      "nativeCaptureReviewDiscardPolicy": "never_discard_captured_photo_on_back",
      "captureMode": "manual",
      "captureQualityMode": stillCaptureModeLabel,
      "stillCaptureMode": stillCaptureModeLabel,
      "nativePreviewScaleMode": nativePreviewScaleMode,
      "nativeControlDensity": nativeControlDensity,
      "visibleControlSet": visibleControlSet(),
      "nativeControlReadinessSummary": nativeControlReadinessSummary(),
      "backControlActual": backControlActualStatus(),
      "settingsControlActual": settingsControlActualStatus(),
      "manualShutterControlActual": manualShutterControlActualStatus(),
      "tapFocusControlActual": tapFocusControlActualStatus(),
      "pinchZoomControlActual": pinchZoomControlActualStatus(),
      "exposureSliderControlActual": exposureSliderControlActualStatus(),
      "exposureResetControlActual": exposureResetControlActualStatus(),
      "torchControlActual": torchControlActualStatus(),
      "focusLockControlActual": focusLockControlActualStatus(),
      "exposureLockControlActual": exposureLockControlActualStatus(),
      "whiteBalanceLockControlActual": whiteBalanceLockControlActualStatus(),
      "previewDominanceTarget": "receipt_preview_75_80_percent",
      "capturedAt": capturedAt,
      "deviceTier": deviceTier,
      "settingsContractVersion": settingsContractVersion,
      "devicePolicyLabel": devicePolicyLabel,
      "cameraResolutionTier": cameraResolutionTier,
      "cameraWorkloadTier": cameraWorkloadTier,
      "photoByteSize": photoByteSize,
      "photoByteSizeBucket": byteSizeBucket(photoByteSize),
      "latestCapturedPhotoWidth": latestCapturedPhotoWidth,
      "latestCapturedPhotoHeight": latestCapturedPhotoHeight,
      "latestCapturedAverageLuma": latestCapturedAverageLuma,
      "latestCapturedEdgeScore": latestCapturedEdgeScore,
      "latestCapturedTopLuma": latestCapturedTopLuma,
      "latestCapturedMiddleLuma": latestCapturedMiddleLuma,
      "latestCapturedBottomLuma": latestCapturedBottomLuma,
      "latestCapturedBottomEdgeScore": latestCapturedBottomEdgeScore,
      "receiptBottomEdgeDetected": receiptBottomEdgeDetected(),
      "receiptBottomEdgeStatus": receiptBottomEdgeStatus(),
      "receiptTotalsTextEvidenceStatus": "not_evaluated_native_capture",
      "latestCapturedBottomTopLumaDelta": latestCapturedBottomTopLumaDelta,
      "latestCapturedBottomTopLumaDeltaBucket": latestCapturedBottomTopLumaDeltaBucket,
      "latestCapturedVerticalQualitySignal": latestCapturedVerticalQualitySignal,
      "latestCapturedMegapixelBucket": latestCapturedMegapixelBucket,
      "latestCapturedByteBucket": latestCapturedByteBucket,
      "latestCapturedBrightnessBucket": latestCapturedBrightnessBucket,
      "latestCapturedSharpnessBucket": latestCapturedSharpnessBucket,
      "latestCapturedQualitySignal": latestCapturedQualitySignal,
      "latestCaptureLiveBrightnessAtShutter": latestCaptureLiveBrightnessAtShutter,
      "latestCapturedLiveToSavedLumaDelta": latestCapturedLiveToSavedLumaDelta,
      "latestCapturedLiveToSavedLumaDeltaBucket": latestCapturedLiveToSavedLumaDeltaBucket,
      "latestCapturedPreviewParitySignal": latestCapturedPreviewParitySignal,
      "latestCapturedExposureMismatch": latestCapturedExposureMismatch,
      "capturedLightingEvidence": capturedLightingEvidence,
      "latestCaptureToSavedMs": latestCaptureToSavedMs,
      "latestCaptureToReviewReadyMs": latestCaptureToReviewReadyMs,
      "latestNativeCaptureLatencyBucket": latestCaptureLatencyBucket,
      "nativeCaptureResponsivenessPolicy": "manual_shutter_to_review_should_feel_immediate",
      "photoCount": capturedPhotoPaths.count,
      "receiptSectionCount": capturedPhotoPaths.count,
      "nextReceiptSectionNumber": nextReceiptSectionNumber(),
      "maxSectionCount": maxSectionCount,
      "receiptSectionOrderPolicy": "top_to_bottom_numbered_sections",
      "longReceiptSectionGuidance": "top_to_bottom_with_readable_overlap",
      "previousSectionGhostGuidePolicy": previousSectionGhostGuidePolicy(),
      "previousSectionGhostGuideUsesNextContext": previousSectionGuideUsesNextContext(),
      "previousSectionGhostGuideMatchTarget": previousSectionGhostGuideMatchTarget(),
      "previousSectionGhostGuideVisible": previousSectionGhostGuideVisible(),
      "previousSectionGhostSourceStartFraction": Double(previousSectionGhostSourceStartFraction),
      "previousSectionGhostSourceHeightFraction": Double(previousSectionGhostSourceHeightFraction),
      "previousSectionGhostOverlayTopFraction": Double(previousSectionGhostOverlayTopFraction),
      "previousSectionGhostOverlayHeightFraction": Double(previousSectionGhostOverlayHeightFraction),
      "previousSectionGhostOpacity": Double(previousSectionGhostOpacity),
      "previousSectionGhostSlicePercent": Int((previousSectionGhostSourceHeightFraction * 100).rounded()),
      "hasNextSectionGuide": nextSectionGuidePhotoPath != nil,
      "nextSectionGhostGuidePolicy": "next_section_top_context_ghost_at_bottom_repeat_3_to_5_lines",
      "nextSectionGhostGuidePlacement": "bottom_ghost_slice",
      "nextSectionGhostGuideVisible": !nextSectionGuideImageView.isHidden,
      "liveAnalysisEnabled": liveAnalysisEnabled,
      "autoExposureAssistEnabled": autoExposureAssistEnabled,
      "edgeDetectionEnabled": edgeDetectionEnabled,
      "edgeOverlayEnabled": edgeOverlayEnabled,
      "motionBlurWarningEnabled": motionBlurWarningEnabled,
      "glareWarningEnabled": glareWarningEnabled,
      "dirtyLensWarningEnabled": dirtyLensWarningEnabled,
      "lowLightWarningEnabled": lowLightWarningEnabled,
      "shadowWarningEnabled": shadowWarningEnabled,
      "textTooSmallWarningEnabled": textTooSmallWarningEnabled,
      "perspectiveCorrectionEnabled": perspectiveCorrectionEnabled,
      "manualCropAfterCapture": manualCropAfterCapture,
      "saveOriginalTemporarily": saveOriginalTemporarily,
      "queueAcceptedCaptureLocally": queueAcceptedCaptureLocally,
      "ocrUsesOriginalFirst": ocrUsesOriginalFirst,
      "autoCropSuggestionEnabled": autoCropSuggestionEnabled,
      "grayscalePreviewEnabled": grayscalePreviewEnabled,
      "contrastBoostEnabled": contrastBoostEnabled,
      "sharpeningEnabled": sharpeningEnabled,
      "shadowReductionEnabled": shadowReductionEnabled,
      "adaptiveThresholdEnabled": adaptiveThresholdEnabled,
      "orientationCorrectionEnabled": orientationCorrectionEnabled,
      "receiptGuidanceWarningsEnabled": receiptGuidanceWarningsEnabled(),
      "experimentalReceiptQualityWarningsEnabled": hasExperimentalReceiptQualityWarningsEnabled(),
      "experimentalReceiptQualityRequiredFrames": experimentalReceiptQualityRequiredFrames,
      "experimentalReceiptQualityCandidateSignal": experimentalReceiptQualityCandidateSignal,
      "experimentalReceiptQualityCandidateCount": experimentalReceiptQualityCandidateCount,
      "autoExposureAdjustmentCount": autoExposureAdjustmentCount,
      "preCaptureExposureAdjustmentCount": preCaptureExposureAdjustmentCount,
      "preCaptureExposureAdjustmentConfirmedCount": preCaptureExposureAdjustmentConfirmedCount,
      "lastAutoExposureDecision": lastAutoExposureDecision,
      "lastPreCaptureExposureDecision": lastPreCaptureExposureDecision,
      "lastPreCaptureExposureSkipReason": lastPreCaptureExposureSkipReason,
      "preCaptureExposureAbortCount": preCaptureExposureAbortCount,
      "lastPreCaptureExposureAbortReason": lastPreCaptureExposureAbortReason,
      "preCaptureExposureOutcome": preCaptureExposureOutcome(),
      "preCaptureExposurePolicy": preCaptureExposurePolicy,
      "lastAutoExposureBrightnessBucket": lastAutoExposureBrightnessBucket,
      "lastAutoExposureCandidate": lastAutoExposureCandidate,
      "autoExposureCandidateFrameCount": autoExposureCandidateFrameCount,
      "lastAutoExposureBias": Double(lastAutoExposureBias),
      "lastPreCaptureExposureTargetBias": Double(lastPreCaptureExposureTargetBias),
      "tapFocusCount": tapFocusCount,
      "tapFocusSuppressedAfterZoomCount": tapFocusSuppressedAfterZoomCount,
      "zoomChangeCount": zoomChangeCount,
      "zoomGestureStartCount": zoomGestureStartCount,
      "zoomUnavailableCount": zoomUnavailableCount,
      "lastZoomStatus": lastZoomStatus,
      "lastZoomRatio": lastZoomRatio,
      "manualExposureChangeCount": manualExposureChangeCount,
      "settingsOpenCount": settingsOpenCount,
      "settingsResetCount": settingsResetCount,
      "lastFocusStatus": lastFocusStatus,
      "focusMode": focusMode,
      "exposureMode": exposureMode,
      "whiteBalanceMode": whiteBalanceMode,
      "whiteBalanceLockEnabled": false,
      "focusLockAttemptCount": focusLockAttemptCount,
      "focusLockSuccessCount": focusLockSuccessCount,
      "exposureLockSuccessCount": exposureLockSuccessCount,
      "whiteBalanceLockAttemptCount": whiteBalanceLockAttemptCount,
      "whiteBalanceLockSuccessCount": whiteBalanceLockSuccessCount,
      "whiteBalanceLockStatus": whiteBalanceLockStatus,
      "autoCaptureStableFrameCount": autoCaptureStableFrameCount,
      "autoCaptureTriggerCount": autoCaptureTriggerCount,
      "manualShutterTapCount": manualShutterTapCount,
      "manualCaptureStartedCount": manualCaptureStartedCount,
      "autoCaptureAttemptCount": autoCaptureAttemptCount,
      "autoCaptureStartedCount": autoCaptureStartedCount,
      "captureBlockedNoCameraCount": captureBlockedNoCameraCount,
      "captureBlockedBusyCount": captureBlockedBusyCount,
      "captureBlockedClosingCount": captureBlockedClosingCount,
      "captureBlockedSurfaceInactiveCount": captureBlockedSurfaceInactiveCount,
      "lastCaptureTrigger": lastCaptureTrigger,
      "lastCaptureBlockReason": lastCaptureBlockReason,
      "latestAutoCaptureStatus": latestAutoCaptureStatus,
      "closeAction": closeAction,
      "closeCapturedPhotoPolicy": "back_returns_captured_sections_before_cancel",
      "closeCapturedPhotoOutcome": closeCapturedPhotoOutcome(),
      "closeRetryCount": closeRetryCount,
      "closeRequestCount": closeRequestCount,
      "closeDuringCaptureCount": closeDuringCaptureCount,
      "closeNoPhotoCancelCount": closeNoPhotoCancelCount,
      "closeReturnedSectionsCount": closeReturnedSectionsCount,
      "lastBackDispatchPath": lastBackDispatchPath,
      "closingCamera": closingCamera,
      "pendingCloseAfterCapture": pendingCloseAfterCapture,
      "closeResultDelivered": closeResultDelivered,
      "exposureAssistStatus": exposureAssistStatus(),
      "userExposureOverride": userExposureOverride,
      "analysisGapMs": analysisGapMs,
      "readyHoldMs": readyHoldMs,
      "assistedShotCount": assistedShotCount,
      "bestShotCandidateCount": bestShotCandidateCount,
      "maxLiveAnalysisPixels": maxLiveAnalysisPixels,
      "maxCleanupPixels": maxCleanupPixels,
      "maxStitchOutputPixels": maxStitchOutputPixels,
      "maxStitchOutputHeight": maxStitchOutputHeight,
      "latestFrameBrightness": latestFrameBrightness,
      "latestShadowScore": latestShadowScore,
      "latestBrightnessBucket": brightnessBucket(latestFrameBrightness),
      "latestReadabilitySignal": latestReadabilitySignal,
      "latestFramingSignal": latestFramingSignal,
      "latestFramingConfidence": latestFramingConfidence,
      "latestEdgeCoverage": latestEdgeCoverage,
      "latestFramingWidthRatio": latestFramingWidthRatio,
      "latestFramingHeightRatio": latestFramingHeightRatio,
      "latestPerspectiveReadiness": latestPerspectiveReadiness,
      "latestMotionSignal": latestMotionSignal,
      "latestMotionScore": latestMotionScore,
      "assistedReceiptFill": assistedReceiptFill,
      "longReceiptMode": longReceiptMode,
      "captureReadinessCode": captureReadinessCode(),
      "captureReadinessLabel": captureReadinessLabel(),
      "manualCaptureAllowed": true,
      "autoCaptureEnabled": autoCaptureEnabled,
      "autoCaptureAllowed": autoCaptureAllowed,
      "stableFrameCount": autoCaptureStableFrameCount,
      "requiredStableFrames": autoCaptureStableFrameTarget,
      "autoCaptureMaxMotionScore": autoCaptureMaxMotionScore,
      "autoCaptureMinBrightness": autoCaptureMinBrightness,
      "autoCaptureMaxBrightness": autoCaptureMaxBrightness,
      "autoCaptureCooldownMs": autoCaptureCooldownMs,
      "autoCaptureCurrentlyAllowed": isAutoCaptureCurrentlyAllowed(),
      "autoCaptureSafetyPolicy": "optional_manual_shutter_always_available",
      "manualCapturePolicy": "guidance_advisory_manual_shutter_always_allowed",
      "guidanceBlockingPolicy": "quality_guidance_warns_never_blocks_manual_capture",
      "manualCaptureBlockPolicy": "only_busy_closing_no_camera_or_inactive_surface",
      "reviewDepth": reviewDepth,
      "dataSaverLevel": dataSaverLevel,
      "receiptPhotoBackupEnabled": receiptPhotoBackupEnabled,
      "askSavedProofSizeEachReceipt": askSavedProofSizeEachReceipt,
      "storageSafetyLevel": storageSafetyLevel,
      "storageConstrained": storageConstrained,
      "storageSafetyReason": storageSafetyReason,
      "workloadProtectionPolicy": workloadProtectionPolicy,
      "maxLocalPhotoBytes": maxLocalPhotoBytes,
      "nativeCaptureMemoryPolicy": nativeCaptureMemoryPolicy,
      "hasPreviousSectionGuide": previousSectionGuidePhotoPath != nil,
      "previousSectionReasonCode": previousSectionReasonCode,
      "previousSectionMissingBottomAndTotals": previousSectionReasonCode == "missing_bottom_edge_and_totals",
      "previousSectionGuidanceAvailable": !previousSectionGuidance.isEmpty,
      "previousSectionGhostGuideTitle": previousSectionGhostGuideTitle(),
      "previousSectionGhostGuideInstruction": previousSectionGhostGuideInstruction(),
      "hasNextSectionGuide": nextSectionGuidePhotoPath != nil,
      "nextSectionGhostGuidePolicy": "next_section_top_context_ghost_at_bottom_repeat_3_to_5_lines",
      "nextSectionGhostGuidePlacement": "bottom_ghost_slice",
      "torchOn": torchOn,
      "hasTorch": device?.hasTorch ?? false,
      "exposureTargetBias": Double(device?.exposureTargetBias ?? 0),
      "minExposureTargetBias": Double(device?.minExposureTargetBias ?? 0),
      "maxExposureTargetBias": Double(device?.maxExposureTargetBias ?? 0),
      "zoomRatio": Double(device?.videoZoomFactor ?? 1),
      "minZoomRatio": 1,
      "maxZoomRatio": Double(device?.maxAvailableVideoZoomFactor ?? 1),
      "sessionMinZoom": sessionMinZoom,
      "sessionMaxZoom": sessionMaxZoom,
      "sessionMinExposureOffset": sessionMinExposureOffset,
      "sessionMaxExposureOffset": sessionMaxExposureOffset,
      "tapFocusEnabled": false,
      "pinchZoomEnabled": pinchZoomEnabled,
      "exposureSliderEnabled": exposureSliderEnabled,
      "exposureResetEnabled": exposureResetEnabled,
      "nativeControlContractVersion": "receipt_native_controls_v1",
      "nativeControlContractTags": nativeControlContractTags,
      "controlDiagnosticsPrivacyScope": "summary_only_no_receipt_content",
      "tapFocusControlExpected": false,
      "pinchZoomControlExpected": pinchZoomEnabled,
      "exposureSliderControlExpected": exposureSliderEnabled,
      "exposureResetControlExpected": exposureResetEnabled,
      "settingsControlExpected": true,
      "backControlExpected": true,
      "torchControlExpected": device?.hasTorch ?? false,
      "focusLockControlExpected": false,
      "exposureLockControlExpected": false,
      "whiteBalanceLockControlExpected": false,
      "manualShutterAlwaysAvailable": arguments["manualShutterAlwaysAvailable"] as? Bool ?? true
    ]
  }
}

extension ReceiptCameraViewController {
  func captureReadinessCode() -> String {
    if !autoCaptureEnabled {
      return "manual_ready_auto_capture_off"
    }
    switch latestAutoCaptureStatus {
    case "capturing":
      return "auto_capture_ready"
    case "waiting_for_edges":
      return "manual_only_check_framing"
    case "waiting_for_light":
      return "manual_only_quality_retake_recommended"
    case "waiting_for_quality_review":
      return "manual_only_quality_review"
    case "closing":
      return "manual_ready_auto_capture_off"
    default:
      return "auto_capture_waiting_for_stability"
    }
  }

  func captureReadinessLabel() -> String {
    switch captureReadinessCode() {
    case "auto_capture_ready":
      return "Receipt looks steady. Taking photo."
    case "manual_only_check_framing":
      return "Check that every receipt line is visible before auto capture."
    case "manual_only_quality_retake_recommended":
      return "Improve lighting before automatic capture."
    case "manual_only_quality_review":
      return "Check sharpness, light, and receipt text before automatic capture."
    case "auto_capture_waiting_for_stability":
      return "Hold steady for automatic capture."
    default:
      return "Manual capture is ready. Auto capture is off."
    }
  }
}
