import 'work_supply_item_identity_resolver.dart';
import 'work_supply_models.dart';

const workSupplyCatalogPackSchemaVersion = 3;

class WorkSupplyCatalogPackItemPayload {
  const WorkSupplyCatalogPackItemPayload({
    required this.canonicalKey,
    required this.id,
    required this.name,
    required this.trade,
    required this.category,
    required this.system,
    required this.itemType,
    required this.variant,
    required this.unit,
    required this.marketScopes,
    required this.packTier,
    required this.parserPriority,
    required this.intelligence,
    required this.searchTerms,
    required this.aliases,
    required this.merchantAliases,
    required this.barcodeAliases,
    required this.merchantSkuAliases,
    required this.packageHints,
  });

  final String canonicalKey;
  final String id;
  final String name;
  final String trade;
  final String category;
  final String system;
  final String itemType;
  final String variant;
  final String unit;
  final List<String> marketScopes;
  final String packTier;
  final String parserPriority;
  final WorkSupplyCatalogPackIntelligencePayload intelligence;
  final List<String> searchTerms;
  final List<WorkSupplyCatalogPackAliasPayload> aliases;
  final List<WorkSupplyCatalogPackAliasPayload> merchantAliases;
  final List<WorkSupplyCatalogPackAliasPayload> barcodeAliases;
  final List<WorkSupplyCatalogPackAliasPayload> merchantSkuAliases;
  final List<String> packageHints;

  Map<String, Object?> toMap() {
    return {
      'canonicalKey': canonicalKey,
      'id': id,
      'name': name,
      'trade': trade,
      'category': category,
      'system': system,
      'itemType': itemType,
      'variant': variant,
      'unit': unit,
      'marketScopes': marketScopes,
      'packTier': packTier,
      'parserPriority': parserPriority,
      'intelligence': intelligence.toMap(),
      'searchTerms': searchTerms,
      'aliases': [for (final alias in aliases) alias.toMap()],
      'merchantAliases': [for (final alias in merchantAliases) alias.toMap()],
      'barcodeAliases': [for (final alias in barcodeAliases) alias.toMap()],
      'merchantSkuAliases': [
        for (final alias in merchantSkuAliases) alias.toMap(),
      ],
      'packageHints': packageHints,
    };
  }
}

class WorkSupplyCatalogPackIntelligencePayload {
  const WorkSupplyCatalogPackIntelligencePayload({
    required this.material,
    required this.size,
    required this.connectionType,
    required this.shapeOrStyle,
    required this.packQuantity,
    required this.isConsumable,
    required this.isDurable,
    required this.isBrandSpecific,
    required this.receiptPatterns,
    required this.ocrMistakePatterns,
    required this.vendorMappings,
    required this.attributeTokens,
    required this.negativeMatchTokens,
    required this.highImportanceTokens,
    required this.mediumImportanceTokens,
    required this.lowImportanceTokens,
    required this.ignoreTokens,
    required this.classification,
    required this.catalogVersion,
    required this.parserVersion,
    required this.sourceConfidence,
    required this.verifiedManually,
    required this.autoGenerated,
    required this.needsReview,
  });

  final String material;
  final String size;
  final String connectionType;
  final String shapeOrStyle;
  final String packQuantity;
  final bool isConsumable;
  final bool isDurable;
  final bool isBrandSpecific;
  final List<String> receiptPatterns;
  final List<String> ocrMistakePatterns;
  final List<WorkSupplyCatalogPackVendorMappingPayload> vendorMappings;
  final List<String> attributeTokens;
  final List<String> negativeMatchTokens;
  final List<String> highImportanceTokens;
  final List<String> mediumImportanceTokens;
  final List<String> lowImportanceTokens;
  final List<String> ignoreTokens;
  final WorkSupplyCatalogPackClassificationPayload classification;
  final String catalogVersion;
  final String parserVersion;
  final String sourceConfidence;
  final bool verifiedManually;
  final bool autoGenerated;
  final bool needsReview;

  Map<String, Object?> toMap() {
    return {
      'material': material,
      'size': size,
      'connectionType': connectionType,
      'shapeOrStyle': shapeOrStyle,
      'packQuantity': packQuantity,
      'isConsumable': isConsumable,
      'isDurable': isDurable,
      'isBrandSpecific': isBrandSpecific,
      'receiptPatterns': receiptPatterns,
      'ocrMistakePatterns': ocrMistakePatterns,
      'vendorMappings': [for (final mapping in vendorMappings) mapping.toMap()],
      'attributeTokens': attributeTokens,
      'negativeMatchTokens': negativeMatchTokens,
      'highImportanceTokens': highImportanceTokens,
      'mediumImportanceTokens': mediumImportanceTokens,
      'lowImportanceTokens': lowImportanceTokens,
      'ignoreTokens': ignoreTokens,
      'classification': classification.toMap(),
      'catalogVersion': catalogVersion,
      'parserVersion': parserVersion,
      'sourceConfidence': sourceConfidence,
      'verifiedManually': verifiedManually,
      'autoGenerated': autoGenerated,
      'needsReview': needsReview,
    };
  }
}

class WorkSupplyCatalogPackVendorMappingPayload {
  const WorkSupplyCatalogPackVendorMappingPayload({
    required this.vendor,
    required this.code,
    required this.label,
  });

  final String vendor;
  final String code;
  final String label;

  Map<String, Object?> toMap() {
    return {'vendor': vendor, 'code': code, 'label': label};
  }
}

class WorkSupplyCatalogPackClassificationPayload {
  const WorkSupplyCatalogPackClassificationPayload({
    required this.inventoryCategory,
    required this.expenseCategory,
    required this.jobMaterialCategory,
    required this.taxReportingCategory,
    required this.maintenanceRelevance,
    required this.billableMaterial,
    required this.defaultUnitCostBehavior,
    required this.defaultMarkupBehavior,
  });

  final String inventoryCategory;
  final String expenseCategory;
  final String jobMaterialCategory;
  final String taxReportingCategory;
  final String maintenanceRelevance;
  final bool billableMaterial;
  final String defaultUnitCostBehavior;
  final String defaultMarkupBehavior;

  Map<String, Object?> toMap() {
    return {
      'inventoryCategory': inventoryCategory,
      'expenseCategory': expenseCategory,
      'jobMaterialCategory': jobMaterialCategory,
      'taxReportingCategory': taxReportingCategory,
      'maintenanceRelevance': maintenanceRelevance,
      'billableMaterial': billableMaterial,
      'defaultUnitCostBehavior': defaultUnitCostBehavior,
      'defaultMarkupBehavior': defaultMarkupBehavior,
    };
  }
}

class WorkSupplyCatalogPackAliasPayload {
  const WorkSupplyCatalogPackAliasPayload({
    required this.value,
    required this.normalized,
    required this.source,
  });

  final String value;
  final String normalized;
  final String source;

  Map<String, Object?> toMap() {
    return {'value': value, 'normalized': normalized, 'source': source};
  }
}

WorkSupplyCatalogPackItemPayload buildWorkSupplyCatalogPackItemPayload(
  WorkSupplyItem item,
) {
  final canonicalTerms = _canonicalTermsFor(item);
  final aliasPayloads = [
    for (final alias in _aliasValuesFor(item))
      WorkSupplyCatalogPackAliasPayload(
        value: alias,
        normalized: normalizeWorkSupplyCatalogPackText(alias),
        source: 'catalog',
      ),
  ];
  final merchantSkuAliases = [
    for (final mapping in item.intelligence.vendorMappings)
      if (mapping.code.trim().isNotEmpty)
        WorkSupplyCatalogPackAliasPayload(
          value: mapping.code,
          normalized: normalizeWorkSupplyCatalogPackText(mapping.code),
          source: 'vendor:${mapping.vendor}',
        ),
  ];
  return WorkSupplyCatalogPackItemPayload(
    canonicalKey: canonicalWorkSupplyItemKey(item),
    id: item.id,
    name: item.name,
    trade: item.trade,
    category: item.category,
    system: item.system,
    itemType: item.itemType,
    variant: item.variant,
    unit: item.unit,
    marketScopes: [for (final scope in item.marketScopes) scope.name],
    packTier: item.packTier.name,
    parserPriority: item.parserPriority.name,
    intelligence: _intelligencePayloadFor(item.intelligence),
    searchTerms: canonicalTerms,
    aliases: aliasPayloads,
    merchantAliases: const [],
    barcodeAliases: const [],
    merchantSkuAliases: merchantSkuAliases,
    packageHints: _packageHintsFor(item),
  );
}

WorkSupplyCatalogPackIntelligencePayload _intelligencePayloadFor(
  WorkSupplyItemIntelligence intelligence,
) {
  final classification = intelligence.classification;
  return WorkSupplyCatalogPackIntelligencePayload(
    material: intelligence.material,
    size: intelligence.size,
    connectionType: intelligence.connectionType,
    shapeOrStyle: intelligence.shapeOrStyle,
    packQuantity: intelligence.packQuantity,
    isConsumable: intelligence.isConsumable,
    isDurable: intelligence.isDurable,
    isBrandSpecific: intelligence.isBrandSpecific,
    receiptPatterns: intelligence.receiptPatterns,
    ocrMistakePatterns: intelligence.ocrMistakePatterns,
    vendorMappings: [
      for (final mapping in intelligence.vendorMappings)
        WorkSupplyCatalogPackVendorMappingPayload(
          vendor: mapping.vendor,
          code: mapping.code,
          label: mapping.label,
        ),
    ],
    attributeTokens: intelligence.attributeTokens,
    negativeMatchTokens: intelligence.negativeMatchTokens,
    highImportanceTokens: intelligence.highImportanceTokens,
    mediumImportanceTokens: intelligence.mediumImportanceTokens,
    lowImportanceTokens: intelligence.lowImportanceTokens,
    ignoreTokens: intelligence.ignoreTokens,
    classification: WorkSupplyCatalogPackClassificationPayload(
      inventoryCategory: classification.inventoryCategory,
      expenseCategory: classification.expenseCategory,
      jobMaterialCategory: classification.jobMaterialCategory,
      taxReportingCategory: classification.taxReportingCategory,
      maintenanceRelevance: classification.maintenanceRelevance,
      billableMaterial: classification.billableMaterial,
      defaultUnitCostBehavior: classification.defaultUnitCostBehavior,
      defaultMarkupBehavior: classification.defaultMarkupBehavior,
    ),
    catalogVersion: intelligence.catalogVersion,
    parserVersion: intelligence.parserVersion,
    sourceConfidence: intelligence.sourceConfidence,
    verifiedManually: intelligence.verifiedManually,
    autoGenerated: intelligence.autoGenerated,
    needsReview: intelligence.needsReview,
  );
}

String normalizeWorkSupplyCatalogPackText(String value) {
  return value
      .toLowerCase()
      .replaceAll('&', ' and ')
      .replaceAll(RegExp(r'(\d+)ft\b'), r'$1 ft')
      .replaceAll(RegExp(r'(\d+)in\b'), r'$1 in')
      .replaceAll(RegExp(r'(\d+)lb\b'), r'$1 lb')
      .replaceAll(RegExp(r'(\d+)oz\b'), r'$1 oz')
      .replaceAll(RegExp(r'(\d+)gal\b'), r'$1 gal')
      .replaceAll(RegExp(r'[^a-z0-9/.-]+'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
}

List<String> _aliasValuesFor(WorkSupplyItem item) {
  return [
    item.name,
    item.variant,
    item.itemType,
    item.system,
    ...item.aliases,
  ].where((value) => value.trim().isNotEmpty).toSet().toList(growable: false);
}

List<String> _canonicalTermsFor(WorkSupplyItem item) {
  final sourceText = [
    item.name,
    item.trade,
    item.category,
    item.system,
    item.itemType,
    item.variant,
    item.unit,
    ...item.marketScopes.map((scope) => scope.name),
    item.packTier.name,
    item.parserPriority.name,
    ...item.aliases,
    ...item.intelligence.searchableTokens,
  ].join(' ');
  final terms = normalizeWorkSupplyCatalogPackText(sourceText)
      .split(RegExp(r'\s+'))
      .where((term) => term.length >= 2 && !_ignoredPackTerm(term))
      .toSet()
      .toList();
  terms.sort();
  return terms;
}

bool _ignoredPackTerm(String term) {
  return switch (term) {
    'a' || 'an' || 'and' || 'the' || 'for' || 'with' || 'x' => true,
    _ => false,
  };
}

List<String> _packageHintsFor(WorkSupplyItem item) {
  final text = normalizeWorkSupplyCatalogPackText(
    '${item.name} ${item.variant} ${item.aliases.join(' ')}',
  );
  final hints = <String>{};
  for (final match in RegExp(
    r'\b(\d+)\s*(pack|pk|ct|count|piece|pieces|roll|rolls|bag|bags|box)\b',
  ).allMatches(text)) {
    hints.add(match.group(0)!);
  }
  if (item.unit.trim().isNotEmpty) hints.add('unit:${item.unit}');
  return hints.toList(growable: false)..sort();
}
