part of 'work_supply_catalog.dart';

bool _hasMeaningfulIntelligence(WorkSupplyItemIntelligence intelligence) {
  return intelligence.searchableTokens.any(
        (token) => token.trim().isNotEmpty,
      ) ||
      intelligence.autoGenerated ||
      intelligence.verifiedManually;
}

bool _hasAny(String text, List<String> signals) {
  return signals.any(text.contains);
}

String _firstMatched(String text, Map<String, String> signals) {
  for (final entry in signals.entries) {
    if (text.contains(entry.key)) return entry.value;
  }
  return '';
}

String _extractSize(String text) {
  final namedSize = RegExp(
    r'\b(?:small|medium|large|\d+\s*gang|new work|old work|remodel|round)\b',
  ).firstMatch(text);
  if (namedSize != null) return namedSize.group(0)!.trim();
  final hvacSize = RegExp(
    r'(?:^|\s)(?:no\s*\d+|[a-z]{1,2}\d{2,3}|\d+%|(?:\d+h/\d+c)|\d+\s*x\s*\d+(?:\s*x\s*\d+)?|\d+\s*(?:qt|quart|gal|gallon|oz|lb|pound))(?:\s|$)',
  ).firstMatch(text);
  if (hvacSize != null) return hvacSize.group(0)!.trim();
  final match = RegExp(
    r'\#\d+\b|\b\d+(?:-\d+/\d+|/\d+)?(?:\.\d+)?\s*(?:in|inch|od|awg|ft|feet|w|watt|watts|v|volt|volts|k|kelvin|mfd|uf|amp|amps|a|hp|ton|tons|cfm|btu|btu\/h)\b|\b\d+/\d+\b',
  ).firstMatch(text);
  return match?.group(0)?.trim() ?? '';
}

String _extractPackQuantity(String text) {
  final match = RegExp(r'\b(?:single|pair|\d+\s*pack)\b').firstMatch(text);
  return match?.group(0)?.trim() ?? '';
}

List<String> _receiptPatternsFor(
  WorkSupplyItem item,
  String material,
  String size,
  String shape,
) {
  final seeds = [
    item.name,
    '${item.variant} ${item.name}',
    if (size.isNotEmpty || material.isNotEmpty || shape.isNotEmpty)
      '$size $material $shape',
    ...item.aliases.take(6),
  ];
  final vendorStyleSeeds = [
    for (final seed in seeds.take(5)) ..._vendorStyleReceiptPatterns(seed),
  ];
  return _cleanList([
        for (final seed in seeds) seed,
        for (final seed in seeds) seed.toUpperCase().replaceAll(' IN ', 'IN '),
        ...vendorStyleSeeds,
        ..._plumbingCoreReceiptPatternsFor(item, material, size, shape),
        ..._electricalCoreReceiptPatternsFor(item, material, size, shape),
        ..._spanishSignalsFor(item, material, size, shape),
      ])
      .take(item.trade == 'Plumbing' || item.trade == 'Electrical' ? 32 : 16)
      .toList(growable: false);
}

List<String> _vendorStyleReceiptPatterns(String value) {
  final compact = value
      .toUpperCase()
      .replaceAll(' SCHEDULE ', ' SCH ')
      .replaceAll(' WATER HEATER ', ' WTR HTR ')
      .replaceAll(' DISHWASHER ', ' DW ')
      .replaceAll(' FEMALE ', ' F ')
      .replaceAll(' MALE ', ' M ')
      .replaceAll(' ADAPTER', ' ADPT')
      .replaceAll(' COUPLING', ' CPLG')
      .replaceAll(' CONNECTOR', ' CONN')
      .replaceAll(' ELBOW', ' ELB')
      .replaceAll(' ELBOWS', ' ELBS')
      .replaceAll(' PIPE JOINT COMPOUND', ' PIPE DOPE')
      .replaceAll(' TOILET ', ' TLT ')
      .replaceAll(RegExp(r'\bIN\b'), 'IN')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
  return _cleanList([
    compact,
    if (compact.contains(' ')) 'HD $compact',
    if (compact.contains(' ')) 'SUPPLY $compact',
  ]);
}

List<String> _ocrLikeMistakePatternsFor(String text) {
  return _cleanList([
    if (text.contains('pex')) 'PEX->PFX',
    if (text.contains('pvc')) 'PVC->PYC',
    if (text.contains('cpvc')) 'CPVC->CPYG',
    if (text.contains('1/2')) '1/2->I/2',
    if (text.contains('elbow') || text.contains('elb')) 'ELB->E1B',
  ]);
}

List<String> _attributeTokensFor(
  WorkSupplyItem item,
  String material,
  String size,
  String connectionType,
) {
  final shape = item.trade == 'Plumbing'
      ? _resolvePlumbingShape(item, item.searchableText)
      : item.trade == 'Electrical'
      ? _resolveElectricalShape(item, item.searchableText)
      : _firstMatched(item.searchableText, _shapeSignals);
  return _cleanList([
    item.trade,
    item.category,
    item.system,
    item.itemType,
    item.variant,
    material,
    size,
    connectionType,
    ...item.aliases,
    ..._plumbingCoreAttributeTokensFor(item, material, size, shape),
    ..._electricalCoreAttributeTokensFor(item, material, size, shape),
    ..._hvacCoreAttributeTokensFor(item, material, size, shape),
    ..._spanishSignalsFor(item, material, size, shape),
  ]);
}

List<String> _spanishSignalsFor(
  WorkSupplyItem item,
  String material,
  String size,
  String shape,
) {
  final text = item.searchableText;
  final family = _spanishFamilyToken(item, shape, text);
  final sizeToken = _spanishSizeToken(size, item.variant);
  final materialToken = _spanishMaterialToken(material, text);
  return _cleanList([
    'es-US',
    'spanish',
    'medida 1 pulg',
    '$sizeToken $materialToken $family',
    '$family $sizeToken',
    if (item.trade == 'Plumbing') 'tubo $sizeToken',
    if (item.trade == 'Electrical') 'cable $sizeToken',
    if (item.trade == 'HVAC') 'filtro $sizeToken',
  ]);
}

String _spanishFamilyToken(WorkSupplyItem item, String shape, String text) {
  final value = '$shape ${item.itemType} $text'.toLowerCase();
  if (value.contains('adapter')) return 'adaptador';
  if (value.contains('box')) return 'caja';
  if (value.contains('tape')) return 'cinta';
  if (value.contains('elbow') || value.contains('ell')) return 'codo';
  if (value.contains('connector')) return 'conector';
  if (value.contains('conduit')) return 'conducto';
  if (value.contains('filter')) return 'filtro';
  if (value.contains('pump')) return 'bomba';
  if (value.contains('tank')) return 'tanque';
  if (value.contains('cap') || value.contains('plug')) return 'tapon';
  if (value.contains('valve')) return 'valvula';
  if (value.contains('pipe') || value.contains('tube')) return 'tubo';
  if (item.trade == 'Electrical') return 'cable';
  if (item.trade == 'HVAC') return 'filtro';
  return 'tubo';
}

String _spanishMaterialToken(String material, String text) {
  final value = '$material $text'.toLowerCase();
  if (value.contains('copper')) return 'cobre';
  if (value.contains('brass')) return 'laton';
  if (value.contains('steel')) return 'acero';
  if (value.contains('iron')) return 'hierro';
  if (value.contains('aluminum')) return 'aluminio';
  if (value.contains('pvc')) return 'pvc';
  if (value.contains('pex')) return 'pex';
  return material;
}

String _spanishSizeToken(String size, String variant) {
  final source = size.isEmpty ? variant : size;
  if (source.trim().isEmpty) return '1 pulg';
  final normalized = source
      .replaceAll(RegExp(r'\binch(?:es)?\b', caseSensitive: false), 'pulg')
      .replaceAll(RegExp(r'\bin\b', caseSensitive: false), 'pulg')
      .trim();
  if (RegExp(r'\b(?:pulg|mm|cm|metro|m)\b').hasMatch(normalized)) {
    return normalized;
  }
  if (RegExp(r'\d+\s*x\s*\d+').hasMatch(normalized.toLowerCase())) {
    return '$normalized pulg';
  }
  return '$normalized 1 pulg';
}

List<String> _negativeMatchTokensFor(
  WorkSupplyItem item,
  String material,
  String shape,
  String text,
) {
  const materials = ['PEX', 'PVC', 'CPVC', 'copper', 'brass', 'cast iron'];
  return _cleanList([
    for (final other in materials)
      if (shape.isNotEmpty &&
          material.isNotEmpty &&
          other.toLowerCase() != material.toLowerCase())
        '$other $shape',
    if (shape.isNotEmpty && !shape.contains('drop-ear')) 'drop-ear $shape',
    if (shape.isNotEmpty && material.toLowerCase() != 'pex') 'PEX crimp $shape',
    if (shape.isNotEmpty && material.toLowerCase() != 'pvc') 'PVC DWV $shape',
    ..._plumbingCoreNegativeMatchTokensFor(item, material, shape, text),
    ..._electricalCoreNegativeMatchTokensFor(item, material, shape, text),
    ..._hvacCoreNegativeMatchTokensFor(item, material, shape, text),
    ..._riskConflictNegativeMatchTokensFor(item, text),
  ]);
}

List<String> _highImportanceTokensFor(
  WorkSupplyItem item,
  String material,
  String size,
  String connectionType,
  String shape,
  String text,
) {
  return _cleanList([
    size,
    material,
    connectionType,
    shape,
    item.itemType,
    if (_containsWord(text, 'kit')) item.system,
    if (_containsWord(text, 'connector')) item.category,
    if (_containsWord(text, 'cement')) item.category,
    if (_containsWord(text, 'primer')) item.category,
    if (_containsWord(text, 'filter')) item.system,
    if (_containsWord(text, 'pvc')) item.system,
    if (_containsWord(text, 'pipe')) item.system,
    ..._plumbingCoreHighImportanceTokensFor(
      item,
      material,
      size,
      connectionType,
      shape,
    ),
    ..._electricalCoreHighImportanceTokensFor(
      item,
      material,
      size,
      connectionType,
      shape,
    ),
    ..._hvacCoreHighImportanceTokensFor(
      item,
      material,
      size,
      connectionType,
      shape,
    ),
  ]);
}

List<String> _plumbingCoreReceiptPatternsFor(
  WorkSupplyItem item,
  String material,
  String size,
  String shape,
) {
  if (!_isPlumbingCoreMetadataTarget(item)) return const [];
  final family = _plumbingCoreFamilyTermsFor(item, shape);
  final compactFamily = _plumbingCompactFamilyTermsFor(item, shape);
  final spanish = _plumbingSpanishCoreFamilyTermsFor(item, shape);
  final sizeToken = size.isEmpty ? item.variant : size;
  final base = _cleanList([
    item.name,
    item.variant,
    item.itemType,
    material,
    shape,
    ...family,
  ]).join(' ');
  return _cleanList([
    base,
    '$sizeToken $base',
    '$material $sizeToken ${family.join(' ')}',
    '$sizeToken ${compactFamily.join(' ')}',
    for (final term in family) '$sizeToken $material $term',
    for (final term in compactFamily) '$sizeToken $term',
    for (final term in compactFamily) 'HD $sizeToken $term',
    for (final term in compactFamily) 'LOWES $sizeToken $term',
    for (final term in compactFamily) 'ACE $sizeToken $term',
    for (final term in compactFamily) 'SUPPLY $sizeToken $term',
    for (final term in spanish) '$sizeToken $term',
    for (final term in spanish) '$term $sizeToken',
  ]);
}

List<String> _plumbingCoreAttributeTokensFor(
  WorkSupplyItem item,
  String material,
  String size,
  String shape,
) {
  if (!_isPlumbingCoreMetadataTarget(item)) return const [];
  return _cleanList([
    'plumbing-core',
    'residential-service',
    'service-truck',
    'hardware-store-stock',
    'box-store-stock',
    'user-review-required',
    'english-us',
    'spanish-us',
    item.path,
    material,
    size,
    shape,
    ..._plumbingCoreFamilyTermsFor(item, shape),
    ..._plumbingCompactFamilyTermsFor(item, shape),
    ..._plumbingSpanishCoreFamilyTermsFor(item, shape),
  ]);
}

List<String> _plumbingCoreHighImportanceTokensFor(
  WorkSupplyItem item,
  String material,
  String size,
  String connectionType,
  String shape,
) {
  if (!_isPlumbingCoreMetadataTarget(item)) return const [];
  return _cleanList([
    'plumbing-core',
    'residential-service',
    item.system,
    item.itemType,
    item.variant,
    material,
    size,
    connectionType,
    shape,
    ..._plumbingCoreFamilyTermsFor(item, shape),
  ]);
}

List<String> _plumbingCoreNegativeMatchTokensFor(
  WorkSupplyItem item,
  String material,
  String shape,
  String text,
) {
  if (!_isPlumbingCoreMetadataTarget(item)) return const [];
  final itemText = '$text ${item.name} ${item.itemType}'.toLowerCase();
  return _cleanList([
    if (!itemText.contains('conduit')) 'electrical conduit',
    if (!itemText.contains('condensate')) 'hvac condensate drain',
    if (!itemText.contains('filter')) 'hvac air filter',
    if (!itemText.contains('paint')) 'paint supplies',
    if (!itemText.contains('irrigation')) 'irrigation sprinkler',
    if (material != 'PVC') 'pvc electrical conduit',
    if (material != 'copper') 'hvac refrigerant copper',
    if (itemText.contains('push') && !itemText.contains('electrical'))
      'electrical connector',
    if (_isWaterTreatmentCoreText(itemText)) 'pool filter',
    if (_isWaterTreatmentCoreText(itemText)) 'swimming pool chemical',
    if (_isWaterTreatmentCoreText(itemText)) 'ice melt salt',
    if (_isWaterTreatmentCoreText(itemText)) 'table salt',
    if (shape != 'valve') 'gas appliance valve',
  ]);
}

List<String> _hvacCoreAttributeTokensFor(
  WorkSupplyItem item,
  String material,
  String size,
  String shape,
) {
  if (!_isHvacCoreItem(item, _workSupplyTierText(item))) return const [];
  return _cleanList([
    'hvac-core',
    'residential-service',
    'service-truck',
    'hardware-store-stock',
    'supply-house-stock',
    'user-review-required',
    'english-us',
    'spanish-us',
    item.path,
    material,
    size,
    shape,
    ..._hvacCoreFamilyTermsFor(item),
  ]);
}

List<String> _hvacCoreHighImportanceTokensFor(
  WorkSupplyItem item,
  String material,
  String size,
  String connectionType,
  String shape,
) {
  if (!_isHvacCoreItem(item, _workSupplyTierText(item))) return const [];
  return _cleanList([
    'hvac-core',
    'residential-service',
    item.system,
    item.itemType,
    item.variant,
    material,
    size,
    connectionType,
    shape,
    ..._hvacCoreFamilyTermsFor(item),
  ]);
}

List<String> _hvacCoreNegativeMatchTokensFor(
  WorkSupplyItem item,
  String material,
  String shape,
  String text,
) {
  if (!_isHvacCoreItem(item, _workSupplyTierText(item))) return const [];
  final itemText = '$text ${item.name} ${item.itemType}'.toLowerCase();
  return _cleanList([
    if (!itemText.contains('water filter')) 'water filter',
    if (!itemText.contains('filter drier')) 'filter drier',
    if (!itemText.contains('conduit')) 'electrical conduit',
    if (!itemText.contains('plumbing')) 'plumbing pvc',
    if (!itemText.contains('irrigation')) 'irrigation tubing',
    if (!itemText.contains('appliance')) 'appliance cord',
    if (!itemText.contains('pool')) 'pool filter',
  ]);
}
