enum WorkSupplyMarketScope { residential, lightIndustrial, commercial }

abstract final class WorkSupplyMarketScopes {
  static const all = [
    WorkSupplyMarketScope.residential,
    WorkSupplyMarketScope.lightIndustrial,
    WorkSupplyMarketScope.commercial,
  ];
}

enum WorkSupplyPackTier { core, standard, professional, complete }

enum WorkSupplyParserPriority {
  everydayCore,
  common,
  occasional,
  rareLegacy,
  specialty,
}

class WorkSupplyItemIntelligence {
  const WorkSupplyItemIntelligence({
    this.material = '',
    this.size = '',
    this.connectionType = '',
    this.shapeOrStyle = '',
    this.packQuantity = '',
    this.isConsumable = false,
    this.isDurable = false,
    this.isBrandSpecific = false,
    this.receiptPatterns = const [],
    this.ocrMistakePatterns = const [],
    this.vendorMappings = const [],
    this.attributeTokens = const [],
    this.negativeMatchTokens = const [],
    this.highImportanceTokens = const [],
    this.mediumImportanceTokens = const [],
    this.lowImportanceTokens = const [],
    this.ignoreTokens = const [],
    this.classification = const WorkSupplyItemClassification(),
    this.catalogVersion = '',
    this.parserVersion = '',
    this.sourceConfidence = '',
    this.verifiedManually = false,
    this.autoGenerated = false,
    this.needsReview = false,
  });

  static const empty = WorkSupplyItemIntelligence();

  final String material;
  final String size;
  final String connectionType;
  final String shapeOrStyle;
  final String packQuantity;
  final bool isConsumable;
  final bool isDurable;
  final bool isBrandSpecific;
  final List<String> receiptPatterns;
  final List<String> ocrMistakePatterns;
  final List<WorkSupplyVendorMapping> vendorMappings;
  final List<String> attributeTokens;
  final List<String> negativeMatchTokens;
  final List<String> highImportanceTokens;
  final List<String> mediumImportanceTokens;
  final List<String> lowImportanceTokens;
  final List<String> ignoreTokens;
  final WorkSupplyItemClassification classification;
  final String catalogVersion;
  final String parserVersion;
  final String sourceConfidence;
  final bool verifiedManually;
  final bool autoGenerated;
  final bool needsReview;

  Iterable<String> get searchableTokens sync* {
    yield material;
    yield size;
    yield connectionType;
    yield shapeOrStyle;
    yield packQuantity;
    yield* receiptPatterns;
    yield* ocrMistakePatterns;
    for (final mapping in vendorMappings) {
      yield mapping.vendor;
      yield mapping.code;
      yield mapping.label;
    }
    yield* attributeTokens;
    yield* negativeMatchTokens;
    yield* highImportanceTokens;
    yield* mediumImportanceTokens;
    yield* lowImportanceTokens;
    yield* ignoreTokens;
    yield* classification.searchableTokens;
    yield catalogVersion;
    yield parserVersion;
    yield sourceConfidence;
  }
}

class WorkSupplyVendorMapping {
  const WorkSupplyVendorMapping({
    required this.vendor,
    required this.code,
    this.label = '',
  });

  final String vendor;
  final String code;
  final String label;
}

class WorkSupplyItemClassification {
  const WorkSupplyItemClassification({
    this.inventoryCategory = '',
    this.expenseCategory = '',
    this.jobMaterialCategory = '',
    this.taxReportingCategory = '',
    this.maintenanceRelevance = '',
    this.billableMaterial = true,
    this.defaultUnitCostBehavior = '',
    this.defaultMarkupBehavior = '',
  });

  final String inventoryCategory;
  final String expenseCategory;
  final String jobMaterialCategory;
  final String taxReportingCategory;
  final String maintenanceRelevance;
  final bool billableMaterial;
  final String defaultUnitCostBehavior;
  final String defaultMarkupBehavior;

  Iterable<String> get searchableTokens sync* {
    yield inventoryCategory;
    yield expenseCategory;
    yield jobMaterialCategory;
    yield taxReportingCategory;
    yield maintenanceRelevance;
    yield defaultUnitCostBehavior;
    yield defaultMarkupBehavior;
  }
}
