part of 'work_supply_catalog_audit.dart';

bool _hasSmartIntelligence(WorkSupplyItem item) {
  final intelligence = item.intelligence;
  return [
        intelligence.material,
        intelligence.size,
        intelligence.connectionType,
        intelligence.shapeOrStyle,
        intelligence.packQuantity,
        intelligence.catalogVersion,
        intelligence.parserVersion,
        intelligence.sourceConfidence,
      ].any((value) => value.trim().isNotEmpty) ||
      intelligence.isConsumable ||
      intelligence.isDurable ||
      intelligence.isBrandSpecific ||
      intelligence.receiptPatterns.isNotEmpty ||
      intelligence.ocrMistakePatterns.isNotEmpty ||
      intelligence.vendorMappings.isNotEmpty ||
      intelligence.attributeTokens.isNotEmpty ||
      intelligence.negativeMatchTokens.isNotEmpty ||
      intelligence.highImportanceTokens.isNotEmpty ||
      intelligence.mediumImportanceTokens.isNotEmpty ||
      intelligence.lowImportanceTokens.isNotEmpty ||
      intelligence.ignoreTokens.isNotEmpty ||
      _hasClassification(intelligence.classification) ||
      intelligence.verifiedManually ||
      intelligence.autoGenerated ||
      intelligence.needsReview;
}

bool _hasClassification(WorkSupplyItemClassification classification) {
  return [
    classification.inventoryCategory,
    classification.expenseCategory,
    classification.jobMaterialCategory,
    classification.taxReportingCategory,
    classification.maintenanceRelevance,
    classification.defaultUnitCostBehavior,
    classification.defaultMarkupBehavior,
  ].any((value) => value.trim().isNotEmpty);
}
