package com.maintainiac

internal fun ReceiptCameraActivity.nativeCaptureDiagnostics(
    photoByteSize: Long,
    capturedAt: String,
): HashMap<String, Any> {
    val activeCamera = camera
    val exposureState = activeCamera?.cameraInfo?.exposureState
    val exposureRange = exposureState?.exposureCompensationRange
    val zoomState = activeCamera?.cameraInfo?.zoomState?.value
    val diagnostics = hashMapOf<String, Any>(
        "engine" to "cameraX",
        "captureSurface" to "maintainiac_native_android",
        "nativeCameraIdentity" to "maintainiac_in_app_receipt_camera",
        "nativeCaptureUiContract" to "maintainiac_custom_receipt_capture_ui_v1",
        "stockCameraUiUsed" to false,
        "nativeTouchControlPolicy" to "continuous_focus_readability_and_pinch_zoom_v1",
        "readabilityGuidanceCoordinateSpace" to "preview_metering_point_factory",
        "tapToFocusPolicy" to tapToFocusPolicy,
        "focusStrategyPolicy" to focusStrategyPolicy,
        "continuousFocusEnabled" to continuousFocusEnabled,
        "readabilityGuidancePolicy" to readabilityGuidancePolicy,
        "receiptCameraQualityBaseline" to receiptCameraQualityBaseline,
        "pinchZoomPolicy" to zoomGesturePolicy,
        "zoomGesturePolicy" to zoomGesturePolicy,
        "previewExposurePolicy" to previewExposurePolicy,
        "previewBrightnessGuardPolicy" to previewBrightnessGuardPolicy,
        "shutterSpeedPolicy" to shutterSpeedPolicy,
        "autoCapturePolicy" to autoCapturePolicy,
        "settingsButtonPlacement" to "top_bar_right",
        "backButtonPlacement" to "top_bar_left",
        "torchButtonPlacement" to "top_bar_right",
        "shutterButtonPlacement" to "bottom_center",
        "reviewNextButtonPlacement" to "top_and_bottom_after_capture",
        "nativeCaptureReviewTransitionPolicy" to "captured_photos_must_open_review_then_receipt_details",
        "nativeCaptureReviewTransitionTarget" to "receipt_photo_review_next_to_receipt_details",
        "nativeCaptureReviewDiscardPolicy" to "never_discard_captured_photo_on_back",
        "captureMode" to "manual",
        "captureQualityMode" to stillCaptureModeLabel,
        "stillCaptureMode" to stillCaptureModeLabel,
        "stillCaptureJpegQuality" to stillCaptureJpegQuality,
        "nativePreviewScaleMode" to nativePreviewScaleMode,
        "nativeControlDensity" to nativeControlDensity,
        "visibleControlSet" to visibleControlSet(),
        "nativeControlReadinessSummary" to nativeControlReadinessSummary(),
        "backControlActual" to backControlActualStatus(),
        "settingsControlActual" to settingsControlActualStatus(),
        "manualShutterControlActual" to manualShutterControlActualStatus(),
        "tapFocusControlActual" to tapFocusControlActualStatus(),
        "pinchZoomControlActual" to pinchZoomControlActualStatus(),
        "exposureSliderControlActual" to exposureSliderControlActualStatus(),
        "exposureResetControlActual" to exposureResetControlActualStatus(),
        "torchControlActual" to torchControlActualStatus(),
        "focusLockControlActual" to focusLockControlActualStatus(),
        "exposureLockControlActual" to exposureLockControlActualStatus(),
        "whiteBalanceLockControlActual" to whiteBalanceLockControlActualStatus(),
        "previewDominanceTarget" to "receipt_preview_75_80_percent",
        "deviceTier" to deviceTier,
        "settingsContractVersion" to settingsContractVersion,
        "devicePolicyLabel" to devicePolicyLabel,
        "cameraResolutionTier" to cameraResolutionTier,
        "cameraWorkloadTier" to cameraWorkloadTier,
        "latestNativeCaptureLatencyBucket" to latestCaptureLatencyBucket,
        "nativeCaptureResponsivenessPolicy" to "manual_shutter_to_review_should_feel_immediate",
        "liveAnalysisEnabled" to liveAnalysisEnabled,
        "autoExposureAssistEnabled" to autoExposureAssistEnabled,
        "edgeDetectionEnabled" to edgeDetectionEnabled,
        "edgeOverlayEnabled" to edgeOverlayEnabled,
        "motionBlurWarningEnabled" to motionBlurWarningEnabled,
        "glareWarningEnabled" to glareWarningEnabled,
        "dirtyLensWarningEnabled" to dirtyLensWarningEnabled,
        "lowLightWarningEnabled" to lowLightWarningEnabled,
        "shadowWarningEnabled" to shadowWarningEnabled,
        "textTooSmallWarningEnabled" to textTooSmallWarningEnabled,
        "perspectiveCorrectionEnabled" to perspectiveCorrectionEnabled,
        "manualCropAfterCapture" to manualCropAfterCapture,
        "saveOriginalTemporarily" to saveOriginalTemporarily,
        "queueAcceptedCaptureLocally" to queueAcceptedCaptureLocally,
        "ocrUsesOriginalFirst" to ocrUsesOriginalFirst,
        "autoCropSuggestionEnabled" to autoCropSuggestionEnabled,
        "grayscalePreviewEnabled" to grayscalePreviewEnabled,
        "contrastBoostEnabled" to contrastBoostEnabled,
        "sharpeningEnabled" to sharpeningEnabled,
        "shadowReductionEnabled" to shadowReductionEnabled,
        "adaptiveThresholdEnabled" to adaptiveThresholdEnabled,
        "orientationCorrectionEnabled" to orientationCorrectionEnabled,
        "receiptGuidanceWarningsEnabled" to receiptGuidanceWarningsEnabled(),
        "experimentalReceiptQualityWarningsEnabled" to hasExperimentalReceiptQualityWarningsEnabled(),
        "experimentalReceiptQualityCandidateSignal" to experimentalReceiptQualityCandidateSignal,
        "experimentalReceiptQualityCandidateCount" to experimentalReceiptQualityCandidateCount,
        "autoExposureAdjustmentCount" to autoExposureAdjustmentCount,
        "preCaptureExposureAdjustmentCount" to preCaptureExposureAdjustmentCount,
        "preCaptureExposureAdjustmentConfirmedCount" to preCaptureExposureAdjustmentConfirmedCount,
        "lastAutoExposureDecision" to lastAutoExposureDecision,
        "lastPreCaptureExposureDecision" to lastPreCaptureExposureDecision,
        "lastPreCaptureExposureSkipReason" to lastPreCaptureExposureSkipReason,
        "preCaptureExposureAbortCount" to preCaptureExposureAbortCount,
        "lastPreCaptureExposureAbortReason" to lastPreCaptureExposureAbortReason,
        "preCaptureExposureOutcome" to preCaptureExposureOutcome(),
        "preCaptureExposurePolicy" to preCaptureExposurePolicy,
        "lastAutoExposureBrightnessBucket" to lastAutoExposureBrightnessBucket,
        "lastAutoExposureCandidate" to lastAutoExposureCandidate,
        "autoExposureCandidateFrameCount" to autoExposureCandidateFrameCount,
        "lastAutoExposureIndex" to lastAutoExposureIndex,
        "lastPreCaptureExposureTargetIndex" to lastPreCaptureExposureTargetIndex,
        "tapFocusCount" to tapFocusCount,
        "tapFocusSuppressedAfterZoomCount" to tapFocusSuppressedAfterZoomCount,
        "zoomChangeCount" to zoomChangeCount,
        "zoomGestureStartCount" to zoomGestureStartCount,
        "zoomUnavailableCount" to zoomUnavailableCount,
        "lastZoomStatus" to lastZoomStatus,
        "lastZoomRatio" to lastZoomRatio,
        "manualExposureChangeCount" to manualExposureChangeCount,
        "settingsOpenCount" to settingsOpenCount,
        "settingsResetCount" to settingsResetCount,
        "lastFocusStatus" to lastFocusStatus,
        "focusMode" to focusMode,
        "exposureMode" to exposureMode,
        "whiteBalanceMode" to whiteBalanceMode,
        "whiteBalanceLockEnabled" to false,
        "focusLockAttemptCount" to focusLockAttemptCount,
        "focusLockSuccessCount" to focusLockSuccessCount,
        "exposureLockSuccessCount" to exposureLockSuccessCount,
        "whiteBalanceLockStatus" to whiteBalanceLockStatus,
        "autoCaptureStableFrameCount" to autoCaptureStableFrameCount,
        "autoCaptureTriggerCount" to autoCaptureTriggerCount,
        "manualShutterTapCount" to manualShutterTapCount,
        "manualCaptureStartedCount" to manualCaptureStartedCount,
        "autoCaptureAttemptCount" to autoCaptureAttemptCount,
        "autoCaptureStartedCount" to autoCaptureStartedCount,
        "captureBlockedNoCameraCount" to captureBlockedNoCameraCount,
        "captureBlockedBusyCount" to captureBlockedBusyCount,
        "captureBlockedClosingCount" to captureBlockedClosingCount,
        "captureBlockedSurfaceInactiveCount" to captureBlockedSurfaceInactiveCount,
        "lastCaptureTrigger" to lastCaptureTrigger,
        "lastCaptureBlockReason" to lastCaptureBlockReason,
        "latestAutoCaptureStatus" to latestAutoCaptureStatus,
        "closeAction" to closeAction,
        "closeCapturedPhotoPolicy" to closeCapturedPhotoPolicy,
        "closeDuringCapturePolicy" to closeDuringCapturePolicy,
        "closeNoPhotoPolicy" to closeNoPhotoPolicy,
        "capturedPhotoReviewDestination" to capturedPhotoReviewDestination,
        "capturedPhotoBackBehavior" to closeCapturedPhotoPolicy,
        "capturedPhotoCloseUserCopy" to "Back keeps captured photos and opens receipt photo review.",
        "noPhotoCloseUserCopy" to "Back closes the camera when no receipt photo was captured.",
        "closeCapturedPhotoOutcome" to closeCapturedPhotoOutcome(),
        "closeRetryCount" to closeRetryCount,
        "closeRequestCount" to closeRequestCount,
        "closeDuringCaptureCount" to closeDuringCaptureCount,
        "closeNoPhotoCancelCount" to closeNoPhotoCancelCount,
        "closeReturnedSectionsCount" to closeReturnedSectionsCount,
        "lastBackDispatchPath" to lastBackDispatchPath,
        "closingCamera" to closingCamera,
        "pendingCloseAfterCapture" to pendingCloseAfterCapture,
        "closeResultDelivered" to closeResultDelivered,
        "exposureAssistStatus" to exposureAssistStatus(),
        "userExposureOverride" to userExposureOverride,
        "analysisGapMs" to analysisGapMs,
        "readyHoldMs" to readyHoldMs,
        "assistedShotCount" to assistedShotCount,
        "bestShotCandidateCount" to bestShotCandidateCount,
        "maxLiveAnalysisPixels" to maxLiveAnalysisPixels,
        "maxCleanupPixels" to maxCleanupPixels,
        "maxStitchOutputPixels" to maxStitchOutputPixels,
        "maxStitchOutputHeight" to maxStitchOutputHeight,
        "latestFrameBrightness" to latestFrameBrightness,
        "latestShadowScore" to latestShadowScore,
        "latestBrightnessBucket" to brightnessBucket(latestFrameBrightness),
        "latestReadabilitySignal" to latestReadabilitySignal,
        "latestFramingSignal" to latestFramingSignal,
        "latestFramingConfidence" to latestFramingConfidence,
        "latestEdgeCoverage" to latestEdgeCoverage,
        "latestFramingWidthRatio" to latestFramingWidthRatio,
        "latestFramingHeightRatio" to latestFramingHeightRatio,
        "latestPerspectiveReadiness" to latestPerspectiveReadiness,
        "latestMotionSignal" to latestMotionSignal,
        "latestMotionScore" to latestMotionScore,
        "assistedReceiptFill" to assistedReceiptFill,
        "longReceiptMode" to longReceiptMode,
        "captureReadinessCode" to captureReadinessCode(),
        "captureReadinessLabel" to captureReadinessLabel(),
        "manualCaptureAllowed" to true,
        "autoCaptureEnabled" to autoCaptureEnabled,
        "autoCaptureAllowed" to autoCaptureAllowed,
        "stableFrameCount" to autoCaptureStableFrameCount,
        "requiredStableFrames" to autoCaptureStableFrameTarget,
        "autoCaptureMaxMotionScore" to autoCaptureMaxMotionScore,
        "autoCaptureMinBrightness" to autoCaptureMinBrightness,
        "autoCaptureMaxBrightness" to autoCaptureMaxBrightness,
        "autoCaptureCooldownMs" to autoCaptureCooldownMs,
        "autoCaptureCurrentlyAllowed" to isAutoCaptureCurrentlyAllowed(),
        "autoCaptureSafetyPolicy" to "optional_manual_shutter_always_available",
        "manualCapturePolicy" to "guidance_advisory_manual_shutter_always_allowed",
        "guidanceBlockingPolicy" to "quality_guidance_warns_never_blocks_manual_capture",
        "manualCaptureBlockPolicy" to "only_busy_closing_no_camera_or_inactive_surface",
        "reviewDepth" to reviewDepth,
        "dataSaverLevel" to dataSaverLevel,
        "storageSafetyLevel" to storageSafetyLevel,
        "storageConstrained" to storageConstrained,
        "storageSafetyReason" to storageSafetyReason,
        "workloadProtectionPolicy" to workloadProtectionPolicy,
        "maxLocalPhotoBytes" to maxLocalPhotoBytes,
        "nativeCaptureMemoryPolicy" to nativeCaptureMemoryPolicy,
        "torchOn" to torchOn,
        "hasFlashUnit" to (activeCamera?.cameraInfo?.hasFlashUnit() == true),
        "exposureCompensationIndex" to (exposureState?.exposureCompensationIndex ?: 0),
        "exposureCompensationRangeLower" to (exposureRange?.lower ?: 0),
        "exposureCompensationRangeUpper" to (exposureRange?.upper ?: 0),
        "zoomRatio" to ((zoomState?.zoomRatio ?: 1f).toDouble()),
        "minZoomRatio" to ((zoomState?.minZoomRatio ?: 1f).toDouble()),
        "maxZoomRatio" to ((zoomState?.maxZoomRatio ?: 1f).toDouble()),
        "sessionMinZoom" to sessionMinZoom,
        "sessionMaxZoom" to sessionMaxZoom,
        "sessionMinExposureOffset" to sessionMinExposureOffset,
        "sessionMaxExposureOffset" to sessionMaxExposureOffset,
        "tapFocusEnabled" to false,
        "pinchZoomEnabled" to pinchZoomEnabled,
        "exposureSliderEnabled" to exposureSliderEnabled,
        "exposureResetEnabled" to exposureResetEnabled,
        "nativeControlContractVersion" to "receipt_native_controls_v1",
        "nativeControlContractTags" to nativeControlContractTags,
        "controlDiagnosticsPrivacyScope" to "summary_only_no_receipt_content",
        "tapFocusControlExpected" to false,
        "pinchZoomControlExpected" to pinchZoomEnabled,
        "exposureSliderControlExpected" to exposureSliderEnabled,
        "exposureResetControlExpected" to exposureResetEnabled,
        "settingsControlExpected" to true,
        "backControlExpected" to true,
        "torchControlExpected" to (activeCamera?.cameraInfo?.hasFlashUnit() == true),
        "focusLockControlExpected" to false,
        "exposureLockControlExpected" to false,
        "whiteBalanceLockControlExpected" to false,
        "manualShutterAlwaysAvailable" to intent.getBooleanExtra("manualShutterAlwaysAvailable", true),
    )
    diagnostics.putAll(nativeCapturedPhotoDiagnostics(photoByteSize, capturedAt))
    diagnostics.putAll(longReceiptSectionDiagnostics())
    diagnostics.putAll(previousSectionCaptureDiagnostics())
    return diagnostics
}

internal fun ReceiptCameraActivity.captureReadinessCode(): String {
    if (!autoCaptureEnabled) return "manual_ready_auto_capture_off"
    return when (latestAutoCaptureStatus) {
        "capturing" -> "auto_capture_ready"
        "waiting_for_edges" -> "manual_only_check_framing"
        "waiting_for_light" -> "manual_only_quality_retake_recommended"
        "waiting_for_quality_review" -> "manual_only_quality_review"
        "closing" -> "manual_ready_auto_capture_off"
        else -> "auto_capture_waiting_for_stability"
    }
}

internal fun ReceiptCameraActivity.captureReadinessLabel(): String {
    return when (captureReadinessCode()) {
        "auto_capture_ready" -> "Receipt looks steady. Taking photo."
        "manual_only_check_framing" -> "Check that every receipt line is visible before auto capture."
        "manual_only_quality_retake_recommended" -> "Improve lighting before automatic capture."
        "manual_only_quality_review" -> "Check sharpness, light, and receipt text before automatic capture."
        "auto_capture_waiting_for_stability" -> "Hold steady for automatic capture."
        else -> "Manual capture is ready. Auto capture is off."
    }
}
