import 'work_supply_catalog_blueprint_model.dart';
import 'work_supply_catalog_blueprint_hvac_tiers.dart';

final hvacResidentialCompleteAddOnFamilies = <CatalogFamily>[
  CatalogFamily(
    slug: 'inline_float_switch',
    category: 'Condensate Safety',
    system: 'Condensate Drain',
    itemType: 'Float Switch',
    material: 'plastic switch',
    unit: 'each',
    sizes: ['inline', 'secondary pan'],
    nameTemplate: '{size} Condensate Float Switch',
    aliasTemplates: ['{size} float switch', '{size} overflow switch'],
    receiptTemplates: ['{size} FLOAT SWITCH', '{size} OVERFLOW SWITCH'],
    negativeTokens: ['sump pump float', 'well pump switch', 'water heater pan'],
  ),
  CatalogFamily(
    slug: 'secondary_drain_pan',
    category: 'Condensate Safety',
    system: 'Air Handler',
    itemType: 'Drain Pan',
    material: 'galvanized steel',
    unit: 'each',
    sizes: ['24x24 in', '30x30 in', '36x36 in'],
    nameTemplate: '{size} Secondary Drain Pan',
    aliasTemplates: ['{size} drain pan', '{size} ac pan'],
    receiptTemplates: ['{size} DRAIN PAN', '{size} SECONDARY PAN'],
    negativeTokens: ['water heater pan', 'paint tray', 'oil drain pan'],
  ),
  CatalogFamily(
    slug: 'pvc_condensate_trap',
    category: 'Condensate Drain',
    system: 'Condensate Drain',
    itemType: 'Condensate Trap',
    material: 'PVC',
    unit: 'each',
    sizes: ['3/4 in', '1 in'],
    nameTemplate: '{size} PVC Condensate Trap',
    aliasTemplates: ['{size} condensate trap', '{size} ez trap'],
    receiptTemplates: ['{size} COND TRAP', '{size} EZ TRAP'],
    negativeTokens: ['sink p trap', 'tubular p trap', 'drum trap'],
  ),
  CatalogFamily(
    slug: 'liquid_line_filter_drier',
    category: 'Refrigerant Line',
    system: 'Refrigerant Circuit',
    itemType: 'Filter Drier',
    material: 'copper shell',
    unit: 'each',
    sizes: ['1/4 in', '3/8 in', '1/2 in'],
    nameTemplate: '{size} Liquid Line Filter Drier',
    aliasTemplates: ['{size} filter drier', '{size} liquid drier'],
    receiptTemplates: ['{size} FILTER DRIER', '{size} LIQ DRIER'],
    negativeTokens: ['air filter', 'water filter', 'oil filter'],
  ),
  CatalogFamily(
    slug: 'thermostat_wire_roll',
    category: 'Controls and Low Voltage',
    system: 'Low Voltage Control',
    itemType: 'Thermostat Wire',
    material: 'copper conductors',
    unit: 'roll',
    sizes: ['18/2', '18/5', '18/8'],
    nameTemplate: '{size} Thermostat Wire',
    aliasTemplates: ['{size} stat wire', '{size} thermostat cable'],
    receiptTemplates: ['{size} STAT WIRE', '{size} TSTAT WIRE'],
    negativeTokens: ['romex', 'thhn', 'speaker wire'],
  ),
  CatalogFamily(
    slug: 'service_valve_cap_pack',
    category: 'Refrigerant Line',
    system: 'Service Valves',
    itemType: 'Service Valve Cap',
    material: 'brass',
    unit: 'pack',
    sizes: ['1/4 in', '5/16 in', 'assorted'],
    nameTemplate: '{size} Service Valve Cap Pack',
    aliasTemplates: ['{size} valve cap pack', '{size} service cap'],
    receiptTemplates: ['{size} VALVE CAP', '{size} SERVICE CAP'],
    negativeTokens: ['plumbing cap', 'pipe cap', 'tire valve cap'],
  ),
  CatalogFamily(
    slug: 'heat_pump_defrost_board',
    category: 'Controls and Low Voltage',
    system: 'Heat Pump',
    itemType: 'Defrost Board',
    material: 'control board',
    unit: 'each',
    sizes: ['universal', 'heat pump'],
    nameTemplate: '{size} Defrost Control Board',
    aliasTemplates: ['{size} defrost board', '{size} heat pump board'],
    receiptTemplates: ['{size} DEFROST BOARD', '{size} HP DFROST CTRL'],
    negativeTokens: ['furnace control board', 'zone board', 'thermostat'],
  ),
  ...hvacResidentialProfessionalFamilies,
];
