import 'dart:convert';
import 'dart:io';

const _usage =
    'dart run tool/work_supply_parser_qa_peh_core_mac_handoff_script.dart '
    '[--packet build/parser_qa_pipeline/peh_core_mac_handoff_packet.json] '
    '[--output build/parser_qa_pipeline/peh_core_mac_handoff.sh]';

Future<void> main(List<String> args) async {
  final exit = runWorkSupplyParserQaPehCoreMacHandoffScript(
    args,
    stdout: stdout,
    stderr: stderr,
  );
  if (exit != 0) exitCode = exit;
}

int runWorkSupplyParserQaPehCoreMacHandoffScript(
  List<String> args, {
  required IOSink stdout,
  required IOSink stderr,
}) {
  if (args.contains('--help') || args.contains('-h')) {
    stdout.writeln(_usage);
    return 0;
  }

  final packetPath = _value(
    args,
    'packet',
    'build/parser_qa_pipeline/peh_core_mac_handoff_packet.json',
  );
  final output = _value(
    args,
    'output',
    'build/parser_qa_pipeline/peh_core_mac_handoff.sh',
  );

  final packetFile = File(packetPath);
  if (!packetFile.existsSync()) {
    stderr.writeln('--packet must exist.');
    return 66;
  }

  final packet =
      jsonDecode(packetFile.readAsStringSync()) as Map<String, Object?>;
  final reusableCheckpoint = _readReusableCheckpoint();
  final branch = packet['branch']?.toString() ?? 'unknown';
  final commit = packet['commit']?.toString() ?? 'unknown';
  final reusableBaselineBranch =
      packet['reusableBaselineBranch']?.toString() ??
      reusableCheckpoint['primaryBranch']?.toString() ??
      'unknown';
  final reusableValidatedFloorCommit =
      packet['reusableValidatedFloorCommit']?.toString() ??
      reusableCheckpoint['validatedFloorCommit']?.toString() ??
      'unknown';
  final reusableHandoffMarkerPath =
      packet['reusableHandoffMarkerPath']?.toString() ??
      'docs/reusable_parsing_qa_handoff_marker.md';
  final reusableCheckpointMarkdownPath =
      packet['reusableCheckpointMarkdownPath']?.toString() ??
      'docs/reusable_parsing_qa_checkpoint.md';
  final measurementCommands =
      (packet['measurementCommands'] as List<dynamic>? ?? const <dynamic>[])
          .whereType<Map>()
          .map((entry) => entry.cast<String, Object?>())
          .toList();
  final rollupCommands =
      (packet['rollupCommands'] as List<dynamic>? ?? const <dynamic>[])
          .whereType<Map>()
          .map((entry) => entry.cast<String, Object?>())
          .toList();
  final refreshCommand =
      (packet['refreshCommand'] as List<dynamic>? ?? const <dynamic>[])
          .map((value) => value.toString())
          .toList();

  final lines = <String>[
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    '# Generated by work_supply_parser_qa_peh_core_mac_handoff_script.dart',
    '# Branch: $branch',
    '# Commit: $commit',
    '# Reusable baseline branch: $reusableBaselineBranch',
    '# Reusable validated floor: $reusableValidatedFloorCommit',
    '',
    'echo "Read reusable baseline marker first: $reusableHandoffMarkerPath"',
    'echo "Confirm reusable checkpoint: $reusableCheckpointMarkdownPath"',
    'echo "Reusable baseline branch: $reusableBaselineBranch @ $reusableValidatedFloorCommit"',
    'echo "Inventory execution branch: $branch @ $commit"',
    '',
    'echo "Running PEH Core Mac handoff wave for $branch @ $commit"',
    '',
  ];

  for (final command in measurementCommands) {
    final trade = command['trade']?.toString() ?? 'unknown';
    final locale = command['localePackId']?.toString() ?? 'unknown';
    final parts =
        (command['command'] as List<dynamic>? ?? const <dynamic>[])
            .map((value) => value.toString())
            .toList();
    lines.add('echo "Measurement: $trade $locale"');
    lines.add(_shell(parts));
    lines.add('');
  }

  for (final command in rollupCommands) {
    final trade = command['trade']?.toString() ?? 'unknown';
    final parts =
        (command['command'] as List<dynamic>? ?? const <dynamic>[])
            .map((value) => value.toString())
            .toList();
    lines.add('echo "Rollup: $trade"');
    lines.add(_shell(parts));
    lines.add('');
  }

  if (refreshCommand.isNotEmpty) {
    lines.add('echo "Refresh downstream PEH truth artifacts"');
    lines.add(_shell(refreshCommand));
    lines.add('');
  }

  final outputFile = File(output)..parent.createSync(recursive: true);
  outputFile.writeAsStringSync('${lines.join('\n')}\n', flush: true);

  stdout.writeln(
    'QA_PEH_CORE_MAC_HANDOFF_SCRIPT '
    '${jsonEncode({
      'packetPath': packetPath,
      'output': output,
      'branch': branch,
      'commit': commit,
      'measurementCommandCount': measurementCommands.length,
      'rollupCommandCount': rollupCommands.length,
      'hasRefreshCommand': refreshCommand.isNotEmpty,
    })}',
  );
  stdout.writeln('QA_PEH_CORE_MAC_HANDOFF_SCRIPT_ARTIFACT script=${outputFile.path}');
  return 0;
}

String _shell(List<String> parts) {
  return parts.map((part) => _quote(_normalizeForShell(part))).join(' ');
}

String _quote(String value) {
  final escaped = value.replaceAll("'", r"'\''");
  return "'$escaped'";
}

String _normalizeForShell(String value) {
  return value.replaceAll(r'\', '/');
}

String _value(List<String> args, String key, String fallback) {
  for (var index = 0; index < args.length; index++) {
    final arg = args[index];
    if (arg == '--$key' && index + 1 < args.length) return args[index + 1];
    if (arg.startsWith('--$key=')) return arg.substring(key.length + 3);
  }
  return fallback;
}

Map<String, Object?> _readReusableCheckpoint() {
  final file = File('docs/reusable_parsing_qa_checkpoint.json');
  if (!file.existsSync()) {
    return const {};
  }
  final decoded = jsonDecode(file.readAsStringSync());
  if (decoded is Map<String, Object?>) {
    return decoded;
  }
  if (decoded is Map) {
    return decoded.cast<String, Object?>();
  }
  return const {};
}
