import 'work_supply_parser_qa_fixture_recipes.dart';
import 'work_supply_parser_qa_fixture_recipes_hvac_professional.dart';

const englishHvacCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'float_switch',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Float Switch',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'float_switch', 'complete_pack'],
    patterns: ['INLINE FLOAT SWITCH', 'SECONDARY PAN FLOAT SWITCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'secondary_drain_pan',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Drain Pan',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'drain_pan', 'complete_pack'],
    patterns: ['30X30 SECONDARY PAN', '24X24 AC DRAIN PAN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condensate_trap',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate Trap',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'trap', 'complete_pack'],
    patterns: ['3/4 COND TRAP', '1 IN EZ TRAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'filter_drier',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Filter Drier',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'refrigerant', 'filter_drier', 'complete_pack'],
    patterns: ['3/8 FILTER DRIER', '1/2 LIQ DRIER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'thermostat_wire',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Thermostat Wire',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'low_voltage', 'thermostat_wire', 'complete_pack'],
    patterns: ['18/5 STAT WIRE', '18/8 TSTAT WIRE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_valve_cap',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Service Valve Cap',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'refrigerant', 'service_valve_cap', 'complete_pack'],
    patterns: ['1/4 VALVE CAP', 'ASSORTED SERVICE CAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'defrost_board',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Defrost',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'heat_pump', 'defrost_board', 'complete_pack'],
    patterns: ['UNIV DEFROST BOARD', 'HEAT PUMP HP DFROST CTRL'],
  ),
  ...englishHvacProfessionalRecipes,
];

const spanishHvacCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'switch_flotador',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Float Switch',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'float_switch', 'complete_pack'],
    patterns: ['SWITCH FLOTADOR INLINEA', 'FLOTADOR BANDEJA SEC'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'bandeja_drenaje',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Drain Pan',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'drain_pan', 'complete_pack'],
    patterns: ['BANDEJA DRENAJE 30X30', 'BANDEJA AC 24X24'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'trampa_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate Trap',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate_trap', 'complete_pack'],
    patterns: ['TRAMPA CONDENSADO 3/4', 'TRAMPA EZ 1 IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'filtro_secador',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Filter Drier',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'filter_drier', 'complete_pack'],
    patterns: ['FILTRO SECADOR 3/8', 'SECADOR LINEA 1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cable_termostato',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Thermostat Wire',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'thermostat_wire', 'complete_pack'],
    patterns: ['CABLE TERMOSTATO 18/5', 'CABLE TSTAT 18/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tapa_valvula_servicio',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Service Valve Cap',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'service_valve_cap', 'complete_pack'],
    patterns: ['TAPA VALVULA SERV 1/4', 'TAPA SERVICIO SURTIDA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tarjeta_descongelar',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Defrost',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'defrost_board', 'complete_pack'],
    patterns: ['TARJETA DESCONGELAR UNIV', 'CONTROL DEFROST BOMBA CALOR'],
  ),
  ...spanishHvacProfessionalRecipes,
];
