import 'dart:convert';
import 'dart:io';

const _usage =
    'dart run tool/work_supply_catalog_blueprint_validate.dart '
    '--input build/parser_qa_blueprints/.../item_blueprints.json';

Future<void> main(List<String> args) async {
  final exit = await runWorkSupplyCatalogBlueprintValidator(
    args,
    stdout: stdout,
    stderr: stderr,
  );
  if (exit != 0) exitCode = exit;
}

Future<int> runWorkSupplyCatalogBlueprintValidator(
  List<String> args, {
  required IOSink stdout,
  required IOSink stderr,
}) async {
  if (args.contains('--help') || args.contains('-h')) {
    stdout.writeln(_usage);
    return 0;
  }
  final input = _value(args, 'input');
  if (input.isEmpty) {
    stderr.writeln('Missing required --input path.');
    return 64;
  }
  final file = File(input);
  if (!file.existsSync()) {
    stderr.writeln('Blueprint file does not exist: $input');
    return 66;
  }

  final decoded = jsonDecode(file.readAsStringSync());
  if (decoded is! List) {
    stderr.writeln('Blueprint file must contain a JSON list.');
    return 65;
  }
  final issues = _validateBlueprints(decoded.cast<Object?>());
  final summary = {
    'schemaVersion': 1,
    'input': input,
    'checked': decoded.length,
    'issueCount': issues.length,
    'issues': issues.take(100).toList(),
    'promotionAllowed': issues.isEmpty,
    'liveServicesAllowed': false,
  };
  stdout.writeln(
    'QA_CATALOG_BLUEPRINT_VALIDATION '
    '${const JsonEncoder.withIndent('  ').convert(summary)}',
  );
  return issues.isEmpty ? 0 : 1;
}

List<String> _validateBlueprints(List<Object?> decoded) {
  final issues = <String>[];
  final ids = <String>{};
  for (var index = 0; index < decoded.length; index++) {
    final entry = decoded[index];
    if (entry is! Map) {
      issues.add('row_$index:not_object');
      continue;
    }
    final row = entry.cast<String, Object?>();
    final id = _text(row['id']);
    if (id.isEmpty) {
      issues.add('row_$index:missing_id');
    } else if (!ids.add(id)) {
      issues.add('$id:duplicate_id');
    }
    for (final field in [
      'canonicalName',
      'trade',
      'category',
      'system',
      'itemType',
      'itemFamily',
      'material',
      'size',
      'unit',
      'sourceConfidence',
      'promotionMode',
    ]) {
      if (_text(row[field]).isEmpty) issues.add('$id:missing_$field');
    }
    for (final field in [
      'aliases',
      'receiptPatterns',
      'negativeMatchTokens',
      'highImportanceTokens',
    ]) {
      if (_stringList(row[field]).isEmpty) issues.add('$id:empty_$field');
    }
    if (row['verifiedManually'] == true) {
      issues.add('$id:generated_blueprint_cannot_be_verified_manually');
    }
    if (row['autoGenerated'] != true) {
      issues.add('$id:autoGenerated_must_be_true');
    }
    if (row['needsReview'] != true) {
      issues.add('$id:needsReview_must_be_true');
    }
    if (_text(row['promotionMode']) != 'manual-review-required') {
      issues.add('$id:promotion_must_require_manual_review');
    }
    final classification = row['classification'];
    if (classification is! Map || classification.isEmpty) {
      issues.add('$id:missing_classification');
    }
  }
  return issues;
}

String _value(List<String> args, String key) {
  for (var index = 0; index < args.length; index++) {
    final arg = args[index];
    if (arg == '--$key' && index + 1 < args.length) return args[index + 1];
    if (arg.startsWith('--$key=')) return arg.substring(key.length + 3);
  }
  return '';
}

String _text(Object? value) => value?.toString().trim() ?? '';

List<String> _stringList(Object? value) {
  if (value is! List) return const [];
  return [
    for (final entry in value)
      if (entry.toString().trim().isNotEmpty) entry.toString().trim(),
  ];
}
