class WorkSupplyFixtureRecipe {
  const WorkSupplyFixtureRecipe({
    required this.slug,
    required this.caseType,
    required this.patterns,
    required this.riskTags,
    this.expectedTrade = 'Plumbing',
    this.expectedNameContains = '',
    this.tradeScope = 'Plumbing',
    this.expectUnknown = false,
    this.maxConfidence = 1,
  });

  final String slug;
  final String caseType;
  final List<String> patterns;
  final List<String> riskTags;
  final String expectedTrade;
  final String expectedNameContains;
  final String tradeScope;
  final bool expectUnknown;
  final double maxConfidence;
}

const englishPlumbingCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'pex_crimp_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PEX',
    riskTags: [
      'pex',
      'crimp',
      'elbow',
      'size',
      'merchant_abbreviation',
      'generated_batch',
    ],
    patterns: ['1/2 PEX CRMP ELL', '3/4 PEX 90', '1/2IN PEX ELB'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Coupling',
    riskTags: ['pex', 'coupling', 'service_truck', 'core_plumbing'],
    patterns: ['1/2 PEX CPLG', '3/4 PEX COUPLING', '1 IN PEX CPLG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_transition_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Transition Coupling',
    riskTags: ['pex', 'transition', 'coupling', 'service_truck'],
    patterns: [
      '1/2 PEX TRANS CPLG',
      '3/4 PEX TRANSITION COUPLING',
      '1 IN PEX TRANS COUPLER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_male_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Male Adapter',
    riskTags: ['pex', 'adapter', 'male_adapter', 'service_truck'],
    patterns: ['1/2 PEX M ADPT', '3/4 PEX MALE ADAPTER', '1 IN PEX MIP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_female_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Female Adapter',
    riskTags: ['pex', 'adapter', 'female_adapter', 'service_truck'],
    patterns: ['1/2 PEX F ADPT', '3/4 PEX FEMALE ADAPTER', '1 IN PEX FIP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Tee',
    riskTags: ['pex', 'tee', 'service_truck', 'core_plumbing'],
    patterns: ['1/2 PEX TEE', '3/4 PEX T', '1 X 3/4 PEX TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_drop_ear_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Drop-Ear Elbow',
    riskTags: ['pex', 'drop_ear', 'elbow', 'stub_out', 'service_truck'],
    patterns: [
      '1/2 PEX DROP EAR ELL',
      '1/2 PEX DROP-EAR ELBOW',
      '3/4 PEX SHOWER ELBOW',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_crimp_ring',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Crimp Ring',
    riskTags: ['pex', 'crimp_ring', 'service_truck', 'consumable'],
    patterns: ['1/2 PEX CRIMP RING', '3/4 PEX CRMP RING', '1 IN PEX RING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_clamp_ring',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Clamp Ring',
    riskTags: ['pex', 'clamp_ring', 'cinch', 'service_truck', 'consumable'],
    patterns: ['1/2 PEX CLAMP RING', '3/4 PEX CINCH CLAMP', '1 IN PEX CLAMP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_crimp_tool',
    caseType: 'clear_match',
    expectedNameContains: 'PEX crimp tool',
    riskTags: ['pex', 'tool', 'crimp_tool', 'service_truck'],
    patterns: ['1/2 PEX CRIMP TOOL', '1/2 3/4 PEX CRIMP TOOL', 'PEX CRMP TOOL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_cinch_tool',
    caseType: 'clear_match',
    expectedNameContains: 'PEX clamp cinch tool',
    riskTags: ['pex', 'tool', 'cinch_tool', 'service_truck'],
    patterns: ['PEX CINCH TOOL', 'PEX CLAMP TOOL', 'PEX CLAMP CINCH TOOL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Coupling',
    riskTags: ['pvc', 'schedule_40', 'coupling', 'size'],
    patterns: ['3/4 PVC SCH40 CPLG', '1 PVC S40 COUPLING', '1/2 PVC CPLG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'elbow'],
    patterns: ['1/2 PVC SCH 40 90 ELB', '3/4 PVC S40 45 ELL', '1 IN PVC 90'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'adapter'],
    patterns: [
      '1/2 PVC SCH 40 MALE ADPT',
      '3/4 PVC SCH40 FEMALE ADAPTER',
      '1 IN PVC S40 F ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Tee',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'tee'],
    patterns: ['1/2 PVC SCH40 TEE', '3/4 PVC S40 T', '1 X 3/4 PVC SCH40 TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_reducer_bushing',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Reducer',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'reducer', 'bushing'],
    patterns: [
      '3/4 X 1/2 PVC SCH40 RED BUSH',
      '1 X 3/4 PVC S40 REDUCER BUSHING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_reducing_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Reducing Coupling',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'reducing_coupling'],
    patterns: [
      '3/4 X 1/2 PVC SCH40 REDUCING CPLG',
      '1 X 3/4 PVC S40 REDUCER COUPLING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_90_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV 90 Elbow',
    riskTags: ['pvc_dwv', 'dwv', 'elbow', 'drainage'],
    patterns: ['1-1/2 PVC DWV 90 ELB', '2 IN PVC DWV 90', '3 PVC DRAIN 90'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_45_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV 45 Elbow',
    riskTags: ['pvc_dwv', 'dwv', 'elbow', 'drainage'],
    patterns: ['1-1/2 PVC DWV 45 ELB', '2 IN PVC DWV 45', '3 PVC DRAIN 45'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_wye',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Wye',
    riskTags: ['pvc_dwv', 'dwv', 'wye', 'drainage'],
    patterns: ['2 PVC DWV WYE', '3 IN PVC DWV Y FITTING', '4 PVC DRAIN WYE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_sanitary_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Sanitary Tee',
    riskTags: ['pvc_dwv', 'dwv', 'sanitary_tee', 'drainage'],
    patterns: ['1-1/2 PVC DWV SAN TEE', '2 PVC SANITARY T', '3 PVC DWV SANTEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_reducing_sanitary_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Reducing Sanitary Tee',
    riskTags: ['pvc_dwv', 'dwv', 'sanitary_tee', 'reducing', 'drainage'],
    patterns: [
      '2 X 2 X 1-1/2 PVC DWV REDUCING SAN TEE',
      '3 X 3 X 2 PVC DWV REDUCING SANITARY',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Coupling',
    riskTags: ['pvc_dwv', 'dwv', 'coupling', 'drainage'],
    patterns: ['1-1/2 PVC DWV CPLG', '2 PVC DWV COUPLING', '3 PVC DRAIN CPLG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_reducing_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Reducing Coupling',
    riskTags: ['pvc_dwv', 'dwv', 'coupling', 'reducing', 'drainage'],
    patterns: [
      '2 X 1-1/2 PVC DWV REDUCING CPLG',
      '3 X 2 PVC DWV REDUCER COUPLING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_trap_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Trap Adapter',
    riskTags: ['pvc_dwv', 'dwv', 'trap_adapter', 'drainage'],
    patterns: [
      '1-1/2 PVC DWV TRAP ADAPTER',
      '2 PVC DWV TRAP ADAPTER',
      '1-1/2 PVC TRAP ADAPTER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_cleanout',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Cleanout',
    riskTags: ['pvc_dwv', 'dwv', 'cleanout', 'drainage'],
    patterns: ['1-1/2 PVC DWV CLEANOUT', '2 PVC DWV CLEAN OUT', '3 PVC CO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_test_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Test Tee',
    riskTags: ['pvc_dwv', 'dwv', 'test_tee', 'cleanout', 'drainage'],
    patterns: ['1-1/2 PVC DWV TEST TEE', '2 PVC CLEANOUT TEE', '3 PVC TEST T'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cleanout_access_plug',
    caseType: 'clear_match',
    expectedNameContains: 'cleanout plug',
    riskTags: ['pvc_dwv', 'cleanout', 'access', 'plug', 'drainage'],
    patterns: [
      '1-1/2 FLUSH CLEANOUT PLUG',
      '2 IN COUNTERSUNK CLEANOUT PLUG',
      '3 BRASS CLEANOUT PLUG',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cleanout_access_cover',
    caseType: 'clear_match',
    expectedNameContains: 'cleanout cover',
    riskTags: ['pvc_dwv', 'cleanout', 'access', 'cover', 'drainage'],
    patterns: ['1-1/2 ROUND CLEANOUT COVER', '2 SQUARE CLEANOUT COVER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_discharge_hose_kit',
    caseType: 'clear_match',
    expectedNameContains: 'discharge hose kit',
    riskTags: ['sump_discharge', 'sump', 'discharge_hose', 'pump'],
    patterns: [
      '1-1/4 SUMP DISCHARGE HOSE KIT',
      '1-1/2 DISCHARGE HOSE KIT',
      'SUMP PUMP HOSE KIT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_rubber_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'rubber coupling',
    riskTags: ['sump_discharge', 'sump', 'rubber_coupling', 'pump'],
    patterns: ['1-1/4 SUMP RUBBER COUPLING', '1-1/2 RUBBER COUPLING SUMP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_pvc_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PVC adapter',
    riskTags: ['sump_discharge', 'sump', 'pvc_adapter', 'pump'],
    patterns: ['1-1/4 SUMP PVC ADAPTER', '1-1/2 PVC ADAPTER SUMP PUMP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_barbed_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'barbed adapter',
    riskTags: ['sump_discharge', 'sump', 'barbed_adapter', 'pump'],
    patterns: ['1-1/4 SUMP BARBED ADAPTER', '1-1/2 BARBED ADAPTER SUMP PUMP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_pump',
    caseType: 'clear_match',
    expectedNameContains: 'Sump Pump',
    riskTags: ['sump_discharge', 'sump', 'pump', 'service_truck'],
    patterns: [
      '1/4 HP SUMP PUMP',
      '1/3 HP SUBMERSIBLE SUMP',
      '1/2 HP SUMP PUMP',
      '3/4 HP SUMP PUMP',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condensate_pump_tubing',
    caseType: 'clear_match',
    expectedNameContains: 'Condensate Pump Tubing',
    riskTags: ['sump_discharge', 'condensate_tubing', 'vinyl_tubing', 'pump'],
    patterns: [
      '3/8 VINYL TUBING CONDENSATE PUMP',
      '3/8 X 50 CONDENSATE TUBING',
      '1/2 X 20 VINYL TUBING COND PUMP',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_male_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Male Adapter',
    riskTags: ['brass_fittings', 'brass', 'male_adapter', 'service_truck'],
    patterns: [
      '1/2 BRASS MALE ADAPTER',
      '3/4 BRS MIP ADPT',
      '1 IN BRASS M ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_female_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Female Adapter',
    riskTags: ['brass_fittings', 'brass', 'female_adapter', 'service_truck'],
    patterns: [
      '1/2 BRASS FEMALE ADAPTER',
      '3/4 BRS FIP ADPT',
      '1 IN BRASS F ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_bushing',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Bushing',
    riskTags: ['brass_fittings', 'brass', 'bushing', 'reducer'],
    patterns: ['3/4 X 1/2 BRASS BUSHING', '1 X 3/4 BRS REDUCING BUSH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_compression_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Compression Adapter',
    riskTags: ['brass_fittings', 'brass', 'compression', 'adapter'],
    patterns: [
      '3/8 BRASS COMPRESSION ADPT',
      '1/2 BRASS COMPRESSION ADAPTER',
      '3/4 BRS COMP ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_compression_union',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Compression Union',
    riskTags: ['brass_fittings', 'brass', 'compression', 'union'],
    patterns: [
      '3/8 BRASS COMPRESSION UNION',
      '1/2 BRS COMP UNION',
      '3/4 BRASS COMPRESSION UNION',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_flare_fitting',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Flare Fitting',
    riskTags: ['brass_fittings', 'brass', 'flare', 'gas'],
    patterns: [
      '3/8 BRASS FLARE FITTING',
      '1/2 BRS FLARE FTG',
      '3/4 GAS FLARE FITTING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_barb_fitting',
    caseType: 'clear_match',
    expectedNameContains: 'Brass Barb Fitting',
    riskTags: ['brass_fittings', 'brass', 'barb', 'hose'],
    patterns: [
      '3/8 BRASS BARB FITTING',
      '1/2 BRS HOSE BARB',
      '3/4 BRASS BARBED FTG',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_support_strap',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Strap',
    riskTags: ['pipe_supports', 'support', 'pipe_strap', 'service_truck'],
    patterns: ['1/2 PIPE STRAP', '3/4 TWO HOLE PIPE STRAP', '1 IN PIPE STRAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_support_split_ring',
    caseType: 'clear_match',
    expectedNameContains: 'Split Ring Hanger',
    riskTags: ['pipe_supports', 'support', 'split_ring', 'hanger'],
    patterns: ['1/2 SPLIT RING HANGER', '3/4 SPLIT RING', '1 IN PIPE HANGER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_support_bell_hanger',
    caseType: 'clear_match',
    expectedNameContains: 'Bell Hanger',
    riskTags: ['pipe_supports', 'support', 'bell_hanger', 'service_truck'],
    patterns: ['1/2 BELL HANGER', '3/4 PIPE BELL HANGER', '1 IN BELL HNGR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_support_stud_guard',
    caseType: 'clear_match',
    expectedNameContains: 'Stud Guard Plate',
    riskTags: ['pipe_supports', 'protection', 'stud_guard', 'nail_plate'],
    patterns: ['1-1/2 X 3 STUD GUARD PLATE', '3 X 5 STUD GUARD', 'NAIL PLATE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_support_insulation',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Insulation',
    riskTags: ['pipe_supports', 'protection', 'pipe_insulation'],
    patterns: [
      '1/2 PIPE INSULATION 6 FT',
      '3/4 PIPE INSULATION',
      '1 IN X 6 FT PIPE INSULATION',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_pvc_ball_valve',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Ball Valve',
    riskTags: ['general_valves', 'valve', 'pvc_ball_valve'],
    patterns: [
      '1/2 PVC BALL VALVE',
      '3/4 PVC BALL VALVE',
      '1 IN PVC SHUTOFF VALVE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_threaded_ball_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Threaded Ball Valve',
    riskTags: ['general_valves', 'valve', 'threaded_ball_valve'],
    patterns: [
      '1/2 THREADED BALL VALVE',
      '3/4 IPS BALL VALVE',
      '1 IN FIP BALL VALVE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_ball_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Ball Valve',
    riskTags: ['general_valves', 'valve', 'ball_valve'],
    patterns: ['1/2 BALL VALVE', '3/4 FULL PORT BALL VALVE', '1 IN BALL VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_gate_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Gate Valve',
    riskTags: ['general_valves', 'valve', 'gate_valve'],
    patterns: ['1/2 GATE VALVE', '3/4 WATER GATE VALVE', '1 IN GATE VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_check_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['general_valves', 'valve', 'check_valve'],
    patterns: ['1/2 CHECK VALVE', '3/4 ONE WAY VALVE', '1 IN CHECK VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_pressure_reducing_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Reducing Valve',
    riskTags: ['general_valves', 'valve', 'prv', 'pressure'],
    patterns: [
      '1/2 PRV',
      '3/4 PRESSURE REDUCING VALVE',
      '1 IN PRESS RED VALVE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_hose_bibb',
    caseType: 'clear_match',
    expectedNameContains: 'Hose Bibb',
    riskTags: ['general_valves', 'valve', 'hose_bibb', 'outside_faucet'],
    patterns: ['1/2 HOSE BIBB', '3/4 HOSE BIB', 'OUTSIDE FAUCET'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_frost_free_sillcock',
    caseType: 'clear_match',
    expectedNameContains: 'Frost-Free Sillcock',
    riskTags: ['general_valves', 'valve', 'sillcock', 'frost_free'],
    patterns: [
      '1/2 X 8 FROST FREE SILLCOCK',
      '3/4 X 10 ANTI SIPHON SILLCOCK',
      '1/2 X 12 FROST FREE SILLCOCK',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_vacuum_breaker',
    caseType: 'clear_match',
    expectedNameContains: 'Vacuum Breaker',
    riskTags: ['general_valves', 'valve', 'vacuum_breaker', 'hose_bibb'],
    patterns: ['HOSE BIBB VAC BRKR', 'VACUUM BREAKER', 'BACKFLOW PREVENTER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'general_hose_bibb_repair',
    caseType: 'clear_match',
    expectedNameContains: 'Hose Bibb Repair Part',
    riskTags: ['general_valves', 'valve', 'hose_bibb_repair'],
    patterns: [
      'HOSE BIBB WASHER',
      'SILLCOCK STEM PACKING',
      'VACUUM BREAKER CAP',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_connector',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater Connector',
    riskTags: ['water_heater_service', 'water_heater', 'connector'],
    patterns: [
      '3/4 FIP WATER HTR CONN 18',
      '3/4 SWEAT X FIP WTR HTR LINE 24',
      'GAS WATER HEATER CONNECTOR 1/2 X 24',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_element',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater Repair Part',
    riskTags: ['water_heater_service', 'water_heater', 'element', 'repair'],
    patterns: [
      '4500 WATT SCREW IN WATER HEATER ELEMENT',
      '5500W WTR HTR ELEMENT',
      'WH ELEMENT 4500W',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_thermostat',
    caseType: 'clear_match',
    expectedNameContains: 'thermostat',
    riskTags: ['water_heater_service', 'water_heater', 'thermostat', 'repair'],
    patterns: [
      'UPPER WATER HEATER THERMOSTAT',
      'LOWER WTR HTR THERMOSTAT',
      'THERMOSTAT AND ELEMENT TUNE UP KIT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_anode_rod',
    caseType: 'clear_match',
    expectedNameContains: 'anode rod',
    riskTags: ['water_heater_service', 'water_heater', 'anode_rod', 'repair'],
    patterns: [
      '24 IN MAGNESIUM WATER HEATER ANODE ROD',
      '42 IN ALUMINUM ZINC WTR HTR ANODE',
      'FLEXIBLE WH ANODE ROD',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_drain_pan',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater Drain Pan',
    riskTags: ['water_heater_service', 'water_heater', 'drain_pan'],
    patterns: [
      '20 IN WATER HEATER DRAIN PAN',
      '24 ALUM WTR HTR PAN W FITTING',
      '26 IN PLASTIC HEATER PAN',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_strap',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater Restraint Strap',
    riskTags: ['water_heater_service', 'water_heater', 'restraint_strap'],
    patterns: [
      'WATER HEATER RESTRAINT STRAP 18',
      'UNIVERSAL WTR HTR STRAP',
      'SEISMIC WATER HEATER STRAP',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_expansion_tank',
    caseType: 'clear_match',
    expectedNameContains: 'Expansion Tank',
    riskTags: ['water_heater_service', 'water_heater', 'expansion_tank'],
    patterns: [
      '2 GAL THERMAL EXPANSION TANK',
      '4.5 GAL WATER HEATER EXP TANK',
      'EXPANSION TANK MOUNTING BRACKET',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_tpr_valve',
    caseType: 'clear_match',
    expectedNameContains: 'relief valve',
    riskTags: ['water_heater_service', 'water_heater', 'tpr', 'relief_valve'],
    patterns: [
      '3/4 T AND P RELIEF VALVE',
      'WATER HEATER TPR VALVE 3/4',
      'TEMP PRESSURE RELIEF VALVE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_drain_valve',
    caseType: 'clear_match',
    expectedNameContains: 'drain valve',
    riskTags: ['water_heater_service', 'water_heater', 'drain_valve'],
    patterns: [
      '3/4 BRASS WATER HEATER DRAIN VALVE',
      'HEATER DRAIN VALVE BALL',
      'BOILER DRAIN WTR HTR',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_dielectric',
    caseType: 'clear_match',
    expectedNameContains: 'dielectric',
    riskTags: ['water_heater_service', 'water_heater', 'dielectric'],
    patterns: [
      '3/4 DIELECTRIC UNION WATER HEATER',
      '3/4 X 2 WATER HEATER DIELECTRIC NIPPLE',
      'DIELECTRIC NIPPLE PAIR',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_service_fitting',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater Service Fitting',
    riskTags: ['water_heater_service', 'water_heater', 'service_fitting'],
    patterns: [
      '3/4 WATER HEATER MIXING VALVE',
      '3/4 WTR HTR UNION',
      'WATER HEATER SERVICE FITTING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_install_accessory',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater Install Accessory',
    riskTags: ['water_heater_service', 'water_heater', 'install_accessory'],
    patterns: [
      '3/4 VACUUM RELIEF VALVE WATER HEATER',
      'GAS SEDIMENT TRAP KIT',
      'WTR HTR INSTALL ACCESSORY',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_thread_sealant',
    caseType: 'clear_match',
    expectedNameContains: 'Thread Sealant Supply',
    riskTags: ['service_consumables_tools', 'thread_sealant', 'consumable'],
    patterns: [
      '8 OZ BLUE THREAD SEALANT',
      '1.5 OZ GAS LINE THREAD SEALANT',
      '4 OZ PTFE PASTE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_pipe_joint_compound',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Joint Compound',
    riskTags: [
      'service_consumables_tools',
      'pipe_joint_compound',
      'consumable',
    ],
    patterns: [
      '4 OZ WHITE PIPE JOINT COMPOUND',
      '8 OZ PIPE DOPE',
      '16 OZ GRAY PIPE JOINT COMPOUND',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_ptfe_tape',
    caseType: 'clear_match',
    expectedNameContains: 'Thread Sealant Supply',
    riskTags: ['service_consumables_tools', 'ptfe_tape', 'consumable'],
    patterns: [
      'WHITE PTFE TAPE',
      'YELLOW GAS PTFE TAPE',
      'PINK WATER LINE PTFE TAPE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_pvc_cement',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Cement',
    riskTags: ['service_consumables_tools', 'pvc_cement', 'consumable'],
    patterns: ['4 OZ PVC CEMENT', '8 OZ PVC GLUE', '16 OZ SOLVENT CEMENT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_pvc_primer',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Primer',
    riskTags: ['service_consumables_tools', 'pvc_primer', 'consumable'],
    patterns: ['4 OZ PVC PRIMER', '8 OZ PURPLE PRIMER', '32 OZ PIPE PRIMER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_plumber_putty',
    caseType: 'clear_match',
    expectedNameContains: 'Plumber Putty',
    riskTags: ['service_consumables_tools', 'putty', 'consumable'],
    patterns: ['14 OZ PLUMBER PUTTY', '32 OZ PLUMBERS PUTTY', '5 LB PUTTY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_pipe_j_hook',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe J-Hook',
    riskTags: ['service_consumables_tools', 'pipe_j_hook', 'hanger'],
    patterns: ['1/2 PIPE J HOOK', '3/4 PIPE J-HOOK', '1-1/2 IN J HOOK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_pex_tool',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'pex_tool', 'tool'],
    patterns: [
      '1/2 PEX CRIMP TOOL',
      'PEX CLAMP CINCH TOOL',
      'PEX EXPANSION TOOL',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_press_jaw',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'press_jaw', 'tool'],
    patterns: [
      '1/2 PROPRESS JAW',
      '3/4 PRESS JAW',
      'COPPER PRESS FITTING TOOL JAW',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_pipe_cutter',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'pipe_cutter', 'tool'],
    patterns: [
      'MINI TUBING CUTTER',
      'RATCHETING PVC PIPE CUTTER',
      'INSIDE PIPE CUTTER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_deburr_reamer',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'deburr_reamer', 'tool'],
    patterns: [
      'PVC DEBURRING TOOL',
      'COPPER PIPE REAMING TOOL',
      'PVC DEBURR TOOL',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_wrench',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'wrench', 'tool'],
    patterns: ['BASIN WRENCH', 'STRAP WRENCH', 'PLUMBING HAND TOOL WRENCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_auger_snake',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'auger_snake', 'tool'],
    patterns: ['CLOSET AUGER', 'HAND DRAIN AUGER', 'SMALL DRAIN SNAKE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_hole_saw',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'hole_saw', 'tool'],
    patterns: [
      '1-1/2 HOLE SAW',
      '2-1/8 IN HOLE SAW',
      '1-1/2 BI-METAL HOLE SAW',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'service_recip_blade',
    caseType: 'clear_match',
    expectedNameContains: 'Plumbing Hand Tool',
    riskTags: ['service_consumables_tools', 'recip_blade', 'tool'],
    patterns: [
      'BI-METAL RECIPROCATING SAW BLADE 6 IN',
      'PVC PLASTIC RECIP SAW BLADE',
      'CARBIDE CAST IRON SAWZALL BLADE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC',
    riskTags: ['cpvc', 'elbow', 'pressure_pipe', 'service_truck'],
    patterns: ['1/2 CPVC 90 ELBOW', '3/4 CPVC 90', '1 IN CPVC ELL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC Coupling',
    riskTags: ['cpvc', 'coupling', 'pressure_pipe', 'service_truck'],
    patterns: ['1/2 CPVC CPLG', '3/4 CPVC COUPLING', '1 IN CPVC COUP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC',
    riskTags: ['cpvc', 'adapter', 'pressure_pipe', 'service_truck'],
    patterns: [
      '1/2 CPVC MALE ADPT',
      '3/4 CPVC FEMALE ADAPTER',
      '1 IN CPVC TRANSITION ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_tee',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC Tee',
    riskTags: ['cpvc', 'tee', 'pressure_pipe', 'service_truck'],
    patterns: ['1/2 CPVC TEE', '3/4 CPVC T', '1 X 3/4 CPVC TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_reducer_bushing',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC Reducer',
    riskTags: ['cpvc', 'reducer', 'bushing', 'pressure_pipe'],
    patterns: ['3/4 X 1/2 CPVC RED BUSH', '1 X 3/4 CPVC REDUCER BUSHING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'Copper',
    riskTags: ['copper', 'elbow', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER 90 ELBOW', '3/4 COPPER 45 ELL', '1 IN COPPER 90'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'Copper Coupling',
    riskTags: ['copper', 'coupling', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER CPLG', '3/4 COPPER COUPLING', '1 IN COPPER COUP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_repair_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'Copper Repair Coupling',
    riskTags: ['copper', 'repair_coupling', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER REPAIR CPLG', '3/4 COPPER SLIP COUPLING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'Copper',
    riskTags: ['copper', 'adapter', 'sweat', 'service_truck'],
    patterns: [
      '1/2 COPPER MALE ADPT',
      '3/4 COPPER FEMALE ADAPTER',
      '1 IN COPPER F ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_tee',
    caseType: 'clear_match',
    expectedNameContains: 'Copper Tee',
    riskTags: ['copper', 'tee', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER TEE', '3/4 COPPER T', '1 X 3/4 COPPER TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_dielectric_union',
    caseType: 'clear_match',
    expectedNameContains: 'Dielectric Union',
    riskTags: ['copper', 'dielectric_union', 'water_heater', 'service_truck'],
    patterns: ['3/4 COPPER DIELECTRIC UNION', '1 IN WATER HEATER UNION'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_bell_hanger',
    caseType: 'clear_match',
    expectedNameContains: 'Bell Hanger',
    riskTags: ['copper', 'bell_hanger', 'support', 'service_truck'],
    patterns: ['1/2 COPPER BELL HANGER', '3/4 BELL HANGER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_angle_stop',
    caseType: 'clear_match',
    expectedNameContains: 'Stop',
    riskTags: ['brass', 'valve', 'angle_stop', 'supply'],
    patterns: ['1/2 X 3/8 BR ANG STOP', '5/8OD X 3/8 COMP STOP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_wax_ring',
    caseType: 'clear_match',
    expectedNameContains: 'Wax',
    riskTags: ['toilet', 'repair', 'seal', 'service_truck'],
    patterns: ['TOILET WAX RING', 'JUMBO WAX RING BOLTS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_fill_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Fill Valve',
    riskTags: ['toilet', 'repair', 'fill_valve', 'service_truck'],
    patterns: ['TOILET FILL VALVE', 'ADJUSTABLE FILL VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_flush_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Flush Valve',
    riskTags: ['toilet_faucet_repair', 'toilet', 'flush_valve'],
    patterns: [
      '2 IN TOILET FLUSH VALVE',
      '3 IN TOILET FLUSH VALVE',
      'TOILET TANK VALVE KIT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_flapper',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Flapper',
    riskTags: ['toilet_faucet_repair', 'toilet', 'flapper'],
    patterns: [
      '2 IN TOILET FLAPPER',
      '3 IN TOILET FLAPPER',
      'UNIVERSAL TOILET FLAPPER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_tank_lever',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Tank Lever',
    riskTags: ['toilet_faucet_repair', 'toilet', 'tank_lever'],
    patterns: ['FRONT MOUNT TOILET TANK LEVER', 'SIDE MOUNT FLUSH LEVER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_tank_bolt_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Tank Bolt Kit',
    riskTags: ['toilet_faucet_repair', 'toilet', 'tank_bolts'],
    patterns: ['HEAVY DUTY TOILET TANK BOLT KIT', 'TANK TO BOWL BOLTS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_tank_seal',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Tank Seal Part',
    riskTags: ['toilet_faucet_repair', 'toilet', 'tank_seal'],
    patterns: [
      '2 IN FLUSH VALVE SEAL',
      'TANK BOLT GASKET',
      'FILL VALVE SHANK WASHER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'closet_flange',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Flange',
    riskTags: ['toilet_faucet_repair', 'toilet', 'closet_flange'],
    patterns: [
      '3 IN TOILET FLANGE',
      '4 IN CLOSET FLANGE',
      'PVC OFFSET CLOSET FLANGE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'closet_flange_repair',
    caseType: 'clear_match',
    expectedNameContains: 'Flange Repair',
    riskTags: ['toilet_faucet_repair', 'toilet', 'closet_flange_repair'],
    patterns: [
      'CLOSET FLANGE REPAIR RING',
      'HALF MOON REPAIR RING',
      'INSIDE FIT REPAIR FLANGE',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'closet_flange_spacer',
    caseType: 'clear_match',
    expectedNameContains: 'flange spacer',
    riskTags: ['toilet_faucet_repair', 'toilet', 'flange_spacer'],
    patterns: ['1/4 IN TOILET FLANGE SPACER', '1/2 IN CLOSET FLANGE SPACER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'closet_bolt_repair',
    caseType: 'clear_match',
    expectedNameContains: 'Closet Bolt Set',
    riskTags: ['toilet_faucet_repair', 'toilet', 'closet_bolts'],
    patterns: [
      'CLOSET BOLT REPAIR KIT',
      'CLOSET BOLT SET',
      'TOILET CLOSET BOLTS',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'closet_seal',
    caseType: 'clear_match',
    expectedNameContains: 'Seal',
    riskTags: ['toilet_faucet_repair', 'toilet', 'closet_seal'],
    patterns: [
      'WAX FREE TOILET SEAL',
      'FOAM CLOSET SEAL',
      'RUBBER CLOSET SEAL',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'faucet_washer_seat',
    caseType: 'clear_match',
    expectedNameContains: 'Faucet Washer and Seat Part',
    riskTags: ['toilet_faucet_repair', 'faucet', 'washer_seat'],
    patterns: [
      '1/4 FLAT FAUCET WASHER',
      '3/8 BEVELED FAUCET WASHER',
      '1/2 SEAT WASHER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'faucet_o_ring_packing',
    caseType: 'clear_match',
    expectedNameContains: 'Faucet O-Ring and Packing Part',
    riskTags: ['toilet_faucet_repair', 'faucet', 'o_ring_packing'],
    patterns: ['1/4 O-RING', '3/8 ROUND O RING', '1/2 STEM PACKING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'faucet_o_ring_seat_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Faucet O-Ring and Seat Kit',
    riskTags: ['toilet_faucet_repair', 'faucet', 'o_ring_seat_kit'],
    patterns: ['ASSORTED FAUCET O-RING AND SEAT KIT', 'O RING AND SEAT KIT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'faucet_cartridge',
    caseType: 'clear_match',
    expectedNameContains: 'Faucet',
    riskTags: ['toilet_faucet_repair', 'faucet', 'cartridge'],
    patterns: [
      'HOT STEM FAUCET CARTRIDGE',
      'COLD STEM CARTRIDGE',
      'FAUCET STEM',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'faucet_repair_assortment',
    caseType: 'clear_match',
    expectedNameContains: 'Faucet Repair Assortment',
    riskTags: ['toilet_faucet_repair', 'faucet', 'repair_assortment'],
    patterns: [
      'SEAT WASHER ASSORTMENT 10 PACK',
      'CARTRIDGE CLIP ASSORTMENT',
      'BONNET NUT ASSORTMENT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'faucet_aerator',
    caseType: 'clear_match',
    expectedNameContains: 'Faucet Aerator',
    riskTags: ['toilet_faucet_repair', 'faucet', 'aerator'],
    patterns: [
      '15/16-27 MALE FAUCET AERATOR',
      '55/64-27 FEMALE AERATOR',
      '13/16-27 MALE CHROME 1.5 GPM AERATOR',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lavatory_pop_up',
    caseType: 'clear_match',
    expectedNameContains: 'Lavatory Pop-Up Assembly',
    riskTags: ['toilet_faucet_repair', 'faucet', 'pop_up'],
    patterns: ['CHROME LAVATORY POP UP', 'BRUSHED NICKEL POP-UP ASSEMBLY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'kitchen_basket_strainer_repair',
    caseType: 'clear_match',
    expectedNameContains: 'Kitchen Sink Basket Strainer',
    riskTags: ['toilet_faucet_repair', 'sink', 'basket_strainer'],
    patterns: [
      'CHROME KITCHEN SINK BASKET STRAINER',
      'DEEP CUP BASKET STRAINER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sink_repair_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Sink Repair Kit',
    riskTags: ['toilet_faucet_repair', 'sink', 'repair_kit'],
    patterns: ['KITCHEN SINK REPAIR KIT', 'BATH SINK REPAIR KIT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_finish_trim',
    caseType: 'clear_match',
    expectedNameContains: 'Toilet Finish Trim Part',
    riskTags: ['toilet_faucet_repair', 'toilet', 'finish_trim'],
    patterns: [
      'CHROME CLOSET BOLT CAPS',
      'BRUSHED NICKEL HINGE BOLT CAPS',
      'TOILET FINISH TRIM NUT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lavatory_p_trap',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['drainage', 'tubular', 'service_truck'],
    patterns: ['1-1/4 LAV P TRAP', '1-1/2 P-TRAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tubular_tailpiece',
    caseType: 'clear_match',
    expectedNameContains: 'Tailpiece',
    riskTags: ['drainage', 'tubular', 'tailpiece', 'service_truck'],
    patterns: ['1-1/2 TAILPIECE', '1-1/4 LAV TAILPIECE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tubular_extension_tube',
    caseType: 'clear_match',
    expectedNameContains: 'Extension Tube',
    riskTags: ['drainage', 'tubular', 'extension_tube', 'service_truck'],
    patterns: ['1-1/2 EXTENSION TUBE', '1-1/4 TUBULAR EXT TUBE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'slip_joint_nut_washer',
    caseType: 'clear_match',
    expectedNameContains: 'Slip Joint',
    riskTags: ['drainage', 'tubular', 'slip_joint', 'service_truck'],
    patterns: ['1-1/2 SLIP JOINT NUT WASHER', '1-1/4 SJ NUT WASHER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'beveled_washer_pack',
    caseType: 'clear_match',
    expectedNameContains: 'beveled washers',
    riskTags: ['drainage', 'tubular', 'washer', 'service_truck'],
    patterns: ['1-1/2 BEVELED WASHER 5PK', '1-1/4 SLIP WASHER 2PK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'basket_strainer',
    caseType: 'clear_match',
    expectedNameContains: 'Basket Strainer',
    riskTags: ['drainage', 'tubular', 'basket_strainer', 'service_truck'],
    patterns: ['KITCHEN BASKET STRAINER', 'STAINLESS BASKET STRAINER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_j_bend',
    caseType: 'clear_match',
    expectedNameContains: 'J-bend',
    riskTags: ['drainage', 'tubular', 'j_bend', 'service_truck'],
    patterns: ['1-1/2 BRASS J BEND', '1-1/4 CHROME J-BEND'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'flanged_tailpiece',
    caseType: 'clear_match',
    expectedNameContains: 'flanged tailpiece',
    riskTags: ['drainage', 'tubular', 'tailpiece', 'service_truck'],
    patterns: ['1-1/2 FLANGED TAILPIECE', '1-1/4 FLANGE TAIL PIECE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'compression_trap_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'compression trap adapter',
    riskTags: [
      'legacy_repair',
      'compression_trap',
      'transition',
      'service_truck',
    ],
    patterns: ['1-1/2 COMPRESSION TRAP ADAPTER', '2 IN COMP TRAP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'desanco_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'desanco adapter',
    riskTags: ['legacy_repair', 'desanco', 'transition', 'service_truck'],
    patterns: ['1-1/2 DESANCO ADAPTER', '1-1/4 DESANCO TRAP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'marvel_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'marvel adapter',
    riskTags: ['legacy_repair', 'marvel', 'transition', 'service_truck'],
    patterns: ['1-1/2 MARVEL ADAPTER', '2 IN MARVEL TRAP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'wall_bend_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'wall bend',
    riskTags: ['legacy_repair', 'wall_bend', 'transition', 'service_truck'],
    patterns: ['1-1/2 WALL BEND ADAPTER', '1-1/4 WALL BEND'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'trap_arm_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'trap arm',
    riskTags: ['legacy_repair', 'trap_arm', 'transition', 'service_truck'],
    patterns: ['1-1/2 TRAP ARM ADAPTER', '2 IN TRAP ARM'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'braided_faucet_supply',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['faucet', 'supply_line', 'service_truck'],
    patterns: ['3/8 X 16 FAUCET CONN', 'LAV SUPPLY 3/8 X 20'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_softener_salt',
    caseType: 'clear_match',
    expectedNameContains: 'water softener salt',
    riskTags: ['water_treatment', 'softener', 'salt', 'service_truck'],
    patterns: ['40LB WATER SOFTENER SALT', '25 LB SOFTENER SALT PELLETS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'well_pressure_switch',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Switch',
    riskTags: ['well', 'pump', 'pressure_switch', 'service_truck'],
    patterns: ['30/50 WELL PRESS SWITCH', '40/60 PUMP PRESS SW'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'well_check_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['well', 'pump', 'check_valve', 'service_truck'],
    patterns: ['1 IN WELL CHECK VALVE', '3/4 PUMP CHECK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'threaded_rod',
    caseType: 'clear_match',
    expectedNameContains: 'Threaded Rod',
    riskTags: ['fastener', 'threaded_rod', 'hanger_support'],
    patterns: ['3/8 ALL THREAD ROD', '1/2 THREADED ROD ZINC'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_pvc_elbow',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['dangerous_word', 'pvc', 'cross_trade', 'needs_review'],
    patterns: ['PVC EL 3/4', 'PVC 90 1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_generic_adapter',
    caseType: 'dangerous_generic',
    expectedTrade: '',
    expectedNameContains: '',
    expectUnknown: true,
    maxConfidence: .78,
    riskTags: ['dangerous_word', 'adapter', 'cross_trade', 'needs_review'],
    patterns: ['ADAPTER 3/4', 'ADPT 1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'receipt_noise_totals',
    caseType: 'receipt_noise',
    expectedTrade: '',
    expectedNameContains: 'noise',
    expectUnknown: true,
    maxConfidence: .20,
    riskTags: ['noise_line', 'receipt_totals', 'needs_review'],
    patterns: ['SUBTOTAL 18.42', 'VISA APPROVED 9001'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'negative_match_cleanup',
    caseType: 'negative_match',
    expectedTrade: '',
    expectedNameContains: '',
    expectUnknown: true,
    maxConfidence: .18,
    riskTags: ['negative_match', 'cleanup', 'non_inventory'],
    patterns: ['SHOP TOWELS 6PK', 'TRASH BAGS 30GAL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'quantity_price_copper_coupling',
    caseType: 'quantity_price',
    expectedNameContains: 'Copper Coupling',
    riskTags: ['quantity', 'price', 'copper', 'coupling', 'service_fitting'],
    patterns: ['1/2 COP CPL', '3/4 COP CPL'],
  ),
];

const spanishPlumbingCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'codo_pex',
    caseType: 'clear_match',
    expectedNameContains: 'PEX',
    riskTags: ['spanish', 'pex', 'codo', 'size', 'generated_batch'],
    patterns: ['1/2 CODO PEX 90', '3/4 CODO PEX LATON'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'acople_pvc',
    caseType: 'clear_match',
    expectedNameContains: 'PVC',
    riskTags: ['spanish', 'pvc', 'coupling', 'size'],
    patterns: ['3/4 ACOPLE PVC CED40', '1 ACOPLE PVC SCH40'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_angulo',
    caseType: 'clear_match',
    expectedNameContains: 'Stop',
    riskTags: ['spanish', 'valve', 'angle_stop', 'supply'],
    patterns: ['1/2 X 3/8 VALVULA ANGULO', 'LLAVE ANGULAR 1/2 X 3/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'varilla_roscada',
    caseType: 'clear_match',
    expectedNameContains: 'Threaded Rod',
    riskTags: ['spanish', 'fastener', 'threaded_rod'],
    patterns: ['3/8 VARILLA ROSCADA', '1/2 VARILLA TODO ROSCA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_llenado_sanitario',
    caseType: 'clear_match',
    expectedNameContains: 'Fill Valve',
    riskTags: ['spanish', 'toilet', 'fill_valve', 'service_truck'],
    patterns: ['VALVULA LLENADO SANITARIO', 'FILL VALVE SANITARIO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'trampa_lavamanos',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['spanish', 'drainage', 'tubular', 'service_truck'],
    patterns: ['TRAMPA LAVAMANOS 1-1/4', 'P TRAP 1-1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'linea_lavamanos',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['spanish', 'faucet', 'supply_line', 'service_truck'],
    patterns: ['LINEA LAVAMANOS 3/8 X 16', 'CONECTOR GRIFO 3/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sal_suavizador',
    caseType: 'clear_match',
    expectedNameContains: 'water softener salt',
    riskTags: ['spanish', 'water_treatment', 'softener', 'salt'],
    patterns: ['SAL SUAVIZADOR 40LB', 'SAL ABLANDADOR 25 LB'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'switch_presion_pozo',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Switch',
    riskTags: ['spanish', 'well', 'pump', 'pressure_switch'],
    patterns: ['SWITCH PRESION POZO 30/50', 'INTERRUPTOR BOMBA 40/60'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_check_pozo',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['spanish', 'well', 'pump', 'check_valve'],
    patterns: ['VALVULA CHECK POZO 1 IN', 'CHECK BOMBA 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'generico_pvc',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['spanish', 'dangerous_word', 'pvc', 'needs_review'],
    patterns: ['PVC CODO', 'PVC 90'],
  ),
];

const englishPlumbingStandardRecipes = [
  ...englishPlumbingCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'closet_bolt_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Closet Bolt',
    riskTags: ['toilet', 'bolt', 'repair', 'standard_pack', 'generated_batch'],
    patterns: ['CLOSET BOLT KIT', 'TOILET BOLTS 5/16'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_supply_line',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['toilet', 'supply_line', 'connector', 'standard_pack'],
    patterns: ['TOILET CONN 3/8 X 12', 'TOILET SUPPLY 3/8 X 16'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hose_bibb',
    caseType: 'clear_match',
    expectedNameContains: 'Hose Bibb',
    riskTags: ['valve', 'outside_faucet', 'standard_pack'],
    patterns: ['1/2 HOSE BIBB', '3/4 OUTSIDE FAUCET'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_cement_primer',
    caseType: 'clear_match',
    expectedNameContains: 'PVC',
    riskTags: ['consumable', 'cement', 'primer', 'dangerous_word'],
    patterns: ['8 OZ PVC CEMENT', 'PURPLE PRIMER 16 OZ'],
  ),
];

const spanishPlumbingStandardRecipes = [
  ...spanishPlumbingCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'perno_sanitario',
    caseType: 'clear_match',
    expectedNameContains: 'Closet Bolt',
    riskTags: ['spanish', 'toilet', 'bolt', 'standard_pack', 'generated_batch'],
    patterns: ['PERNO SANITARIO', 'TORNILLO SANITARIO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'linea_sanitario',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['spanish', 'toilet', 'supply_line', 'standard_pack'],
    patterns: ['LINEA SUMINISTRO SANITARIO', 'CONECTOR SANITARIO 3/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'llave_manguera',
    caseType: 'clear_match',
    expectedNameContains: 'Sillcock',
    riskTags: ['spanish', 'valve', 'outside_faucet', 'standard_pack'],
    patterns: ['LLAVE MANGUERA 1/2', 'GRIFO EXTERIOR 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cemento_primer',
    caseType: 'clear_match',
    expectedNameContains: 'PVC',
    riskTags: ['spanish', 'consumable', 'cement', 'primer'],
    patterns: ['CEMENTO PVC 8 OZ', 'PRIMER MORADO 16 OZ'],
  ),
];

const englishPlumbingProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'tubular_p_trap',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['drainage', 'tubular', 'professional_pack'],
    patterns: ['1-1/2 P-TRAP', '1-1/4 TUBULAR P TRAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'disposal_install_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Disposal',
    riskTags: ['drainage', 'kitchen', 'professional_pack'],
    patterns: ['DISPOSAL KIT', 'DISPOSAL CONN KIT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_connector',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater',
    riskTags: ['water_heater', 'connector', 'professional_pack'],
    patterns: ['3/4 WATER HTR CONN', 'WTR HTR LINE 24'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_check_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['pump', 'sump', 'professional_pack'],
    patterns: ['1-1/2 SUMP CHECK', 'PUMP CHECK VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'vacuum_breaker',
    caseType: 'clear_match',
    expectedNameContains: 'Vacuum Breaker',
    riskTags: ['valve', 'hose_bibb', 'professional_pack'],
    patterns: ['HOSE BIBB VAC BRKR', 'VACUUM BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'washer_hose',
    caseType: 'clear_match',
    expectedNameContains: 'Washing Machine Hose',
    riskTags: ['supply_line', 'appliance', 'professional_pack'],
    patterns: ['WASHER HOSE 6FT', 'LAUNDRY HOSE PAIR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_strap',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Strap',
    riskTags: ['fastener', 'support', 'professional_pack'],
    patterns: ['3/4 PIPE STRAP', '1/2 2 HOLE STRAP'],
  ),
  ...englishPlumbingStandardRecipes,
];

const englishPlumbingCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'cleanout_part',
    caseType: 'clear_match',
    expectedNameContains: 'Cleanout',
    riskTags: ['drainage', 'cleanout', 'complete_pack'],
    patterns: ['2 CLEANOUT PLUG', '3 CLEANOUT COVER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lav_pop_up',
    caseType: 'clear_match',
    expectedNameContains: 'Pop-Up',
    riskTags: ['drainage', 'lavatory', 'complete_pack'],
    patterns: ['LAV POP UP', 'POP UP DRAIN 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'slip_joint_nut',
    caseType: 'clear_match',
    expectedNameContains: 'Slip Joint',
    riskTags: ['drainage', 'tubular', 'complete_pack'],
    patterns: ['1-1/2 SLIP JOINT NUT', '1-1/4 NUT WASHER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'gas_connector',
    caseType: 'clear_match',
    expectedNameContains: 'Gas Appliance Connector',
    riskTags: ['gas', 'connector', 'complete_pack'],
    patterns: ['1/2 GAS CONNECTOR', 'GAS APPLIANCE CONN 36'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pressure_reducing_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Reducing Valve',
    riskTags: ['valve', 'pressure', 'complete_pack'],
    patterns: ['3/4 PRV', 'PRESS REDUCING VALVE 1IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ice_maker_line',
    caseType: 'clear_match',
    expectedNameContains: 'Ice Maker Supply Line',
    riskTags: ['supply_line', 'appliance', 'complete_pack'],
    patterns: ['ICE MAKER LINE 25FT', 'FRIDGE WATER LINE 10FT'],
  ),
  ...englishPlumbingProfessionalRecipes,
];

const spanishPlumbingProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'trampa_p',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['spanish', 'drainage', 'professional_pack'],
    patterns: ['TRAMPA P 1-1/2', 'P TRAP 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'kit_triturador',
    caseType: 'clear_match',
    expectedNameContains: 'Disposal',
    riskTags: ['spanish', 'drainage', 'professional_pack'],
    patterns: ['KIT TRITURADOR', 'CONECTOR DISPOSAL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_calentador',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater',
    riskTags: ['spanish', 'water_heater', 'professional_pack'],
    patterns: ['CONECTOR CALENTADOR 3/4', 'LINEA CALENTADOR 24'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_bomba',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['spanish', 'pump', 'professional_pack'],
    patterns: ['VALVULA CHECK BOMBA', 'SUMP CHECK 1-1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'rompedor_vacio',
    caseType: 'clear_match',
    expectedNameContains: 'Vacuum Breaker',
    riskTags: ['spanish', 'valve', 'professional_pack'],
    patterns: ['ROMPEDOR VACIO', 'VACUUM BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'manguera_lavadora',
    caseType: 'clear_match',
    expectedNameContains: 'Washing Machine Hose',
    riskTags: ['spanish', 'supply_line', 'professional_pack'],
    patterns: ['MANGUERA LAVADORA 6FT', 'MANGUERA LAVANDERIA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'abrazadera_tubo',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Strap',
    riskTags: ['spanish', 'fastener', 'professional_pack'],
    patterns: ['ABRAZADERA TUBO 3/4', 'SOPORTE TUBO 1/2'],
  ),
  ...spanishPlumbingStandardRecipes,
];

const spanishPlumbingCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'tapon_limpieza',
    caseType: 'clear_match',
    expectedNameContains: 'Cleanout',
    riskTags: ['spanish', 'drainage', 'cleanout', 'complete_pack'],
    patterns: ['TAPON CLEANOUT 2', 'CUBIERTA CLEANOUT 3'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'drenaje_pop_up',
    caseType: 'clear_match',
    expectedNameContains: 'Pop-Up',
    riskTags: ['spanish', 'drainage', 'lavatory', 'complete_pack'],
    patterns: ['LAV POP UP DRENAJE', 'DRENAJE POP UP 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tuerca_slip_joint',
    caseType: 'clear_match',
    expectedNameContains: 'Slip Joint',
    riskTags: ['spanish', 'drainage', 'tubular', 'complete_pack'],
    patterns: ['TUERCA SLIP JOINT 1-1/2', 'NUT WASHER 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_gas',
    caseType: 'clear_match',
    expectedNameContains: 'Gas Appliance Connector',
    riskTags: ['spanish', 'gas', 'connector', 'complete_pack'],
    patterns: ['CONECTOR GAS 1/2', 'GAS APPLIANCE CONN 36'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_prv',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Reducing Valve',
    riskTags: ['spanish', 'valve', 'pressure', 'complete_pack'],
    patterns: ['VALVULA PRV 3/4', 'PRESS REDUCING VALVE 1IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'linea_hielera',
    caseType: 'clear_match',
    expectedNameContains: 'Ice Maker Supply Line',
    riskTags: ['spanish', 'supply_line', 'appliance', 'complete_pack'],
    patterns: ['LINEA ICE MAKER 25FT', 'FRIDGE WATER LINE 10FT'],
  ),
  ...spanishPlumbingProfessionalRecipes,
];

const englishElectricalCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'old_work_box',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Old Work',
    tradeScope: 'Electrical',
    riskTags: [
      'electrical',
      'box',
      'old_work',
      'dangerous_word',
      'generated_batch',
    ],
    patterns: ['1G OLD WORK BOX', '2G REMOD BOX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'nm_b_wire',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'NM-B',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'wire', 'romex', 'size'],
    patterns: ['12/2 NM-B WIRE', '14/2 ROMEX 25FT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'emt_connector',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'EMT',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'emt', 'connector', 'conduit'],
    patterns: ['1/2 EMT SS CONN', '3/4 EMT CONNECTOR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'wire_nut',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wire Connector',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'connector', 'wire_nut'],
    patterns: ['YEL WIRE NUT', 'RED TWIST CONN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'gfci_receptacle',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'GFCI',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'gfci', 'service_truck'],
    patterns: ['15A GFCI RECPT WHITE', '20 AMP GFI OUTLET'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'single_pole_breaker',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Breaker',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'breaker', 'panel', 'service_truck'],
    patterns: ['20A 1P BRKR', '15 AMP CIRCUIT BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'electrical_tape',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Electrical Tape',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'tape', 'dangerous_word', 'service_truck'],
    patterns: ['3/4 ELEC TAPE BLACK', '1IN ELECTRICAL TAPE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lever_connector',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Lever Connector',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'connector', 'lever_connector', 'service_truck'],
    patterns: ['3 PORT LEVER CONNECTOR', '2 PORT LEVER WIRE CONN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'anti_short_bushing',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Anti Short Bushing',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'bushing', 'mc', 'service_truck'],
    patterns: ['MC ANTI SHORT BUSHING', '100PK ANTI SHORT BUSH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toggle_switch',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'switch', 'service_truck'],
    patterns: ['SP TOGGLE SWITCH', '3WAY WALL SWITCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'decorator_wall_plate',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wall Plate',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'plate', 'trim_out', 'service_truck'],
    patterns: ['1G DECORA WALL PLATE', '2 GANG DECORATOR PLATE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_pvc_conduit',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['electrical', 'dangerous_word', 'pvc', 'cross_trade'],
    patterns: ['PVC COND 3/4', '3/4 PVC CPLG'],
  ),
];

const spanishElectricalCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'caja_remodelacion',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Old Work',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'box', 'generated_batch'],
    patterns: ['CAJA REMODEL 1G', 'CAJA ELECTRICA 2G'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cable_nm_b',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'NM-B',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'wire'],
    patterns: ['CABLE 12/2 NM-B', 'CABLE ROMEX 14/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_emt',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'EMT',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'emt'],
    patterns: ['CONECTOR EMT 1/2', 'CONECTOR EMT 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tuerca_cable',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wire Connector',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'wire_nut'],
    patterns: ['CONECTOR CABLE AMARILLO', 'WIRE NUT ROJO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'receptaculo_gfci',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'GFCI',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'device', 'gfci'],
    patterns: ['15A RECEPTACULO GFCI', '20A TOMACORRIENTE GFI'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'breaker_un_polo',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Breaker',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'breaker'],
    patterns: ['BREAKER UN POLO 20A', 'DISYUNTOR 1P 15A'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cinta_electrica',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Electrical Tape',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'tape'],
    patterns: ['CINTA ELECTRICA 3/4', 'CINTA AISLANTE NEGRA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_palanca',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Lever Connector',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'lever_connector'],
    patterns: ['CONECTOR PALANCA 3 PUERTOS', 'CONECTOR DE PALANCA 2P'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'bushing_anti_corto',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Anti Short Bushing',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'bushing'],
    patterns: ['BUSHING ANTI CORTO MC', 'ANTI CORTO 100PK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'interruptor_toggle',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'switch'],
    patterns: ['INTERRUPTOR TOGGLE SP', 'INTERRUPTOR 3WAY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'placa_decorador',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wall Plate',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'plate'],
    patterns: ['PLACA DECORA 1G', 'PLACA DECORADOR 2 GANG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_conducto_generico',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['spanish', 'electrical', 'dangerous_word', 'pvc'],
    patterns: ['PVC COND 3/4', 'ACOPLE PVC 3/4'],
  ),
];

const englishElectricalStandardRecipes = [
  ...englishElectricalCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'romex_staple',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Cable Staple',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'fastener', 'staple', 'standard_pack'],
    patterns: ['1/2 ROMEX STAPLE', '3/4 CABLE STAPLE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ground_clamp',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'grounding', 'clamp', 'standard_pack'],
    patterns: ['5/8 GROUND CLAMP', 'GRD ROD CLAMP 1/2'],
  ),
];

const englishElectricalProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'double_pole_breaker',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Double-Pole',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'breaker', 'professional_pack'],
    patterns: ['30A 2P BRKR', '50 AMP DOUBLE POLE BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'afci_breaker',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'AFCI',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'breaker', 'afci', 'professional_pack'],
    patterns: ['20A AFCI BRKR', '15 AMP ARC FAULT BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toggle_switch',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'switch', 'professional_pack'],
    patterns: ['SP TOGGLE SWITCH', '3WAY WALL SWITCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dimmer_switch',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Dimmer',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'dimmer', 'professional_pack'],
    patterns: ['LED DIMMER SWITCH', '3WAY LED DIMMER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'junction_box',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Junction Box',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'box', 'junction', 'professional_pack'],
    patterns: ['4IN SQ J BOX', '4-11/16 JUNCTION BOX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ground_rod',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground Rod',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'grounding', 'professional_pack'],
    patterns: ['5/8 GROUND ROD 8FT', '1/2 GRD ROD 8FT'],
  ),
  ...englishElectricalStandardRecipes,
];

const spanishElectricalStandardRecipes = [
  ...spanishElectricalCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'grapa_romex',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Cable Staple',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'fastener', 'standard_pack'],
    patterns: ['GRAPA ROMEX 1/2', 'GRAPA CABLE 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'abrazadera_tierra',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'grounding', 'standard_pack'],
    patterns: ['ABRAZADERA TIERRA 5/8', 'CLAMP TIERRA 1/2'],
  ),
];

const spanishElectricalProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'breaker_doble',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Double-Pole',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'breaker', 'professional_pack'],
    patterns: ['30A BREAKER 2P', '50 AMP DOUBLE POLE BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'breaker_afci',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'AFCI',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'breaker', 'professional_pack'],
    patterns: ['20A BREAKER AFCI', '15 AMP ARC FAULT BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'interruptor_toggle',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'switch', 'professional_pack'],
    patterns: ['INTERRUPTOR TOGGLE SP', 'INTERRUPTOR 3WAY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dimmer_led',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Dimmer',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'dimmer', 'professional_pack'],
    patterns: ['DIMMER LED', 'INTERRUPTOR DIMMER 3WAY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'caja_junction',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Junction Box',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'box', 'professional_pack'],
    patterns: ['CAJA JUNCTION 4IN', 'CAJA J BOX 4-11/16'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'varilla_tierra',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground Rod',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'grounding', 'professional_pack'],
    patterns: ['VARILLA TIERRA 5/8 8FT', 'GROUND ROD 1/2 8FT'],
  ),
  ...spanishElectricalStandardRecipes,
];

const englishHvacCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'pleated_filter',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Air Filter',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'filter', 'dangerous_word', 'size', 'generated_batch'],
    patterns: ['20X25X1 AIR FILTER', '16X20X1 FURNACE FILTER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'foil_tape',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Foil Tape',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'tape', 'foil', 'dangerous_word'],
    patterns: ['2IN FOIL TAPE', '3 HVAC TAPE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sheet_metal_screw',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Sheet Metal Screw',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'fastener', 'sheet_metal_screw'],
    patterns: ['#8 X 1/2 ZIP SCREW', '#10 X 1 SHEET MTL SCR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condensate_coupling',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'pvc', 'cross_trade'],
    patterns: ['3/4 COND PVC CPLG', '1 PVC DRAIN COUP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dual_run_capacitor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Capacitor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'capacitor', 'controls', 'service_truck'],
    patterns: ['35/5 DUAL RUN CAP', '40/5 440V CAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hvac_contactor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Contactor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'contactor', 'controls', 'service_truck'],
    patterns: ['30A 2P CONTACTOR', '40 AMP HVAC CONTACTOR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condensate_pump',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate Pump',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'pump', 'service_truck'],
    patterns: ['115V COND PUMP', 'CONDENSATE PUMP 230V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pan_tabs',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Drain Tablets',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'treatment', 'service_truck'],
    patterns: ['PAN TABS', 'COND DRAIN TABS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'flex_duct',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flex Duct',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'duct', 'airflow', 'service_truck'],
    patterns: ['6IN R6 FLEX DUCT', '8 IN INS FLEX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'start_collar',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Duct Takeoff',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'duct', 'takeoff', 'service_truck'],
    patterns: ['6IN START COLLAR', '8 IN DUCT TAKEOFF'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'flame_sensor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flame Sensor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'flame_sensor', 'service_truck'],
    patterns: ['UNIV FLAME SENSOR', 'STRAIGHT FLAME ROD'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hot_surface_ignitor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Ignitor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'ignitor', 'service_truck'],
    patterns: ['UNIV HSI IGNITOR', '120V HOT SURF IGN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'thermostat_wire',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Thermostat Wire',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'low_voltage', 'thermostat_wire', 'service_truck'],
    patterns: ['18/5 STAT WIRE', '18/8 TSTAT WIRE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'humidifier_water_panel',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Humidifier',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'humidifier', 'iaq', 'service_truck'],
    patterns: ['MODEL 10 HUMIDIFIER PAD', 'MODEL 35 WATER PANEL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_filter',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['hvac', 'dangerous_word', 'filter', 'cross_trade'],
    patterns: ['FILTER', '20X25X1 FILTER'],
  ),
];

const spanishHvacCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'filtro_aire',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Air Filter',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'filter', 'generated_batch'],
    patterns: ['FILTRO AIRE 20X25X1', 'FILTRO HVAC 16X20X1'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cinta_aluminio',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Foil Tape',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'tape'],
    patterns: ['CINTA ALUMINIO 2IN', 'CINTA HVAC 3IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tornillo_lamina',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Sheet Metal Screw',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'fastener'],
    patterns: ['TORNILLO LAMINA #8', 'TORNILLO METAL #10'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'acople_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate', 'pvc'],
    patterns: ['ACOPLE PVC COND 3/4', 'ACOPLE DRENAJE PVC 1'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'capacitor_doble',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Capacitor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'capacitor'],
    patterns: ['35/5 CAPACITOR DOBLE', '40/5 CAP 440V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'contactor_hvac',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Contactor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'contactor'],
    patterns: ['CONTACTOR HVAC 30A', 'CONTACTOR 2P 40A'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'bomba_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate Pump',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate', 'pump'],
    patterns: ['BOMBA CONDENSADO 115V', 'BOMBA COND 230V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pastillas_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Drain Tablets',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate'],
    patterns: ['PASTILLAS BANDEJA', 'TABLETAS DRENAJE COND'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ducto_flexible',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flex Duct',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'duct'],
    patterns: ['DUCTO FLEX 6IN R6', 'FLEX AISLADO 8IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'collarin_arranque',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Duct Takeoff',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'duct'],
    patterns: ['COLLARIN ARRANQUE 6IN', 'TOMA DUCTO 8IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sensor_flama',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flame Sensor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'furnace'],
    patterns: ['SENSOR FLAMA UNIV', 'VARILLA FLAMA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ignitor_hsi',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Ignitor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'ignitor'],
    patterns: ['IGNITOR HSI UNIV', 'IGNITOR SUPERFICIE 120V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cable_termostato',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Thermostat Wire',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'thermostat_wire'],
    patterns: ['CABLE TERMOSTATO 18/5', 'CABLE TSTAT 18/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'panel_humidificador',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Humidifier',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'humidifier', 'iaq'],
    patterns: ['PANEL HUMIDIFICADOR MODELO 10', 'PAD HUMIDIFICADOR MODELO 35'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'filtro_generico',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['spanish', 'hvac', 'dangerous_word', 'filter'],
    patterns: ['FILTRO', 'FILTRO 20X25X1'],
  ),
];

const englishHvacStandardRecipes = [...englishHvacCoreRecipes];

const spanishHvacStandardRecipes = [...spanishHvacCoreRecipes];
