import 'dart:convert';
import 'dart:io';

import 'work_supply_catalog_blueprint_electrical_complete.dart';
import 'work_supply_catalog_blueprint_hvac_complete.dart';
import 'work_supply_catalog_blueprint_hvac_tiers.dart';
import 'work_supply_catalog_blueprint_model.dart';

const _usage =
    'dart run tool/work_supply_catalog_blueprint_generator.dart '
    '[--trade plumbing] [--scope residential] [--tier core] '
    '[--locale en-US] [--limit 500] [--output-dir build/parser_qa_blueprints]';

Future<void> main(List<String> args) async {
  final exit = await runWorkSupplyCatalogBlueprintGenerator(
    args,
    stdout: stdout,
    stderr: stderr,
  );
  if (exit != 0) exitCode = exit;
}

Future<int> runWorkSupplyCatalogBlueprintGenerator(
  List<String> args, {
  required IOSink stdout,
  required IOSink stderr,
}) async {
  if (args.contains('--help') || args.contains('-h')) {
    stdout.writeln(_usage);
    return 0;
  }
  final options = _BlueprintOptions.parse(args);
  if (options.limit <= 0) {
    stderr.writeln('--limit must be greater than zero.');
    return 64;
  }
  final families = _familiesFor(options);
  if (families.isEmpty) {
    stderr.writeln(
      'No catalog blueprint families matched trade=${options.trade} '
      'scope=${options.scope} tier=${options.tier} locale=${options.locale}.',
    );
    return 65;
  }

  final blueprints = _buildBlueprints(options: options, families: families);
  final outputDir = Directory(
    '${options.outputDir}/work_supply_catalog/${options.trade}/'
    '${options.scope}/${options.tier}/${options.locale}',
  )..createSync(recursive: true);
  final blueprintPath = '${outputDir.path}/item_blueprints.json';
  final manifestPath = '${outputDir.path}/manifest.json';
  File(blueprintPath).writeAsStringSync(
    const JsonEncoder.withIndent('  ').convert(blueprints),
    flush: true,
  );
  File(manifestPath).writeAsStringSync(
    const JsonEncoder.withIndent('  ').convert({
      'schemaVersion': 1,
      'generator': 'work_supply_catalog_blueprint_generator',
      'generationSeed': options.seed,
      'trade': options.trade,
      'marketScope': options.scope,
      'tier': options.tier,
      'localePackId': options.locale,
      'requestedLimit': options.limit,
      'generatedCount': blueprints.length,
      'blueprintPath': blueprintPath,
      'promotionMode': 'review-required',
      'writesProductionCatalog': false,
      'liveServicesAllowed': false,
      'firebaseWritesAllowed': false,
      'families': _unique(blueprints, 'itemFamily'),
    }),
    flush: true,
  );

  stdout.writeln(
    'QA_CATALOG_BLUEPRINTS blueprints=$blueprintPath '
    'manifest=$manifestPath count=${blueprints.length} seed=${options.seed}',
  );
  return 0;
}

List<Map<String, Object?>> _buildBlueprints({
  required _BlueprintOptions options,
  required List<CatalogFamily> families,
}) {
  final blueprints = <Map<String, Object?>>[];
  var index = 0;
  while (blueprints.length < options.limit) {
    final family = families[index % families.length];
    final size = family.sizes[index % family.sizes.length];
    final id = [
      'qa',
      options.trade,
      options.scope,
      options.tier,
      family.slug,
      size.replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_'),
      blueprints.length.toString().padLeft(5, '0'),
    ].join('_').toUpperCase();
    blueprints.add({
      'id': id,
      'canonicalName': family.nameFor(size),
      'trade': _tradeLabel(options.trade),
      'marketScopes': [options.scope],
      'packTier': options.tier,
      'localePackId': options.locale,
      'category': family.category,
      'system': family.system,
      'itemType': family.itemType,
      'itemFamily': family.slug,
      'material': family.material,
      'size': size,
      'unit': family.unit,
      'aliases': family.aliasesFor(size),
      'receiptPatterns': family.receiptPatternsFor(size),
      'negativeMatchTokens': family.negativeTokens,
      'highImportanceTokens': [size, family.material, family.itemType],
      'classification': {
        'inventoryCategory': family.category,
        'expenseCategory': 'materials',
        'jobMaterialCategory': family.category,
        'billableMaterial': true,
      },
      'sourceType': 'synthetic-blueprint',
      'sourceOwner': 'Mainteniac QA generator',
      'sourceConfidence': 'generated-needs-review',
      'verifiedManually': false,
      'autoGenerated': true,
      'needsReview': true,
      'promotionMode': 'manual-review-required',
    });
    index++;
  }
  return blueprints;
}

List<CatalogFamily> _familiesFor(_BlueprintOptions options) {
  if (options.scope != 'residential') return const [];
  if (options.trade == 'plumbing' && options.tier == 'core') {
    return _plumbingResidentialCoreFamilies;
  }
  if (options.trade == 'plumbing' && options.tier == 'standard') {
    return _plumbingResidentialStandardFamilies;
  }
  if (options.trade == 'plumbing' && options.tier == 'professional') {
    return _plumbingResidentialProfessionalFamilies;
  }
  if (options.trade == 'plumbing' && options.tier == 'complete') {
    return _plumbingResidentialCompleteFamilies;
  }
  if (options.trade == 'electrical' && options.tier == 'standard') {
    return _electricalResidentialStandardFamilies;
  }
  if (options.trade == 'electrical' && options.tier == 'professional') {
    return _electricalResidentialProfessionalFamilies;
  }
  if (options.trade == 'electrical' && options.tier == 'complete') {
    return _electricalResidentialCompleteFamilies;
  }
  if (options.trade == 'hvac' && options.tier == 'standard') {
    return hvacResidentialStandardFamilies;
  }
  if (options.trade == 'hvac' && options.tier == 'professional') {
    return hvacResidentialProfessionalFamilies;
  }
  if (options.trade == 'hvac' && options.tier == 'complete') {
    return hvacResidentialCompleteAddOnFamilies;
  }
  if (options.tier != 'core') return const [];
  if (options.trade == 'electrical') return _electricalResidentialCoreFamilies;
  if (options.trade == 'hvac') return hvacResidentialCoreFamilies;
  return const [];
}

String _tradeLabel(String trade) {
  if (trade == 'hvac') return 'HVAC';
  if (trade.isEmpty) return trade;
  return trade[0].toUpperCase() + trade.substring(1);
}

List<String> _unique(List<Map<String, Object?>> entries, String key) {
  return {
    for (final entry in entries) entry[key]?.toString() ?? '',
  }.where((value) => value.isNotEmpty).toList()..sort();
}

class _BlueprintOptions {
  const _BlueprintOptions({
    required this.trade,
    required this.scope,
    required this.tier,
    required this.locale,
    required this.limit,
    required this.outputDir,
    required this.seed,
  });

  final String trade;
  final String scope;
  final String tier;
  final String locale;
  final int limit;
  final String outputDir;
  final String seed;

  static _BlueprintOptions parse(List<String> args) {
    final values = <String, String>{};
    for (var index = 0; index < args.length; index++) {
      final arg = args[index];
      if (!arg.startsWith('--')) continue;
      final keyValue = arg.substring(2).split('=');
      if (keyValue.length == 2) {
        values[keyValue[0]] = keyValue[1];
      } else if (index + 1 < args.length && !args[index + 1].startsWith('--')) {
        values[keyValue[0]] = args[++index];
      }
    }
    final trade = (values['trade'] ?? 'plumbing').toLowerCase();
    final scope = (values['scope'] ?? 'residential').toLowerCase();
    final tier = (values['tier'] ?? 'core').toLowerCase();
    final locale = values['locale'] ?? 'en-US';
    return _BlueprintOptions(
      trade: trade,
      scope: scope,
      tier: tier,
      locale: locale,
      limit: int.tryParse(values['limit'] ?? '') ?? 500,
      outputDir: values['output-dir'] ?? 'build/parser_qa_blueprints',
      seed:
          values['seed'] ?? 'catalog-blueprint-v1-$trade-$scope-$tier-$locale',
    );
  }
}

const _plumbingResidentialCoreFamilies = [
  CatalogFamily(
    slug: 'pex_crimp_elbow_brass_90',
    category: 'Fittings',
    system: 'PEX',
    itemType: 'Elbow',
    material: 'brass',
    unit: 'each',
    sizes: ['1/2 in', '3/4 in', '1 in'],
    nameTemplate: '{size} PEX Crimp Elbow, Brass, 90 Degree',
    aliasTemplates: ['{size} PEX 90', '{size} PEX elbow', '{size} PEX ell'],
    receiptTemplates: [
      '{size} PEX CRMP ELL',
      '{size} PEX 90',
      'PEX ELB {size}',
    ],
    negativeTokens: ['PVC', 'conduit', 'copper', 'street elbow'],
  ),
  CatalogFamily(
    slug: 'pvc_schedule_40_coupling',
    category: 'Fittings',
    system: 'PVC Schedule 40',
    itemType: 'Coupling',
    material: 'PVC',
    unit: 'each',
    sizes: ['1/2 in', '3/4 in', '1 in', '1-1/2 in', '2 in'],
    nameTemplate: '{size} PVC Schedule 40 Coupling',
    aliasTemplates: ['{size} PVC coupling', '{size} PVC SCH40 CPLG'],
    receiptTemplates: ['{size} PVC SCH40 CPLG', '{size} PVC S40 COUPLING'],
    negativeTokens: ['conduit', 'EMT', 'CPVC', 'DWV'],
  ),
  CatalogFamily(
    slug: 'brass_compression_angle_stop',
    category: 'Valves',
    system: 'Fixture Stops',
    itemType: 'Supply Stop',
    material: 'brass',
    unit: 'each',
    sizes: ['1/2 x 3/8 in', '5/8 x 3/8 in'],
    nameTemplate: '{size} Brass Compression Angle Supply Stop',
    aliasTemplates: ['{size} angle stop', '{size} brass stop'],
    receiptTemplates: ['{size} BR ANG STOP', '{size} COMP STOP'],
    negativeTokens: ['gas valve', 'ball valve', 'gate valve'],
  ),
  CatalogFamily(
    slug: 'threaded_rod_zinc',
    category: 'Hangers and Supports',
    system: 'Fasteners',
    itemType: 'Threaded Rod',
    material: 'zinc-plated steel',
    unit: 'each',
    sizes: ['1/4 in', '3/8 in', '1/2 in'],
    nameTemplate: '{size} Zinc Threaded Rod',
    aliasTemplates: ['{size} all thread', '{size} threaded rod'],
    receiptTemplates: ['{size} ALL THREAD ROD', '{size} THREADED ROD ZINC'],
    negativeTokens: ['rebar', 'bolt', 'wood dowel'],
  ),
];

const _plumbingResidentialStandardFamilies = [
  ..._plumbingResidentialCoreFamilies,
  CatalogFamily(
    slug: 'toilet_wax_ring_with_bolts',
    category: 'Toilet Repair',
    system: 'Seals and Bolts',
    itemType: 'Wax Ring',
    material: 'wax',
    unit: 'each',
    sizes: ['standard', 'jumbo', 'extra thick'],
    nameTemplate: '{size} Toilet Wax Ring With Bolts',
    aliasTemplates: ['{size} wax ring', '{size} toilet seal'],
    receiptTemplates: ['{size} TOILET WAX RING', '{size} WAX RING BOLTS'],
    negativeTokens: ['o-ring', 'hose washer', 'wax free seal'],
  ),
  CatalogFamily(
    slug: 'toilet_closet_bolts',
    category: 'Toilet Repair',
    system: 'Seals and Bolts',
    itemType: 'Closet Bolt',
    material: 'brass plated steel',
    unit: 'pack',
    sizes: ['1/4 in x 2-1/4 in', '5/16 in x 3 in'],
    nameTemplate: '{size} Toilet Closet Bolt Kit',
    aliasTemplates: ['{size} closet bolt', '{size} toilet bolt'],
    receiptTemplates: ['{size} CLOSET BOLT KIT', '{size} TOILET BOLTS'],
    negativeTokens: ['lag bolt', 'machine bolt', 'anchor bolt'],
  ),
  CatalogFamily(
    slug: 'toilet_supply_line_braided',
    category: 'Supply Lines',
    system: 'Fixture Connectors',
    itemType: 'Toilet Supply Line',
    material: 'stainless braided',
    unit: 'each',
    sizes: ['3/8 in x 12 in', '3/8 in x 16 in', '3/8 in x 20 in'],
    nameTemplate: '{size} Braided Toilet Supply Line',
    aliasTemplates: ['{size} toilet connector', '{size} toilet supply'],
    receiptTemplates: ['{size} TOILET CONN', '{size} TOILET SUPPLY'],
    negativeTokens: ['faucet supply', 'dishwasher line', 'ice maker line'],
  ),
  CatalogFamily(
    slug: 'hose_bibb_brass',
    category: 'Valves',
    system: 'Hose Bibbs and Sillcocks',
    itemType: 'Hose Bibb',
    material: 'brass',
    unit: 'each',
    sizes: ['1/2 in', '3/4 in'],
    nameTemplate: '{size} Brass Hose Bibb',
    aliasTemplates: ['{size} hose bib', '{size} outside faucet'],
    receiptTemplates: ['{size} HOSE BIBB', '{size} OUTSIDE FAUCET'],
    negativeTokens: ['ball valve', 'washing machine valve', 'gas valve'],
  ),
  CatalogFamily(
    slug: 'pvc_primer_cement',
    category: 'Consumables',
    system: 'Solvent Welding',
    itemType: 'PVC Cement and Primer',
    material: 'solvent cement',
    unit: 'can',
    sizes: ['4 oz', '8 oz', '16 oz'],
    nameTemplate: '{size} PVC Primer and Cement',
    aliasTemplates: ['{size} pvc cement', '{size} purple primer'],
    receiptTemplates: ['{size} PVC CEMENT', '{size} PURPLE PRIMER'],
    negativeTokens: ['contact cement', 'tile primer', 'pipe fitting'],
  ),
];

const _plumbingResidentialProfessionalFamilies = [
  ..._plumbingResidentialStandardFamilies,
  CatalogFamily(
    slug: 'tubular_p_trap',
    category: 'Drainage',
    system: 'Tubular',
    itemType: 'P-Trap',
    material: 'PVC',
    unit: 'each',
    sizes: ['1-1/4 in', '1-1/2 in'],
    nameTemplate: '{size} Tubular P-Trap',
    aliasTemplates: ['{size} p-trap', '{size} p trap'],
    receiptTemplates: ['{size} P-TRAP', '{size} TUBULAR P TRAP'],
    negativeTokens: ['animal trap', 's trap', 'electrical box'],
  ),
  CatalogFamily(
    slug: 'disposal_install_kit',
    category: 'Drainage',
    system: 'Kitchen Drain',
    itemType: 'Disposal Install Kit',
    material: 'PVC and rubber',
    unit: 'kit',
    sizes: ['standard', 'with elbow'],
    nameTemplate: '{size} Garbage Disposal Install Kit',
    aliasTemplates: ['{size} disposal kit', '{size} disposal connector'],
    receiptTemplates: ['{size} DISPOSAL KIT', '{size} DISPOSAL CONN KIT'],
    negativeTokens: ['trash bag', 'food disposal unit only', 'air switch'],
  ),
  CatalogFamily(
    slug: 'water_heater_connector',
    category: 'Water Heater',
    system: 'Water Heater Supply',
    itemType: 'Water Heater Connector',
    material: 'stainless corrugated',
    unit: 'each',
    sizes: ['3/4 in x 18 in', '3/4 in x 24 in'],
    nameTemplate: '{size} Water Heater Connector',
    aliasTemplates: ['{size} water heater line', '{size} wtr htr conn'],
    receiptTemplates: ['{size} WATER HTR CONN', '{size} WTR HTR LINE'],
    negativeTokens: ['gas connector', 'faucet supply', 'toilet supply'],
  ),
  CatalogFamily(
    slug: 'sump_pump_check_valve',
    category: 'Pumps',
    system: 'Sump Pump',
    itemType: 'Check Valve',
    material: 'rubber and PVC',
    unit: 'each',
    sizes: ['1-1/4 in', '1-1/2 in'],
    nameTemplate: '{size} Sump Pump Check Valve',
    aliasTemplates: ['{size} sump check', '{size} pump check valve'],
    receiptTemplates: ['{size} SUMP CHECK', '{size} PUMP CHECK VALVE'],
    negativeTokens: ['water supply check', 'backflow preventer', 'gas valve'],
  ),
  CatalogFamily(
    slug: 'hose_bibb_vacuum_breaker',
    category: 'Valves',
    system: 'Hose Bibbs and Sillcocks',
    itemType: 'Vacuum Breaker',
    material: 'brass',
    unit: 'each',
    sizes: ['standard', 'frost-free'],
    nameTemplate: '{size} Hose Bibb Vacuum Breaker',
    aliasTemplates: ['{size} vac brkr', '{size} backflow preventer'],
    receiptTemplates: ['{size} VAC BRKR', '{size} VACUUM BREAKER'],
    negativeTokens: ['circuit breaker', 'check valve', 'pressure regulator'],
  ),
  CatalogFamily(
    slug: 'washing_machine_supply_hose',
    category: 'Supply Lines',
    system: 'Appliance Connectors',
    itemType: 'Washing Machine Hose',
    material: 'stainless braided',
    unit: 'pair',
    sizes: ['4 ft', '6 ft'],
    nameTemplate: '{size} Washing Machine Supply Hose Pair',
    aliasTemplates: ['{size} washer hose', '{size} laundry hose'],
    receiptTemplates: ['{size} WASHER HOSE', '{size} LAUNDRY HOSE'],
    negativeTokens: ['garden hose', 'dishwasher hose', 'discharge hose'],
  ),
  CatalogFamily(
    slug: 'galvanized_pipe_strap',
    category: 'Hangers and Supports',
    system: 'Pipe Support',
    itemType: 'Pipe Strap',
    material: 'galvanized steel',
    unit: 'pack',
    sizes: ['1/2 in', '3/4 in', '1 in'],
    nameTemplate: '{size} Galvanized Pipe Strap',
    aliasTemplates: ['{size} pipe strap', '{size} two hole strap'],
    receiptTemplates: ['{size} PIPE STRAP', '{size} 2 HOLE STRAP'],
    negativeTokens: ['duct strap', 'hanger strap', 'conduit strap'],
  ),
];

const _plumbingResidentialCompleteFamilies = [
  ..._plumbingResidentialProfessionalFamilies,
  CatalogFamily(
    slug: 'cleanout_plug_cover',
    category: 'Drainage',
    system: 'Cleanouts',
    itemType: 'Cleanout Part',
    material: 'brass and PVC',
    unit: 'each',
    sizes: ['1-1/2 in', '2 in', '3 in', '4 in'],
    nameTemplate: '{size} Cleanout Plug and Cover',
    aliasTemplates: ['{size} cleanout plug', '{size} cleanout cover'],
    receiptTemplates: ['{size} CLEANOUT PLUG', '{size} CLEANOUT COVER'],
    negativeTokens: ['electrical cover', 'wall plate', 'pipe cap'],
  ),
  CatalogFamily(
    slug: 'lavatory_pop_up_drain',
    category: 'Drainage',
    system: 'Lavatory Drains',
    itemType: 'Pop-Up Drain',
    material: 'chrome and brass',
    unit: 'each',
    sizes: ['1-1/4 in', '1-1/2 in'],
    nameTemplate: '{size} Lavatory Pop-Up Drain',
    aliasTemplates: ['{size} lav pop up', '{size} pop-up drain'],
    receiptTemplates: ['{size} LAV POP UP', '{size} POP UP DRAIN'],
    negativeTokens: ['tub drain', 'floor drain', 'roof drain'],
  ),
  CatalogFamily(
    slug: 'slip_joint_nut_washer',
    category: 'Drainage',
    system: 'Tubular',
    itemType: 'Slip Joint Hardware',
    material: 'poly and zinc',
    unit: 'pack',
    sizes: ['1-1/4 in', '1-1/2 in'],
    nameTemplate: '{size} Slip Joint Nut and Washer',
    aliasTemplates: ['{size} slip joint nut', '{size} nut and washer'],
    receiptTemplates: ['{size} SLIP JOINT NUT', '{size} NUT WASHER'],
    negativeTokens: ['machine nut', 'wire nut', 'faucet washer'],
  ),
  CatalogFamily(
    slug: 'gas_appliance_connector',
    category: 'Gas',
    system: 'Appliance Connectors',
    itemType: 'Gas Appliance Connector',
    material: 'stainless corrugated',
    unit: 'each',
    sizes: ['1/2 in x 24 in', '1/2 in x 36 in', '5/8 in x 48 in'],
    nameTemplate: '{size} Gas Appliance Connector',
    aliasTemplates: ['{size} gas connector', '{size} gas flex'],
    receiptTemplates: ['{size} GAS CONNECTOR', '{size} GAS APPLIANCE CONN'],
    negativeTokens: ['water heater supply', 'faucet supply', 'electrical flex'],
  ),
  CatalogFamily(
    slug: 'pressure_reducing_valve',
    category: 'Valves',
    system: 'Pressure Control',
    itemType: 'Pressure Reducing Valve',
    material: 'bronze',
    unit: 'each',
    sizes: ['1/2 in', '3/4 in', '1 in'],
    nameTemplate: '{size} Pressure Reducing Valve',
    aliasTemplates: ['{size} prv', '{size} pressure regulator'],
    receiptTemplates: ['{size} PRV', '{size} PRESS REDUCING VALVE'],
    negativeTokens: ['gas regulator', 'air regulator', 'check valve'],
  ),
  CatalogFamily(
    slug: 'ice_maker_supply_line',
    category: 'Supply Lines',
    system: 'Appliance Connectors',
    itemType: 'Ice Maker Supply Line',
    material: 'poly and stainless',
    unit: 'each',
    sizes: ['1/4 in x 10 ft', '1/4 in x 25 ft'],
    nameTemplate: '{size} Ice Maker Supply Line',
    aliasTemplates: ['{size} ice maker line', '{size} fridge water line'],
    receiptTemplates: ['{size} ICE MAKER LINE', '{size} FRIDGE WATER LINE'],
    negativeTokens: ['dishwasher line', 'toilet supply', 'gas connector'],
  ),
];

const _electricalResidentialCoreFamilies = [
  CatalogFamily(
    slug: 'old_work_box_single_gang',
    category: 'Boxes',
    system: 'Residential Wiring',
    itemType: 'Old Work Box',
    material: 'PVC',
    unit: 'each',
    sizes: ['1 gang', '2 gang'],
    nameTemplate: '{size} Old Work Electrical Box',
    aliasTemplates: ['{size} old work box', '{size} remodel box'],
    receiptTemplates: ['{size} OLD WORK BOX', '{size} REMOD BOX'],
    negativeTokens: ['junction box', 'metal box', 'plumbing box'],
  ),
  CatalogFamily(
    slug: 'nm_b_wire_copper',
    category: 'Wire',
    system: 'NM-B',
    itemType: 'Cable',
    material: 'copper',
    unit: 'roll',
    sizes: ['14/2', '12/2', '12/3'],
    nameTemplate: '{size} NM-B Copper Cable',
    aliasTemplates: ['{size} romex', '{size} nm cable'],
    receiptTemplates: ['{size} NM-B WIRE', '{size} ROMEX'],
    negativeTokens: ['THHN', 'low voltage', 'speaker wire'],
  ),
  CatalogFamily(
    slug: 'emt_set_screw_connector',
    category: 'Conduit and Fittings',
    system: 'EMT',
    itemType: 'Connector',
    material: 'zinc',
    unit: 'each',
    sizes: ['1/2 in', '3/4 in', '1 in'],
    nameTemplate: '{size} EMT Set Screw Connector',
    aliasTemplates: ['{size} EMT connector', '{size} set screw conn'],
    receiptTemplates: ['{size} EMT SS CONN', '{size} EMT CONNECTOR'],
    negativeTokens: ['PVC coupling', 'plumbing coupling', 'compression stop'],
  ),
  CatalogFamily(
    slug: 'wire_nut_assorted',
    category: 'Connectors',
    system: 'Splicing',
    itemType: 'Wire Connector',
    material: 'plastic and spring steel',
    unit: 'pack',
    sizes: ['small', 'medium', 'large'],
    nameTemplate: '{size} Twist-On Wire Connector Pack',
    aliasTemplates: ['{size} wire nut', '{size} wirenut'],
    receiptTemplates: ['{size} WIRE NUT', '{size} TWIST CONN'],
    negativeTokens: ['plumbing nut', 'lock nut', 'hose connector'],
  ),
];

const _electricalResidentialStandardFamilies = [
  ..._electricalResidentialCoreFamilies,
  CatalogFamily(
    slug: 'gfci_receptacle_white',
    category: 'Devices',
    system: 'Residential Wiring',
    itemType: 'GFCI Receptacle',
    material: 'thermoplastic and copper',
    unit: 'each',
    sizes: ['15 amp', '20 amp'],
    nameTemplate: '{size} White GFCI Receptacle',
    aliasTemplates: ['{size} gfci outlet', '{size} gfi receptacle'],
    receiptTemplates: ['{size} GFCI RECPT', '{size} GFI OUTLET'],
    negativeTokens: ['breaker', 'switch', 'cover plate'],
  ),
  CatalogFamily(
    slug: 'single_pole_breaker',
    category: 'Breakers',
    system: 'Load Center',
    itemType: 'Single-Pole Breaker',
    material: 'molded case',
    unit: 'each',
    sizes: ['15 amp', '20 amp', '30 amp'],
    nameTemplate: '{size} Single-Pole Circuit Breaker',
    aliasTemplates: ['{size} 1 pole breaker', '{size} circuit breaker'],
    receiptTemplates: ['{size} 1P BRKR', '{size} CIRCUIT BREAKER'],
    negativeTokens: ['gfci receptacle', 'switch', 'fuse'],
  ),
  CatalogFamily(
    slug: 'vinyl_electrical_tape',
    category: 'Connectors and Consumables',
    system: 'Splicing',
    itemType: 'Electrical Tape',
    material: 'vinyl',
    unit: 'roll',
    sizes: ['3/4 in', '1 in'],
    nameTemplate: '{size} Vinyl Electrical Tape',
    aliasTemplates: ['{size} electrical tape', '{size} electric tape'],
    receiptTemplates: ['{size} ELEC TAPE', '{size} ELECTRICAL TAPE'],
    negativeTokens: ['foil tape', 'duct tape', 'thread seal tape'],
  ),
  CatalogFamily(
    slug: 'nm_cable_staple',
    category: 'Fasteners',
    system: 'NM-B',
    itemType: 'Cable Staple',
    material: 'plastic insulated steel',
    unit: 'pack',
    sizes: ['1/2 in', '3/4 in'],
    nameTemplate: '{size} Insulated NM Cable Staple',
    aliasTemplates: ['{size} romex staple', '{size} cable staple'],
    receiptTemplates: ['{size} ROMEX STAPLE', '{size} CABLE STAPLE'],
    negativeTokens: ['floor staple', 'landscape staple', 'wire connector'],
  ),
  CatalogFamily(
    slug: 'grounding_rod_clamp',
    category: 'Grounding and Bonding',
    system: 'Grounding',
    itemType: 'Ground Rod Clamp',
    material: 'bronze',
    unit: 'each',
    sizes: ['1/2 in', '5/8 in'],
    nameTemplate: '{size} Ground Rod Clamp',
    aliasTemplates: ['{size} ground clamp', '{size} grounding clamp'],
    receiptTemplates: ['{size} GROUND CLAMP', '{size} GRD ROD CLAMP'],
    negativeTokens: ['hose clamp', 'pipe clamp', 'ground screw'],
  ),
];

const _electricalResidentialProfessionalFamilies = [
  ..._electricalResidentialStandardFamilies,
  CatalogFamily(
    slug: 'double_pole_breaker',
    category: 'Breakers',
    system: 'Load Center',
    itemType: 'Double-Pole Breaker',
    material: 'molded case',
    unit: 'each',
    sizes: ['20 amp', '30 amp', '40 amp', '50 amp'],
    nameTemplate: '{size} Double-Pole Circuit Breaker',
    aliasTemplates: ['{size} 2 pole breaker', '{size} double pole breaker'],
    receiptTemplates: ['{size} 2P BRKR', '{size} DOUBLE POLE BREAKER'],
    negativeTokens: ['single pole breaker', 'gfci outlet', 'switch'],
  ),
  CatalogFamily(
    slug: 'afci_breaker',
    category: 'Breakers',
    system: 'Load Center',
    itemType: 'AFCI Breaker',
    material: 'molded case',
    unit: 'each',
    sizes: ['15 amp', '20 amp'],
    nameTemplate: '{size} AFCI Circuit Breaker',
    aliasTemplates: ['{size} afci breaker', '{size} arc fault breaker'],
    receiptTemplates: ['{size} AFCI BRKR', '{size} ARC FAULT BREAKER'],
    negativeTokens: ['gfci receptacle', 'surge protector', 'switch'],
  ),
  CatalogFamily(
    slug: 'toggle_switch',
    category: 'Devices',
    system: 'Residential Wiring',
    itemType: 'Toggle Switch',
    material: 'thermoplastic and copper',
    unit: 'each',
    sizes: ['single pole', '3-way', '4-way'],
    nameTemplate: '{size} Toggle Switch',
    aliasTemplates: ['{size} wall switch', '{size} light switch'],
    receiptTemplates: ['{size} TOGGLE SWITCH', '{size} WALL SWITCH'],
    negativeTokens: ['breaker', 'disconnect', 'thermostat'],
  ),
  CatalogFamily(
    slug: 'dimmer_switch',
    category: 'Devices',
    system: 'Residential Wiring',
    itemType: 'Dimmer Switch',
    material: 'thermoplastic and electronics',
    unit: 'each',
    sizes: ['single pole', '3-way'],
    nameTemplate: '{size} LED Dimmer Switch',
    aliasTemplates: ['{size} dimmer', '{size} led dimmer'],
    receiptTemplates: ['{size} LED DIMMER', '{size} DIMMER SWITCH'],
    negativeTokens: ['breaker', 'thermostat', 'fan control'],
  ),
  CatalogFamily(
    slug: 'junction_box_metal',
    category: 'Boxes',
    system: 'Residential Wiring',
    itemType: 'Junction Box',
    material: 'steel',
    unit: 'each',
    sizes: ['4 in square', '4-11/16 in square'],
    nameTemplate: '{size} Metal Junction Box',
    aliasTemplates: ['{size} j box', '{size} junction box'],
    receiptTemplates: ['{size} J BOX', '{size} JUNCTION BOX'],
    negativeTokens: ['old work box', 'plumbing box', 'gang box'],
  ),
  CatalogFamily(
    slug: 'ground_rod_copper',
    category: 'Grounding and Bonding',
    system: 'Grounding',
    itemType: 'Ground Rod',
    material: 'copper bonded steel',
    unit: 'each',
    sizes: ['5/8 in x 8 ft', '1/2 in x 8 ft'],
    nameTemplate: '{size} Copper Ground Rod',
    aliasTemplates: ['{size} ground rod', '{size} grounding rod'],
    receiptTemplates: ['{size} GROUND ROD', '{size} GRD ROD'],
    negativeTokens: ['ground clamp', 'threaded rod', 'rebar'],
  ),
];

const _electricalResidentialCompleteFamilies = [
  ..._electricalResidentialProfessionalFamilies,
  ...electricalResidentialCompleteAddOnFamilies,
];
