import 'work_supply_catalog_blueprint_model.dart';

const electricalResidentialCompleteAddOnFamilies = [
  CatalogFamily(
    slug: 'weatherproof_in_use_cover',
    category: 'Weatherproof Devices',
    system: 'Exterior Wiring',
    itemType: 'In-Use Cover',
    material: 'polycarbonate',
    unit: 'each',
    sizes: ['1 gang', '2 gang'],
    nameTemplate: '{size} Weatherproof In-Use Cover',
    aliasTemplates: ['{size} bubble cover', '{size} while-in-use cover'],
    receiptTemplates: ['{size} IN USE COVER', '{size} WP BUBBLE COVER'],
    negativeTokens: ['junction box', 'plate cover', 'duct cover'],
  ),
  CatalogFamily(
    slug: 'weatherproof_exterior_box',
    category: 'Weatherproof Boxes',
    system: 'Exterior Wiring',
    itemType: 'Weatherproof Box',
    material: 'die-cast aluminum',
    unit: 'each',
    sizes: ['1 gang', '2 gang'],
    nameTemplate: '{size} Weatherproof Exterior Box',
    aliasTemplates: ['{size} outdoor box', '{size} wp box'],
    receiptTemplates: ['{size} WP BOX', '{size} OUTDOOR BOX'],
    negativeTokens: ['old work box', 'junction box', 'plumbing box'],
  ),
  CatalogFamily(
    slug: 'air_conditioner_disconnect',
    category: 'Disconnects',
    system: 'Exterior Equipment',
    itemType: 'AC Disconnect',
    material: 'steel enclosure',
    unit: 'each',
    sizes: ['30 amp', '60 amp'],
    nameTemplate: '{size} Non-Fused AC Disconnect',
    aliasTemplates: ['{size} ac disconnect', '{size} pullout disconnect'],
    receiptTemplates: ['{size} AC DISC', '{size} NON FUSED DISC'],
    negativeTokens: ['breaker', 'switch', 'fuse'],
  ),
  CatalogFamily(
    slug: 'ceiling_fan_brace_box',
    category: 'Boxes',
    system: 'Ceiling Wiring',
    itemType: 'Fan Brace Box',
    material: 'steel',
    unit: 'kit',
    sizes: ['new work', 'old work'],
    nameTemplate: '{size} Ceiling Fan Brace Box',
    aliasTemplates: ['{size} fan box brace', '{size} fan rated box'],
    receiptTemplates: ['{size} FAN BRACE BOX', '{size} FAN RATED BOX'],
    negativeTokens: ['junction box', 'old work wall box', 'light fixture'],
  ),
  CatalogFamily(
    slug: 'load_center_panel_filler',
    category: 'Load Center Parts',
    system: 'Load Center',
    itemType: 'Panel Filler Plate',
    material: 'plastic',
    unit: 'pack',
    sizes: ['1 in', '1/2 in'],
    nameTemplate: '{size} Load Center Panel Filler Plate',
    aliasTemplates: ['{size} breaker filler', '{size} panel blank'],
    receiptTemplates: ['{size} PANEL FILLER', '{size} BRKR FILLER'],
    negativeTokens: ['wall plate', 'switch plate', 'junction box cover'],
  ),
  CatalogFamily(
    slug: 'thhn_wire_spool',
    category: 'Wire',
    system: 'Branch Circuit',
    itemType: 'THHN Wire',
    material: 'copper',
    unit: 'spool',
    sizes: ['12 awg black', '12 awg white', '10 awg black'],
    nameTemplate: '{size} Stranded THHN Wire',
    aliasTemplates: ['{size} thhn', '{size} building wire'],
    receiptTemplates: ['{size} THHN WIRE', '{size} THHN STRD'],
    negativeTokens: ['nm-b cable', 'thermostat wire', 'ground rod'],
  ),
  CatalogFamily(
    slug: 'conduit_body_lb',
    category: 'Conduit Bodies',
    system: 'Raceway',
    itemType: 'LB Conduit Body',
    material: 'PVC',
    unit: 'each',
    sizes: ['1/2 in', '3/4 in', '1 in'],
    nameTemplate: '{size} PVC LB Conduit Body',
    aliasTemplates: ['{size} lb body', '{size} conduit body'],
    receiptTemplates: ['{size} PVC LB BODY', '{size} COND BODY LB'],
    negativeTokens: ['plumbing elbow', 'condensate fitting', 'junction box'],
  ),
];
