class WorkSupplyFixtureRecipe {
  const WorkSupplyFixtureRecipe({
    required this.slug,
    required this.caseType,
    required this.patterns,
    required this.riskTags,
    this.expectedTrade = 'Plumbing',
    this.expectedNameContains = '',
    this.tradeScope = 'Plumbing',
    this.expectUnknown = false,
    this.maxConfidence = 1,
  });

  final String slug;
  final String caseType;
  final List<String> patterns;
  final List<String> riskTags;
  final String expectedTrade;
  final String expectedNameContains;
  final String tradeScope;
  final bool expectUnknown;
  final double maxConfidence;
}

const englishPlumbingCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'pex_crimp_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PEX',
    riskTags: [
      'pex',
      'crimp',
      'elbow',
      'size',
      'merchant_abbreviation',
      'generated_batch',
    ],
    patterns: ['1/2 PEX CRMP ELL', '3/4 PEX 90', '1/2IN PEX ELB'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Coupling',
    riskTags: ['pex', 'coupling', 'service_truck', 'core_plumbing'],
    patterns: ['1/2 PEX CPLG', '3/4 PEX COUPLING', '1 IN PEX CPLG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_transition_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Transition Coupling',
    riskTags: ['pex', 'transition', 'coupling', 'service_truck'],
    patterns: [
      '1/2 PEX TRANS CPLG',
      '3/4 PEX TRANSITION COUPLING',
      '1 IN PEX TRANS COUPLER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_male_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Male Adapter',
    riskTags: ['pex', 'adapter', 'male_adapter', 'service_truck'],
    patterns: ['1/2 PEX M ADPT', '3/4 PEX MALE ADAPTER', '1 IN PEX MIP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_female_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Female Adapter',
    riskTags: ['pex', 'adapter', 'female_adapter', 'service_truck'],
    patterns: ['1/2 PEX F ADPT', '3/4 PEX FEMALE ADAPTER', '1 IN PEX FIP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Tee',
    riskTags: ['pex', 'tee', 'service_truck', 'core_plumbing'],
    patterns: ['1/2 PEX TEE', '3/4 PEX T', '1 X 3/4 PEX TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_drop_ear_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Drop-Ear Elbow',
    riskTags: ['pex', 'drop_ear', 'elbow', 'stub_out', 'service_truck'],
    patterns: [
      '1/2 PEX DROP EAR ELL',
      '1/2 PEX DROP-EAR ELBOW',
      '3/4 PEX SHOWER ELBOW',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_crimp_ring',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Crimp Ring',
    riskTags: ['pex', 'crimp_ring', 'service_truck', 'consumable'],
    patterns: ['1/2 PEX CRIMP RING', '3/4 PEX CRMP RING', '1 IN PEX RING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_clamp_ring',
    caseType: 'clear_match',
    expectedNameContains: 'PEX Clamp Ring',
    riskTags: ['pex', 'clamp_ring', 'cinch', 'service_truck', 'consumable'],
    patterns: ['1/2 PEX CLAMP RING', '3/4 PEX CINCH CLAMP', '1 IN PEX CLAMP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_crimp_tool',
    caseType: 'clear_match',
    expectedNameContains: 'PEX crimp tool',
    riskTags: ['pex', 'tool', 'crimp_tool', 'service_truck'],
    patterns: ['1/2 PEX CRIMP TOOL', '1/2 3/4 PEX CRIMP TOOL', 'PEX CRMP TOOL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pex_cinch_tool',
    caseType: 'clear_match',
    expectedNameContains: 'PEX clamp cinch tool',
    riskTags: ['pex', 'tool', 'cinch_tool', 'service_truck'],
    patterns: ['PEX CINCH TOOL', 'PEX CLAMP TOOL', 'PEX CLAMP CINCH TOOL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Coupling',
    riskTags: ['pvc', 'schedule_40', 'coupling', 'size'],
    patterns: ['3/4 PVC SCH40 CPLG', '1 PVC S40 COUPLING', '1/2 PVC CPLG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'elbow'],
    patterns: ['1/2 PVC SCH 40 90 ELB', '3/4 PVC S40 45 ELL', '1 IN PVC 90'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'adapter'],
    patterns: [
      '1/2 PVC SCH 40 MALE ADPT',
      '3/4 PVC SCH40 FEMALE ADAPTER',
      '1 IN PVC S40 F ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Tee',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'tee'],
    patterns: ['1/2 PVC SCH40 TEE', '3/4 PVC S40 T', '1 X 3/4 PVC SCH40 TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_reducer_bushing',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Reducer',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'reducer', 'bushing'],
    patterns: [
      '3/4 X 1/2 PVC SCH40 RED BUSH',
      '1 X 3/4 PVC S40 REDUCER BUSHING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_schedule_40_reducing_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC Schedule 40 Reducing Coupling',
    riskTags: ['pvc_pressure', 'pvc', 'schedule_40', 'reducing_coupling'],
    patterns: [
      '3/4 X 1/2 PVC SCH40 REDUCING CPLG',
      '1 X 3/4 PVC S40 REDUCER COUPLING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_90_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV 90 Elbow',
    riskTags: ['pvc_dwv', 'dwv', 'elbow', 'drainage'],
    patterns: ['1-1/2 PVC DWV 90 ELB', '2 IN PVC DWV 90', '3 PVC DRAIN 90'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_45_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV 45 Elbow',
    riskTags: ['pvc_dwv', 'dwv', 'elbow', 'drainage'],
    patterns: ['1-1/2 PVC DWV 45 ELB', '2 IN PVC DWV 45', '3 PVC DRAIN 45'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_wye',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Wye',
    riskTags: ['pvc_dwv', 'dwv', 'wye', 'drainage'],
    patterns: ['2 PVC DWV WYE', '3 IN PVC DWV Y FITTING', '4 PVC DRAIN WYE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_sanitary_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Sanitary Tee',
    riskTags: ['pvc_dwv', 'dwv', 'sanitary_tee', 'drainage'],
    patterns: ['1-1/2 PVC DWV SAN TEE', '2 PVC SANITARY T', '3 PVC DWV SANTEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_reducing_sanitary_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Reducing Sanitary Tee',
    riskTags: ['pvc_dwv', 'dwv', 'sanitary_tee', 'reducing', 'drainage'],
    patterns: [
      '2 X 2 X 1-1/2 PVC DWV REDUCING SAN TEE',
      '3 X 3 X 2 PVC DWV REDUCING SANITARY',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Coupling',
    riskTags: ['pvc_dwv', 'dwv', 'coupling', 'drainage'],
    patterns: ['1-1/2 PVC DWV CPLG', '2 PVC DWV COUPLING', '3 PVC DRAIN CPLG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_reducing_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Reducing Coupling',
    riskTags: ['pvc_dwv', 'dwv', 'coupling', 'reducing', 'drainage'],
    patterns: [
      '2 X 1-1/2 PVC DWV REDUCING CPLG',
      '3 X 2 PVC DWV REDUCER COUPLING',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_trap_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Trap Adapter',
    riskTags: ['pvc_dwv', 'dwv', 'trap_adapter', 'drainage'],
    patterns: [
      '1-1/2 PVC DWV TRAP ADAPTER',
      '2 PVC DWV TRAP ADAPTER',
      '1-1/2 PVC DWV MARVEL ADAPTER',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_cleanout',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Cleanout',
    riskTags: ['pvc_dwv', 'dwv', 'cleanout', 'drainage'],
    patterns: ['1-1/2 PVC DWV CLEANOUT', '2 PVC DWV CLEAN OUT', '3 PVC CO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_dwv_test_tee',
    caseType: 'clear_match',
    expectedNameContains: 'PVC DWV Test Tee',
    riskTags: ['pvc_dwv', 'dwv', 'test_tee', 'cleanout', 'drainage'],
    patterns: ['1-1/2 PVC DWV TEST TEE', '2 PVC CLEANOUT TEE', '3 PVC TEST T'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cleanout_access_plug',
    caseType: 'clear_match',
    expectedNameContains: 'cleanout plug',
    riskTags: ['pvc_dwv', 'cleanout', 'access', 'plug', 'drainage'],
    patterns: [
      '1-1/2 FLUSH CLEANOUT PLUG',
      '2 IN COUNTERSUNK CLEANOUT PLUG',
      '3 BRASS CLEANOUT PLUG',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cleanout_access_cover',
    caseType: 'clear_match',
    expectedNameContains: 'cleanout cover',
    riskTags: ['pvc_dwv', 'cleanout', 'access', 'cover', 'drainage'],
    patterns: ['1-1/2 ROUND CLEANOUT COVER', '2 SQUARE CLEANOUT COVER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC',
    riskTags: ['cpvc', 'elbow', 'pressure_pipe', 'service_truck'],
    patterns: ['1/2 CPVC 90 ELBOW', '3/4 CPVC 90', '1 IN CPVC ELL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC Coupling',
    riskTags: ['cpvc', 'coupling', 'pressure_pipe', 'service_truck'],
    patterns: ['1/2 CPVC CPLG', '3/4 CPVC COUPLING', '1 IN CPVC COUP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC',
    riskTags: ['cpvc', 'adapter', 'pressure_pipe', 'service_truck'],
    patterns: [
      '1/2 CPVC MALE ADPT',
      '3/4 CPVC FEMALE ADAPTER',
      '1 IN CPVC TRANSITION ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_tee',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC Tee',
    riskTags: ['cpvc', 'tee', 'pressure_pipe', 'service_truck'],
    patterns: ['1/2 CPVC TEE', '3/4 CPVC T', '1 X 3/4 CPVC TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cpvc_reducer_bushing',
    caseType: 'clear_match',
    expectedNameContains: 'CPVC Reducer',
    riskTags: ['cpvc', 'reducer', 'bushing', 'pressure_pipe'],
    patterns: ['3/4 X 1/2 CPVC RED BUSH', '1 X 3/4 CPVC REDUCER BUSHING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_elbow',
    caseType: 'clear_match',
    expectedNameContains: 'Copper',
    riskTags: ['copper', 'elbow', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER 90 ELBOW', '3/4 COPPER 45 ELL', '1 IN COPPER 90'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'Copper Coupling',
    riskTags: ['copper', 'coupling', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER CPLG', '3/4 COPPER COUPLING', '1 IN COPPER COUP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_repair_coupling',
    caseType: 'clear_match',
    expectedNameContains: 'Copper Repair Coupling',
    riskTags: ['copper', 'repair_coupling', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER REPAIR CPLG', '3/4 COPPER SLIP COUPLING'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'Copper',
    riskTags: ['copper', 'adapter', 'sweat', 'service_truck'],
    patterns: [
      '1/2 COPPER MALE ADPT',
      '3/4 COPPER FEMALE ADAPTER',
      '1 IN COPPER F ADPT',
    ],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_tee',
    caseType: 'clear_match',
    expectedNameContains: 'Copper Tee',
    riskTags: ['copper', 'tee', 'sweat', 'service_truck'],
    patterns: ['1/2 COPPER TEE', '3/4 COPPER T', '1 X 3/4 COPPER TEE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_dielectric_union',
    caseType: 'clear_match',
    expectedNameContains: 'Dielectric Union',
    riskTags: ['copper', 'dielectric_union', 'water_heater', 'service_truck'],
    patterns: ['3/4 COPPER DIELECTRIC UNION', '1 IN WATER HEATER UNION'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'copper_bell_hanger',
    caseType: 'clear_match',
    expectedNameContains: 'Bell Hanger',
    riskTags: ['copper', 'bell_hanger', 'support', 'service_truck'],
    patterns: ['1/2 COPPER BELL HANGER', '3/4 BELL HANGER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_angle_stop',
    caseType: 'clear_match',
    expectedNameContains: 'Stop',
    riskTags: ['brass', 'valve', 'angle_stop', 'supply'],
    patterns: ['1/2 X 3/8 BR ANG STOP', '5/8OD X 3/8 COMP STOP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_wax_ring',
    caseType: 'clear_match',
    expectedNameContains: 'Wax',
    riskTags: ['toilet', 'repair', 'seal', 'service_truck'],
    patterns: ['TOILET WAX RING', 'JUMBO WAX RING BOLTS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_fill_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Fill Valve',
    riskTags: ['toilet', 'repair', 'fill_valve', 'service_truck'],
    patterns: ['TOILET FILL VALVE', 'ADJUSTABLE FILL VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lavatory_p_trap',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['drainage', 'tubular', 'service_truck'],
    patterns: ['1-1/4 LAV P TRAP', '1-1/2 P-TRAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tubular_tailpiece',
    caseType: 'clear_match',
    expectedNameContains: 'Tailpiece',
    riskTags: ['drainage', 'tubular', 'tailpiece', 'service_truck'],
    patterns: ['1-1/2 TAILPIECE', '1-1/4 LAV TAILPIECE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tubular_extension_tube',
    caseType: 'clear_match',
    expectedNameContains: 'Extension Tube',
    riskTags: ['drainage', 'tubular', 'extension_tube', 'service_truck'],
    patterns: ['1-1/2 EXTENSION TUBE', '1-1/4 TUBULAR EXT TUBE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'slip_joint_nut_washer',
    caseType: 'clear_match',
    expectedNameContains: 'Slip Joint',
    riskTags: ['drainage', 'tubular', 'slip_joint', 'service_truck'],
    patterns: ['1-1/2 SLIP JOINT NUT WASHER', '1-1/4 SJ NUT WASHER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'beveled_washer_pack',
    caseType: 'clear_match',
    expectedNameContains: 'beveled washers',
    riskTags: ['drainage', 'tubular', 'washer', 'service_truck'],
    patterns: ['1-1/2 BEVELED WASHER 5PK', '1-1/4 SLIP WASHER 2PK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'basket_strainer',
    caseType: 'clear_match',
    expectedNameContains: 'Basket Strainer',
    riskTags: ['drainage', 'tubular', 'basket_strainer', 'service_truck'],
    patterns: ['KITCHEN BASKET STRAINER', 'STAINLESS BASKET STRAINER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'brass_j_bend',
    caseType: 'clear_match',
    expectedNameContains: 'J-bend',
    riskTags: ['drainage', 'tubular', 'j_bend', 'service_truck'],
    patterns: ['1-1/2 BRASS J BEND', '1-1/4 CHROME J-BEND'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'flanged_tailpiece',
    caseType: 'clear_match',
    expectedNameContains: 'flanged tailpiece',
    riskTags: ['drainage', 'tubular', 'tailpiece', 'service_truck'],
    patterns: ['1-1/2 FLANGED TAILPIECE', '1-1/4 FLANGE TAIL PIECE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'compression_trap_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'compression trap adapter',
    riskTags: [
      'legacy_repair',
      'compression_trap',
      'transition',
      'service_truck',
    ],
    patterns: ['1-1/2 COMPRESSION TRAP ADAPTER', '2 IN COMP TRAP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'desanco_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'desanco adapter',
    riskTags: ['legacy_repair', 'desanco', 'transition', 'service_truck'],
    patterns: ['1-1/2 DESANCO ADAPTER', '1-1/4 DESANCO TRAP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'marvel_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'marvel adapter',
    riskTags: ['legacy_repair', 'marvel', 'transition', 'service_truck'],
    patterns: ['1-1/2 MARVEL ADAPTER', '2 IN MARVEL TRAP ADPT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'wall_bend_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'wall bend',
    riskTags: ['legacy_repair', 'wall_bend', 'transition', 'service_truck'],
    patterns: ['1-1/2 WALL BEND ADAPTER', '1-1/4 WALL BEND'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'trap_arm_adapter',
    caseType: 'clear_match',
    expectedNameContains: 'trap arm',
    riskTags: ['legacy_repair', 'trap_arm', 'transition', 'service_truck'],
    patterns: ['1-1/2 TRAP ARM ADAPTER', '2 IN TRAP ARM'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'braided_faucet_supply',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['faucet', 'supply_line', 'service_truck'],
    patterns: ['3/8 X 16 FAUCET CONN', 'LAV SUPPLY 3/8 X 20'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_softener_salt',
    caseType: 'clear_match',
    expectedNameContains: 'water softener salt',
    riskTags: ['water_treatment', 'softener', 'salt', 'service_truck'],
    patterns: ['40LB WATER SOFTENER SALT', '25 LB SOFTENER SALT PELLETS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'well_pressure_switch',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Switch',
    riskTags: ['well', 'pump', 'pressure_switch', 'service_truck'],
    patterns: ['30/50 WELL PRESS SWITCH', '40/60 PUMP PRESS SW'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'well_check_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['well', 'pump', 'check_valve', 'service_truck'],
    patterns: ['1 IN WELL CHECK VALVE', '3/4 PUMP CHECK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'threaded_rod',
    caseType: 'clear_match',
    expectedNameContains: 'Threaded Rod',
    riskTags: ['fastener', 'threaded_rod', 'hanger_support'],
    patterns: ['3/8 ALL THREAD ROD', '1/2 THREADED ROD ZINC'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_pvc_elbow',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['dangerous_word', 'pvc', 'cross_trade', 'needs_review'],
    patterns: ['PVC EL 3/4', 'PVC 90 1/2'],
  ),
];

const spanishPlumbingCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'codo_pex',
    caseType: 'clear_match',
    expectedNameContains: 'PEX',
    riskTags: ['spanish', 'pex', 'codo', 'size', 'generated_batch'],
    patterns: ['1/2 CODO PEX 90', '3/4 CODO PEX LATON'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'acople_pvc',
    caseType: 'clear_match',
    expectedNameContains: 'PVC',
    riskTags: ['spanish', 'pvc', 'coupling', 'size'],
    patterns: ['3/4 ACOPLE PVC CED40', '1 ACOPLE PVC SCH40'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_angulo',
    caseType: 'clear_match',
    expectedNameContains: 'Stop',
    riskTags: ['spanish', 'valve', 'angle_stop', 'supply'],
    patterns: ['1/2 X 3/8 VALVULA ANGULO', 'LLAVE ANGULAR 1/2 X 3/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'varilla_roscada',
    caseType: 'clear_match',
    expectedNameContains: 'Threaded Rod',
    riskTags: ['spanish', 'fastener', 'threaded_rod'],
    patterns: ['3/8 VARILLA ROSCADA', '1/2 VARILLA TODO ROSCA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_llenado_sanitario',
    caseType: 'clear_match',
    expectedNameContains: 'Fill Valve',
    riskTags: ['spanish', 'toilet', 'fill_valve', 'service_truck'],
    patterns: ['VALVULA LLENADO SANITARIO', 'FILL VALVE SANITARIO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'trampa_lavamanos',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['spanish', 'drainage', 'tubular', 'service_truck'],
    patterns: ['TRAMPA LAVAMANOS 1-1/4', 'P TRAP 1-1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'linea_lavamanos',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['spanish', 'faucet', 'supply_line', 'service_truck'],
    patterns: ['LINEA LAVAMANOS 3/8 X 16', 'CONECTOR GRIFO 3/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sal_suavizador',
    caseType: 'clear_match',
    expectedNameContains: 'water softener salt',
    riskTags: ['spanish', 'water_treatment', 'softener', 'salt'],
    patterns: ['SAL SUAVIZADOR 40LB', 'SAL ABLANDADOR 25 LB'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'switch_presion_pozo',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Switch',
    riskTags: ['spanish', 'well', 'pump', 'pressure_switch'],
    patterns: ['SWITCH PRESION POZO 30/50', 'INTERRUPTOR BOMBA 40/60'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_check_pozo',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['spanish', 'well', 'pump', 'check_valve'],
    patterns: ['VALVULA CHECK POZO 1 IN', 'CHECK BOMBA 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'generico_pvc',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['spanish', 'dangerous_word', 'pvc', 'needs_review'],
    patterns: ['PVC CODO', 'PVC 90'],
  ),
];

const englishPlumbingStandardRecipes = [
  ...englishPlumbingCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'closet_bolt_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Closet Bolt',
    riskTags: ['toilet', 'bolt', 'repair', 'standard_pack', 'generated_batch'],
    patterns: ['CLOSET BOLT KIT', 'TOILET BOLTS 5/16'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toilet_supply_line',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['toilet', 'supply_line', 'connector', 'standard_pack'],
    patterns: ['TOILET CONN 3/8 X 12', 'TOILET SUPPLY 3/8 X 16'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hose_bibb',
    caseType: 'clear_match',
    expectedNameContains: 'Hose Bibb',
    riskTags: ['valve', 'outside_faucet', 'standard_pack'],
    patterns: ['1/2 HOSE BIBB', '3/4 OUTSIDE FAUCET'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_cement_primer',
    caseType: 'clear_match',
    expectedNameContains: 'PVC',
    riskTags: ['consumable', 'cement', 'primer', 'dangerous_word'],
    patterns: ['8 OZ PVC CEMENT', 'PURPLE PRIMER 16 OZ'],
  ),
];

const spanishPlumbingStandardRecipes = [
  ...spanishPlumbingCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'perno_sanitario',
    caseType: 'clear_match',
    expectedNameContains: 'Closet Bolt',
    riskTags: ['spanish', 'toilet', 'bolt', 'standard_pack', 'generated_batch'],
    patterns: ['PERNO SANITARIO', 'TORNILLO SANITARIO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'linea_sanitario',
    caseType: 'clear_match',
    expectedNameContains: 'Supply Line',
    riskTags: ['spanish', 'toilet', 'supply_line', 'standard_pack'],
    patterns: ['LINEA SUMINISTRO SANITARIO', 'CONECTOR SANITARIO 3/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'llave_manguera',
    caseType: 'clear_match',
    expectedNameContains: 'Sillcock',
    riskTags: ['spanish', 'valve', 'outside_faucet', 'standard_pack'],
    patterns: ['LLAVE MANGUERA 1/2', 'GRIFO EXTERIOR 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cemento_primer',
    caseType: 'clear_match',
    expectedNameContains: 'PVC',
    riskTags: ['spanish', 'consumable', 'cement', 'primer'],
    patterns: ['CEMENTO PVC 8 OZ', 'PRIMER MORADO 16 OZ'],
  ),
];

const englishPlumbingProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'tubular_p_trap',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['drainage', 'tubular', 'professional_pack'],
    patterns: ['1-1/2 P-TRAP', '1-1/4 TUBULAR P TRAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'disposal_install_kit',
    caseType: 'clear_match',
    expectedNameContains: 'Disposal',
    riskTags: ['drainage', 'kitchen', 'professional_pack'],
    patterns: ['DISPOSAL KIT', 'DISPOSAL CONN KIT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'water_heater_connector',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater',
    riskTags: ['water_heater', 'connector', 'professional_pack'],
    patterns: ['3/4 WATER HTR CONN', 'WTR HTR LINE 24'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sump_check_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['pump', 'sump', 'professional_pack'],
    patterns: ['1-1/2 SUMP CHECK', 'PUMP CHECK VALVE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'vacuum_breaker',
    caseType: 'clear_match',
    expectedNameContains: 'Vacuum Breaker',
    riskTags: ['valve', 'hose_bibb', 'professional_pack'],
    patterns: ['HOSE BIBB VAC BRKR', 'VACUUM BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'washer_hose',
    caseType: 'clear_match',
    expectedNameContains: 'Washing Machine Hose',
    riskTags: ['supply_line', 'appliance', 'professional_pack'],
    patterns: ['WASHER HOSE 6FT', 'LAUNDRY HOSE PAIR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pipe_strap',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Strap',
    riskTags: ['fastener', 'support', 'professional_pack'],
    patterns: ['3/4 PIPE STRAP', '1/2 2 HOLE STRAP'],
  ),
  ...englishPlumbingStandardRecipes,
];

const englishPlumbingCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'cleanout_part',
    caseType: 'clear_match',
    expectedNameContains: 'Cleanout',
    riskTags: ['drainage', 'cleanout', 'complete_pack'],
    patterns: ['2 CLEANOUT PLUG', '3 CLEANOUT COVER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lav_pop_up',
    caseType: 'clear_match',
    expectedNameContains: 'Pop-Up',
    riskTags: ['drainage', 'lavatory', 'complete_pack'],
    patterns: ['LAV POP UP', 'POP UP DRAIN 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'slip_joint_nut',
    caseType: 'clear_match',
    expectedNameContains: 'Slip Joint',
    riskTags: ['drainage', 'tubular', 'complete_pack'],
    patterns: ['1-1/2 SLIP JOINT NUT', '1-1/4 NUT WASHER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'gas_connector',
    caseType: 'clear_match',
    expectedNameContains: 'Gas Appliance Connector',
    riskTags: ['gas', 'connector', 'complete_pack'],
    patterns: ['1/2 GAS CONNECTOR', 'GAS APPLIANCE CONN 36'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pressure_reducing_valve',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Reducing Valve',
    riskTags: ['valve', 'pressure', 'complete_pack'],
    patterns: ['3/4 PRV', 'PRESS REDUCING VALVE 1IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ice_maker_line',
    caseType: 'clear_match',
    expectedNameContains: 'Ice Maker Supply Line',
    riskTags: ['supply_line', 'appliance', 'complete_pack'],
    patterns: ['ICE MAKER LINE 25FT', 'FRIDGE WATER LINE 10FT'],
  ),
  ...englishPlumbingProfessionalRecipes,
];

const spanishPlumbingProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'trampa_p',
    caseType: 'clear_match',
    expectedNameContains: 'P-Trap',
    riskTags: ['spanish', 'drainage', 'professional_pack'],
    patterns: ['TRAMPA P 1-1/2', 'P TRAP 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'kit_triturador',
    caseType: 'clear_match',
    expectedNameContains: 'Disposal',
    riskTags: ['spanish', 'drainage', 'professional_pack'],
    patterns: ['KIT TRITURADOR', 'CONECTOR DISPOSAL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_calentador',
    caseType: 'clear_match',
    expectedNameContains: 'Water Heater',
    riskTags: ['spanish', 'water_heater', 'professional_pack'],
    patterns: ['CONECTOR CALENTADOR 3/4', 'LINEA CALENTADOR 24'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_bomba',
    caseType: 'clear_match',
    expectedNameContains: 'Check Valve',
    riskTags: ['spanish', 'pump', 'professional_pack'],
    patterns: ['VALVULA CHECK BOMBA', 'SUMP CHECK 1-1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'rompedor_vacio',
    caseType: 'clear_match',
    expectedNameContains: 'Vacuum Breaker',
    riskTags: ['spanish', 'valve', 'professional_pack'],
    patterns: ['ROMPEDOR VACIO', 'VACUUM BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'manguera_lavadora',
    caseType: 'clear_match',
    expectedNameContains: 'Washing Machine Hose',
    riskTags: ['spanish', 'supply_line', 'professional_pack'],
    patterns: ['MANGUERA LAVADORA 6FT', 'MANGUERA LAVANDERIA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'abrazadera_tubo',
    caseType: 'clear_match',
    expectedNameContains: 'Pipe Strap',
    riskTags: ['spanish', 'fastener', 'professional_pack'],
    patterns: ['ABRAZADERA TUBO 3/4', 'SOPORTE TUBO 1/2'],
  ),
  ...spanishPlumbingStandardRecipes,
];

const spanishPlumbingCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'tapon_limpieza',
    caseType: 'clear_match',
    expectedNameContains: 'Cleanout',
    riskTags: ['spanish', 'drainage', 'cleanout', 'complete_pack'],
    patterns: ['TAPON CLEANOUT 2', 'CUBIERTA CLEANOUT 3'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'drenaje_pop_up',
    caseType: 'clear_match',
    expectedNameContains: 'Pop-Up',
    riskTags: ['spanish', 'drainage', 'lavatory', 'complete_pack'],
    patterns: ['LAV POP UP DRENAJE', 'DRENAJE POP UP 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tuerca_slip_joint',
    caseType: 'clear_match',
    expectedNameContains: 'Slip Joint',
    riskTags: ['spanish', 'drainage', 'tubular', 'complete_pack'],
    patterns: ['TUERCA SLIP JOINT 1-1/2', 'NUT WASHER 1-1/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_gas',
    caseType: 'clear_match',
    expectedNameContains: 'Gas Appliance Connector',
    riskTags: ['spanish', 'gas', 'connector', 'complete_pack'],
    patterns: ['CONECTOR GAS 1/2', 'GAS APPLIANCE CONN 36'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'valvula_prv',
    caseType: 'clear_match',
    expectedNameContains: 'Pressure Reducing Valve',
    riskTags: ['spanish', 'valve', 'pressure', 'complete_pack'],
    patterns: ['VALVULA PRV 3/4', 'PRESS REDUCING VALVE 1IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'linea_hielera',
    caseType: 'clear_match',
    expectedNameContains: 'Ice Maker Supply Line',
    riskTags: ['spanish', 'supply_line', 'appliance', 'complete_pack'],
    patterns: ['LINEA ICE MAKER 25FT', 'FRIDGE WATER LINE 10FT'],
  ),
  ...spanishPlumbingProfessionalRecipes,
];

const englishElectricalCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'old_work_box',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Old Work',
    tradeScope: 'Electrical',
    riskTags: [
      'electrical',
      'box',
      'old_work',
      'dangerous_word',
      'generated_batch',
    ],
    patterns: ['1G OLD WORK BOX', '2G REMOD BOX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'nm_b_wire',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'NM-B',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'wire', 'romex', 'size'],
    patterns: ['12/2 NM-B WIRE', '14/2 ROMEX 25FT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'emt_connector',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'EMT',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'emt', 'connector', 'conduit'],
    patterns: ['1/2 EMT SS CONN', '3/4 EMT CONNECTOR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'wire_nut',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wire Connector',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'connector', 'wire_nut'],
    patterns: ['YEL WIRE NUT', 'RED TWIST CONN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'gfci_receptacle',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'GFCI',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'gfci', 'service_truck'],
    patterns: ['15A GFCI RECPT WHITE', '20 AMP GFI OUTLET'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'single_pole_breaker',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Breaker',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'breaker', 'panel', 'service_truck'],
    patterns: ['20A 1P BRKR', '15 AMP CIRCUIT BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'electrical_tape',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Electrical Tape',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'tape', 'dangerous_word', 'service_truck'],
    patterns: ['3/4 ELEC TAPE BLACK', '1IN ELECTRICAL TAPE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lever_connector',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Lever Connector',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'connector', 'lever_connector', 'service_truck'],
    patterns: ['3 PORT LEVER CONNECTOR', '2 PORT LEVER WIRE CONN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'anti_short_bushing',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Anti Short Bushing',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'bushing', 'mc', 'service_truck'],
    patterns: ['MC ANTI SHORT BUSHING', '100PK ANTI SHORT BUSH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toggle_switch',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'switch', 'service_truck'],
    patterns: ['SP TOGGLE SWITCH', '3WAY WALL SWITCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'decorator_wall_plate',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wall Plate',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'plate', 'trim_out', 'service_truck'],
    patterns: ['1G DECORA WALL PLATE', '2 GANG DECORATOR PLATE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_pvc_conduit',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['electrical', 'dangerous_word', 'pvc', 'cross_trade'],
    patterns: ['PVC COND 3/4', '3/4 PVC CPLG'],
  ),
];

const spanishElectricalCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'caja_remodelacion',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Old Work',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'box', 'generated_batch'],
    patterns: ['CAJA REMODEL 1G', 'CAJA ELECTRICA 2G'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cable_nm_b',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'NM-B',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'wire'],
    patterns: ['CABLE 12/2 NM-B', 'CABLE ROMEX 14/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_emt',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'EMT',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'emt'],
    patterns: ['CONECTOR EMT 1/2', 'CONECTOR EMT 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tuerca_cable',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wire Connector',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'wire_nut'],
    patterns: ['CONECTOR CABLE AMARILLO', 'WIRE NUT ROJO'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'receptaculo_gfci',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'GFCI',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'device', 'gfci'],
    patterns: ['15A RECEPTACULO GFCI', '20A TOMACORRIENTE GFI'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'breaker_un_polo',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Breaker',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'breaker'],
    patterns: ['BREAKER UN POLO 20A', 'DISYUNTOR 1P 15A'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cinta_electrica',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Electrical Tape',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'tape'],
    patterns: ['CINTA ELECTRICA 3/4', 'CINTA AISLANTE NEGRA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conector_palanca',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Lever Connector',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'lever_connector'],
    patterns: ['CONECTOR PALANCA 3 PUERTOS', 'CONECTOR DE PALANCA 2P'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'bushing_anti_corto',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Anti Short Bushing',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'bushing'],
    patterns: ['BUSHING ANTI CORTO MC', 'ANTI CORTO 100PK'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'interruptor_toggle',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'switch'],
    patterns: ['INTERRUPTOR TOGGLE SP', 'INTERRUPTOR 3WAY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'placa_decorador',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Wall Plate',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'plate'],
    patterns: ['PLACA DECORA 1G', 'PLACA DECORADOR 2 GANG'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pvc_conducto_generico',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['spanish', 'electrical', 'dangerous_word', 'pvc'],
    patterns: ['PVC COND 3/4', 'ACOPLE PVC 3/4'],
  ),
];

const englishElectricalStandardRecipes = [
  ...englishElectricalCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'romex_staple',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Cable Staple',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'fastener', 'staple', 'standard_pack'],
    patterns: ['1/2 ROMEX STAPLE', '3/4 CABLE STAPLE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ground_clamp',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'grounding', 'clamp', 'standard_pack'],
    patterns: ['5/8 GROUND CLAMP', 'GRD ROD CLAMP 1/2'],
  ),
];

const englishElectricalProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'double_pole_breaker',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Double-Pole',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'breaker', 'professional_pack'],
    patterns: ['30A 2P BRKR', '50 AMP DOUBLE POLE BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'afci_breaker',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'AFCI',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'breaker', 'afci', 'professional_pack'],
    patterns: ['20A AFCI BRKR', '15 AMP ARC FAULT BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'toggle_switch',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'switch', 'professional_pack'],
    patterns: ['SP TOGGLE SWITCH', '3WAY WALL SWITCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dimmer_switch',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Dimmer',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'device', 'dimmer', 'professional_pack'],
    patterns: ['LED DIMMER SWITCH', '3WAY LED DIMMER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'junction_box',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Junction Box',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'box', 'junction', 'professional_pack'],
    patterns: ['4IN SQ J BOX', '4-11/16 JUNCTION BOX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ground_rod',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground Rod',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'grounding', 'professional_pack'],
    patterns: ['5/8 GROUND ROD 8FT', '1/2 GRD ROD 8FT'],
  ),
  ...englishElectricalStandardRecipes,
];

const spanishElectricalStandardRecipes = [
  ...spanishElectricalCoreRecipes,
  WorkSupplyFixtureRecipe(
    slug: 'grapa_romex',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Cable Staple',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'fastener', 'standard_pack'],
    patterns: ['GRAPA ROMEX 1/2', 'GRAPA CABLE 3/4'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'abrazadera_tierra',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'grounding', 'standard_pack'],
    patterns: ['ABRAZADERA TIERRA 5/8', 'CLAMP TIERRA 1/2'],
  ),
];

const spanishElectricalProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'breaker_doble',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Double-Pole',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'breaker', 'professional_pack'],
    patterns: ['30A BREAKER 2P', '50 AMP DOUBLE POLE BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'breaker_afci',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'AFCI',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'breaker', 'professional_pack'],
    patterns: ['20A BREAKER AFCI', '15 AMP ARC FAULT BREAKER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'interruptor_toggle',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Switch',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'switch', 'professional_pack'],
    patterns: ['INTERRUPTOR TOGGLE SP', 'INTERRUPTOR 3WAY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dimmer_led',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Dimmer',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'dimmer', 'professional_pack'],
    patterns: ['DIMMER LED', 'INTERRUPTOR DIMMER 3WAY'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'caja_junction',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Junction Box',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'box', 'professional_pack'],
    patterns: ['CAJA JUNCTION 4IN', 'CAJA J BOX 4-11/16'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'varilla_tierra',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Ground Rod',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'grounding', 'professional_pack'],
    patterns: ['VARILLA TIERRA 5/8 8FT', 'GROUND ROD 1/2 8FT'],
  ),
  ...spanishElectricalStandardRecipes,
];

const englishHvacCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'pleated_filter',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Air Filter',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'filter', 'dangerous_word', 'size', 'generated_batch'],
    patterns: ['20X25X1 AIR FILTER', '16X20X1 FURNACE FILTER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'foil_tape',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Foil Tape',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'tape', 'foil', 'dangerous_word'],
    patterns: ['2IN FOIL TAPE', '3 HVAC TAPE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sheet_metal_screw',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Sheet Metal Screw',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'fastener', 'sheet_metal_screw'],
    patterns: ['#8 X 1/2 ZIP SCREW', '#10 X 1 SHEET MTL SCR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condensate_coupling',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'pvc', 'cross_trade'],
    patterns: ['3/4 COND PVC CPLG', '1 PVC DRAIN COUP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dual_run_capacitor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Capacitor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'capacitor', 'controls', 'service_truck'],
    patterns: ['35/5 DUAL RUN CAP', '40/5 440V CAP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hvac_contactor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Contactor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'contactor', 'controls', 'service_truck'],
    patterns: ['30A 2P CONTACTOR', '40 AMP HVAC CONTACTOR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condensate_pump',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate Pump',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'pump', 'service_truck'],
    patterns: ['115V COND PUMP', 'CONDENSATE PUMP 230V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pan_tabs',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Drain Tablets',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'condensate', 'treatment', 'service_truck'],
    patterns: ['PAN TABS', 'COND DRAIN TABS'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'flex_duct',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flex Duct',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'duct', 'airflow', 'service_truck'],
    patterns: ['6IN R6 FLEX DUCT', '8 IN INS FLEX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'start_collar',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Duct Takeoff',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'duct', 'takeoff', 'service_truck'],
    patterns: ['6IN START COLLAR', '8 IN DUCT TAKEOFF'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'flame_sensor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flame Sensor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'flame_sensor', 'service_truck'],
    patterns: ['UNIV FLAME SENSOR', 'STRAIGHT FLAME ROD'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hot_surface_ignitor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Ignitor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'ignitor', 'service_truck'],
    patterns: ['UNIV HSI IGNITOR', '120V HOT SURF IGN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'thermostat_wire',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Thermostat Wire',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'low_voltage', 'thermostat_wire', 'service_truck'],
    patterns: ['18/5 STAT WIRE', '18/8 TSTAT WIRE'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'humidifier_water_panel',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Water Panel',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'humidifier', 'iaq', 'service_truck'],
    patterns: ['MODEL 10 HUMIDIFIER PAD', 'MODEL 35 WATER PANEL'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'dangerous_filter',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['hvac', 'dangerous_word', 'filter', 'cross_trade'],
    patterns: ['FILTER', '20X25X1 FILTER'],
  ),
];

const spanishHvacCoreRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'filtro_aire',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Air Filter',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'filter', 'generated_batch'],
    patterns: ['FILTRO AIRE 20X25X1', 'FILTRO HVAC 16X20X1'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cinta_aluminio',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Foil Tape',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'tape'],
    patterns: ['CINTA ALUMINIO 2IN', 'CINTA HVAC 3IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'tornillo_lamina',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Sheet Metal Screw',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'fastener'],
    patterns: ['TORNILLO LAMINA #8', 'TORNILLO METAL #10'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'acople_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate', 'pvc'],
    patterns: ['ACOPLE PVC COND 3/4', 'ACOPLE DRENAJE PVC 1'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'capacitor_doble',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Capacitor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'capacitor'],
    patterns: ['35/5 CAPACITOR DOBLE', '40/5 CAP 440V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'contactor_hvac',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Contactor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'contactor'],
    patterns: ['CONTACTOR HVAC 30A', 'CONTACTOR 2P 40A'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'bomba_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condensate Pump',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate', 'pump'],
    patterns: ['BOMBA CONDENSADO 115V', 'BOMBA COND 230V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pastillas_condensado',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Drain Tablets',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condensate'],
    patterns: ['PASTILLAS BANDEJA', 'TABLETAS DRENAJE COND'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ducto_flexible',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flex Duct',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'duct'],
    patterns: ['DUCTO FLEX 6IN R6', 'FLEX AISLADO 8IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'collarin_arranque',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Duct Takeoff',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'duct'],
    patterns: ['COLLARIN ARRANQUE 6IN', 'TOMA DUCTO 8IN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'sensor_flama',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flame Sensor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'furnace'],
    patterns: ['SENSOR FLAMA UNIV', 'VARILLA FLAMA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ignitor_hsi',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Ignitor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'ignitor'],
    patterns: ['IGNITOR HSI UNIV', 'IGNITOR SUPERFICIE 120V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cable_termostato',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Thermostat Wire',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'thermostat_wire'],
    patterns: ['CABLE TERMOSTATO 18/5', 'CABLE TSTAT 18/8'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'panel_humidificador',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Water Panel',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'humidifier', 'iaq'],
    patterns: ['PANEL HUMIDIFICADOR MODELO 10', 'PAD HUMIDIFICADOR MODELO 35'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'filtro_generico',
    caseType: 'ambiguous_review',
    expectedTrade: '',
    expectedNameContains: '',
    tradeScope: '',
    expectUnknown: true,
    maxConfidence: .81,
    riskTags: ['spanish', 'hvac', 'dangerous_word', 'filter'],
    patterns: ['FILTRO', 'FILTRO 20X25X1'],
  ),
];

const englishHvacStandardRecipes = [...englishHvacCoreRecipes];

const spanishHvacStandardRecipes = [...spanishHvacCoreRecipes];
