import 'work_supply_catalog_blueprint_model.dart';

const hvacResidentialCoreFamilies = [
  CatalogFamily(
    slug: 'pleated_air_filter',
    category: 'Filters',
    system: 'Forced Air',
    itemType: 'Air Filter',
    material: 'pleated media',
    unit: 'each',
    sizes: ['16x20x1', '20x20x1', '20x25x1'],
    nameTemplate: '{size} Pleated HVAC Air Filter',
    aliasTemplates: ['{size} air filter', '{size} furnace filter'],
    receiptTemplates: ['FILTER {size}', '{size} AIR FILTER'],
    negativeTokens: ['oil filter', 'water filter', 'pool filter'],
  ),
  CatalogFamily(
    slug: 'foil_hvac_tape',
    category: 'Duct Sealing',
    system: 'Ductwork',
    itemType: 'Foil Tape',
    material: 'aluminum foil',
    unit: 'roll',
    sizes: ['2 in', '3 in'],
    nameTemplate: '{size} UL Listed HVAC Foil Tape',
    aliasTemplates: ['{size} foil tape', '{size} hvac tape'],
    receiptTemplates: ['{size} FOIL TAPE', '{size} HVAC TAPE'],
    negativeTokens: ['electrical tape', 'drywall tape', 'thread seal tape'],
  ),
  CatalogFamily(
    slug: 'sheet_metal_screw_hex',
    category: 'Fasteners',
    system: 'Sheet Metal',
    itemType: 'Sheet Metal Screw',
    material: 'zinc-plated steel',
    unit: 'pack',
    sizes: ['#8 x 1/2 in', '#8 x 3/4 in', '#10 x 1 in'],
    nameTemplate: '{size} Hex Head Sheet Metal Screw',
    aliasTemplates: ['{size} zip screw', '{size} sheet metal screw'],
    receiptTemplates: ['{size} ZIP SCREW', '{size} SHEET MTL SCR'],
    negativeTokens: ['wood screw', 'tapcon', 'drywall screw'],
  ),
  CatalogFamily(
    slug: 'condensate_pvc_coupling',
    category: 'Condensate Drain',
    system: 'PVC Condensate',
    itemType: 'Coupling',
    material: 'PVC',
    unit: 'each',
    sizes: ['3/4 in', '1 in'],
    nameTemplate: '{size} PVC Condensate Coupling',
    aliasTemplates: ['{size} condensate coupling', '{size} PVC drain cplg'],
    receiptTemplates: ['{size} COND PVC CPLG', '{size} PVC DRAIN COUP'],
    negativeTokens: ['electrical conduit', 'pressure fitting', 'DWV'],
  ),
  CatalogFamily(
    slug: 'dual_run_capacitor',
    category: 'Electrical Controls',
    system: 'Air Conditioning',
    itemType: 'Dual Run Capacitor',
    material: 'metalized polypropylene',
    unit: 'each',
    sizes: ['35/5 mfd', '40/5 mfd', '45/5 mfd'],
    nameTemplate: '{size} 440V Dual Run Capacitor',
    aliasTemplates: ['{size} dual run cap', '{size} ac capacitor'],
    receiptTemplates: ['{size} DUAL RUN CAP', '{size} 440V CAP'],
    negativeTokens: ['start capacitor', 'battery capacitor', 'plumbing cap'],
  ),
  CatalogFamily(
    slug: 'definite_purpose_contactor',
    category: 'Electrical Controls',
    system: 'Air Conditioning',
    itemType: 'Contactor',
    material: 'electrical assembly',
    unit: 'each',
    sizes: ['30 amp', '40 amp', '50 amp'],
    nameTemplate: '{size} 2 Pole 24V HVAC Contactor',
    aliasTemplates: ['{size} contactor', '{size} compressor contactor'],
    receiptTemplates: ['{size} 2P CONTACTOR', '{size} HVAC CONTACTOR'],
    negativeTokens: ['light switch', 'breaker', 'relay only'],
  ),
  CatalogFamily(
    slug: 'condensate_pump',
    category: 'Condensate Drain',
    system: 'Condensate',
    itemType: 'Condensate Pump',
    material: 'plastic pump assembly',
    unit: 'each',
    sizes: ['115V', '230V'],
    nameTemplate: '{size} Condensate Pump',
    aliasTemplates: ['{size} condensate pump', '{size} little pump'],
    receiptTemplates: ['{size} COND PUMP', '{size} CONDENSATE PUMP'],
    negativeTokens: ['sump pump', 'well pump', 'utility pump'],
  ),
  CatalogFamily(
    slug: 'condensate_drain_tablets',
    category: 'Condensate Drain',
    system: 'Condensate',
    itemType: 'Drain Treatment',
    material: 'treatment tablets',
    unit: 'pack',
    sizes: ['standard pack', 'jar'],
    nameTemplate: '{size} Condensate Drain Tablets',
    aliasTemplates: ['{size} pan tabs', '{size} condensate tablets'],
    receiptTemplates: ['{size} PAN TABS', '{size} DRAIN TABS'],
    negativeTokens: ['pool tablets', 'dishwasher tablets', 'medicine'],
  ),
  CatalogFamily(
    slug: 'insulated_flex_duct',
    category: 'Ductwork',
    system: 'Airflow',
    itemType: 'Flex Duct',
    material: 'insulated flexible duct',
    unit: 'each',
    sizes: ['6 in', '8 in', '10 in'],
    nameTemplate: '{size} R6 Insulated Flex Duct',
    aliasTemplates: ['{size} flex duct', '{size} insulated flex'],
    receiptTemplates: ['{size} R6 FLEX DUCT', '{size} INS FLEX'],
    negativeTokens: ['dryer vent', 'foil tape', 'rigid pipe'],
  ),
  CatalogFamily(
    slug: 'start_collar',
    category: 'Ductwork',
    system: 'Airflow',
    itemType: 'Start Collar',
    material: 'galvanized steel',
    unit: 'each',
    sizes: ['6 in', '8 in', '10 in'],
    nameTemplate: '{size} Galvanized Start Collar',
    aliasTemplates: ['{size} start collar', '{size} duct takeoff'],
    receiptTemplates: ['{size} START COLLAR', '{size} DUCT TAKEOFF'],
    negativeTokens: ['pipe collar', 'animal collar', 'plumbing adapter'],
  ),
  CatalogFamily(
    slug: 'furnace_flame_sensor',
    category: 'Heating Controls',
    system: 'Gas Furnace',
    itemType: 'Flame Sensor',
    material: 'ceramic and steel',
    unit: 'each',
    sizes: ['universal', 'straight rod'],
    nameTemplate: '{size} Furnace Flame Sensor',
    aliasTemplates: ['{size} flame sensor', '{size} flame rod'],
    receiptTemplates: ['{size} FLAME SENSOR', '{size} FLAME ROD'],
    negativeTokens: ['thermocouple', 'temperature probe', 'gas valve'],
  ),
  CatalogFamily(
    slug: 'hot_surface_ignitor',
    category: 'Heating Controls',
    system: 'Gas Furnace',
    itemType: 'Hot Surface Ignitor',
    material: 'silicon nitride',
    unit: 'each',
    sizes: ['universal', '80V', '120V'],
    nameTemplate: '{size} Hot Surface Ignitor',
    aliasTemplates: ['{size} hsi ignitor', '{size} furnace igniter'],
    receiptTemplates: ['{size} HSI IGNITOR', '{size} HOT SURF IGN'],
    negativeTokens: ['spark plug', 'grill ignitor', 'pilot assembly'],
  ),
  CatalogFamily(
    slug: 'thermostat_wire',
    category: 'Electrical Controls',
    system: 'Low Voltage',
    itemType: 'Thermostat Wire',
    material: 'copper',
    unit: 'roll',
    sizes: ['18/5', '18/7', '18/8'],
    nameTemplate: '{size} Thermostat Wire',
    aliasTemplates: ['{size} stat wire', '{size} tstat cable'],
    receiptTemplates: ['{size} TSTAT WIRE', '{size} THERMOSTAT WIRE'],
    negativeTokens: ['nm-b', 'speaker wire', 'security cable'],
  ),
  CatalogFamily(
    slug: 'humidifier_water_panel',
    category: 'Indoor Air Quality',
    system: 'Humidifier',
    itemType: 'Water Panel',
    material: 'coated media',
    unit: 'each',
    sizes: ['model 10', 'model 35', 'model 45'],
    nameTemplate: '{size} Humidifier Water Panel',
    aliasTemplates: ['{size} humidifier pad', '{size} water panel'],
    receiptTemplates: ['{size} HUMIDIFIER PAD', '{size} WATER PANEL'],
    negativeTokens: ['air filter', 'water filter', 'furnace panel'],
  ),
];

const hvacResidentialStandardFamilies = [
  ...hvacResidentialCoreFamilies,
  CatalogFamily(
    slug: 'liquid_line_filter_drier',
    category: 'Refrigerant Service',
    system: 'Line Set',
    itemType: 'Filter Drier',
    material: 'copper and desiccant',
    unit: 'each',
    sizes: ['1/4 in', '3/8 in', '1/2 in'],
    nameTemplate: '{size} Liquid Line Filter Drier',
    aliasTemplates: ['{size} filter drier', '{size} liquid line drier'],
    receiptTemplates: ['{size} FILTER DRIER', '{size} LIQ LINE DRIER'],
    negativeTokens: ['air filter', 'water filter', 'oil filter'],
  ),
  CatalogFamily(
    slug: 'service_valve_cap',
    category: 'Refrigerant Service',
    system: 'Service Port',
    itemType: 'Service Valve Cap',
    material: 'brass',
    unit: 'pack',
    sizes: ['1/4 in', '5/16 in'],
    nameTemplate: '{size} Refrigerant Service Valve Cap',
    aliasTemplates: ['{size} service cap', '{size} valve cap'],
    receiptTemplates: ['{size} SERVICE CAP', '{size} VALVE CAP'],
    negativeTokens: ['plumbing cap', 'pipe cap', 'wire cap'],
  ),
  CatalogFamily(
    slug: 'condensate_trap',
    category: 'Condensate Drain',
    system: 'Condensate',
    itemType: 'Condensate Trap',
    material: 'PVC',
    unit: 'each',
    sizes: ['3/4 in', '1 in'],
    nameTemplate: '{size} PVC Condensate Trap',
    aliasTemplates: ['{size} condensate trap', '{size} ez trap'],
    receiptTemplates: ['{size} COND TRAP', '{size} PVC EZ TRAP'],
    negativeTokens: ['sink trap', 'p-trap', 'animal trap'],
  ),
];

const hvacResidentialProfessionalFamilies = [
  ...hvacResidentialStandardFamilies,
  CatalogFamily(
    slug: 'furnace_pressure_switch',
    category: 'Heating Controls',
    system: 'Gas Furnace',
    itemType: 'Pressure Switch',
    material: 'plastic diaphragm',
    unit: 'each',
    sizes: ['universal', '-0.40 wc', '-0.60 wc'],
    nameTemplate: '{size} Furnace Pressure Switch',
    aliasTemplates: ['{size} pressure switch', '{size} draft switch'],
    receiptTemplates: ['{size} PRESS SWITCH', '{size} DRAFT SWITCH'],
    negativeTokens: ['water pressure switch', 'well switch', 'air switch'],
  ),
  CatalogFamily(
    slug: 'furnace_limit_switch',
    category: 'Heating Controls',
    system: 'Gas Furnace',
    itemType: 'Limit Switch',
    material: 'temperature control',
    unit: 'each',
    sizes: ['150F', '180F', '200F'],
    nameTemplate: '{size} Furnace Limit Switch',
    aliasTemplates: ['{size} limit switch', '{size} fan limit'],
    receiptTemplates: ['{size} LIMIT SWITCH', '{size} FAN LIMIT'],
    negativeTokens: ['light switch', 'float switch', 'disconnect'],
  ),
  CatalogFamily(
    slug: 'blower_motor',
    category: 'Motors',
    system: 'Air Handler',
    itemType: 'Blower Motor',
    material: 'electric motor',
    unit: 'each',
    sizes: ['1/3 hp', '1/2 hp', '3/4 hp'],
    nameTemplate: '{size} PSC Blower Motor',
    aliasTemplates: ['{size} blower motor', '{size} furnace motor'],
    receiptTemplates: ['{size} BLOWER MOTOR', '{size} FURN MOTOR'],
    negativeTokens: ['condenser fan motor', 'pump motor', 'garage opener'],
  ),
  CatalogFamily(
    slug: 'condenser_fan_motor',
    category: 'Motors',
    system: 'Condensing Unit',
    itemType: 'Condenser Fan Motor',
    material: 'electric motor',
    unit: 'each',
    sizes: ['1/6 hp', '1/4 hp', '1/3 hp'],
    nameTemplate: '{size} Condenser Fan Motor',
    aliasTemplates: ['{size} condenser motor', '{size} outdoor fan motor'],
    receiptTemplates: ['{size} COND FAN MOTOR', '{size} OD FAN MOTOR'],
    negativeTokens: ['blower motor', 'bath fan', 'ceiling fan'],
  ),
  CatalogFamily(
    slug: 'line_set_insulation',
    category: 'Refrigerant Line',
    system: 'Line Set',
    itemType: 'Line Set Insulation',
    material: 'elastomeric foam',
    unit: 'length',
    sizes: ['3/4 in', '7/8 in', '1-1/8 in'],
    nameTemplate: '{size} Refrigerant Line Set Insulation',
    aliasTemplates: ['{size} line insulation', '{size} armaflex'],
    receiptTemplates: ['{size} LINE INSUL', '{size} ARMAFLEX'],
    negativeTokens: ['pipe insulation plumbing', 'duct insulation', 'wire'],
  ),
];
