import 'work_supply_parser_qa_fixture_recipes.dart';

const englishHvacProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'flame_sensor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flame Sensor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'flame_sensor', 'professional_pack'],
    patterns: ['UNIV FLAME SENSOR', 'STRAIGHT FLAME ROD'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'hot_surface_ignitor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Ignitor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'ignitor', 'professional_pack'],
    patterns: ['UNIV HSI IGNITOR', '120V HOT SURF IGN'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'pressure_switch',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Pressure Switch',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'pressure_switch', 'professional_pack'],
    patterns: ['UNIV PRESS SWITCH', '-0.60 WC DRAFT SWITCH'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'limit_switch',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Limit Switch',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'furnace', 'limit_switch', 'professional_pack'],
    patterns: ['180F LIMIT SWITCH', '200F FAN LIMIT'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'blower_motor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Blower Motor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'motor', 'blower', 'professional_pack'],
    patterns: ['1/2 HP BLOWER MOTOR', '1/3 HP FURN MOTOR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'condenser_fan_motor',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condenser Fan Motor',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'motor', 'condenser', 'professional_pack'],
    patterns: ['1/4 HP COND FAN MOTOR', '1/3 HP OD FAN MOTOR'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'line_set_insulation',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Insulation',
    tradeScope: 'HVAC',
    riskTags: ['hvac', 'line_set', 'insulation', 'professional_pack'],
    patterns: ['3/4 LINE INSUL', '7/8 ARMAFLEX'],
  ),
  ...englishHvacStandardRecipes,
];

const spanishHvacProfessionalRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'sensor_flama',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Flame Sensor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'furnace', 'professional_pack'],
    patterns: ['SENSOR FLAMA UNIV', 'VARILLA FLAMA'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ignitor_hsi',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Ignitor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'ignitor', 'professional_pack'],
    patterns: ['IGNITOR HSI UNIV', 'IGNITOR SUPERFICIE 120V'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'switch_presion',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Pressure Switch',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'pressure_switch', 'professional_pack'],
    patterns: ['SWITCH PRESION UNIV', 'INTERRUPTOR PRESION -0.60'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'switch_limite',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Limit Switch',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'limit_switch', 'professional_pack'],
    patterns: ['SWITCH LIMITE 180F', 'LIMITE VENTILADOR 200F'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'motor_blower',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Blower Motor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'motor', 'professional_pack'],
    patterns: ['MOTOR BLOWER 1/2 HP', 'MOTOR FURN 1/3 HP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'motor_condensador',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Condenser Fan Motor',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'condenser_motor', 'professional_pack'],
    patterns: ['MOTOR COND FAN 1/4 HP', 'MOTOR VENT EXTERIOR 1/3 HP'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'aislamiento_linea',
    caseType: 'clear_match',
    expectedTrade: 'HVAC',
    expectedNameContains: 'Insulation',
    tradeScope: 'HVAC',
    riskTags: ['spanish', 'hvac', 'insulation', 'professional_pack'],
    patterns: ['AISLAMIENTO LINEA 3/4', 'ARMAFLEX 7/8'],
  ),
  ...spanishHvacStandardRecipes,
];
