import 'work_supply_parser_qa_fixture_recipes.dart';

const englishElectricalCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'in_use_cover',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'In-Use Cover',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'weatherproof', 'cover', 'complete_pack'],
    patterns: ['1G IN USE COVER', '2G WP BUBBLE COVER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'weatherproof_box',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Weatherproof',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'weatherproof', 'box', 'complete_pack'],
    patterns: ['1G WP BOX', '2G OUTDOOR BOX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'ac_disconnect',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Disconnect',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'disconnect', 'hvac_overlap', 'complete_pack'],
    patterns: ['60A AC DISC', '30A NON FUSED DISC'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'fan_brace_box',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Fan',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'box', 'fan_brace', 'complete_pack'],
    patterns: ['OLD WORK FAN BRACE BOX', 'NEW WORK FAN RATED BOX'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'panel_filler',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Panel Filler',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'load_center', 'panel_filler', 'complete_pack'],
    patterns: ['1IN PANEL FILLER', '1/2 BRKR FILLER'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'thhn_wire',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'THHN',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'wire', 'thhn', 'complete_pack'],
    patterns: ['12AWG BLACK THHN WIRE', '10 AWG THHN STRD'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'lb_conduit_body',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'LB',
    tradeScope: 'Electrical',
    riskTags: ['electrical', 'conduit', 'pvc', 'complete_pack'],
    patterns: ['3/4 PVC LB BODY', '1IN COND BODY LB'],
  ),
  ...englishElectricalProfessionalRecipes,
];

const spanishElectricalCompleteRecipes = [
  WorkSupplyFixtureRecipe(
    slug: 'cubierta_exterior',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'In-Use Cover',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'weatherproof', 'complete_pack'],
    patterns: ['CUBIERTA USO EXTERIOR 1G', 'TAPA WP BURBUJA 2G'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'caja_exterior',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Weatherproof',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'box', 'complete_pack'],
    patterns: ['CAJA WP 1G', 'CAJA EXTERIOR 2G'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'desconectador_ac',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Disconnect',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'disconnect', 'complete_pack'],
    patterns: ['DESCONECTADOR AC 60A', 'DISC NO FUSIBLE 30A'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'caja_ventilador',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Fan',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'fan_box', 'complete_pack'],
    patterns: ['CAJA VENTILADOR OLD WORK', 'CAJA FAN RATED'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'relleno_panel',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'Panel Filler',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'panel_filler', 'complete_pack'],
    patterns: ['RELLENO PANEL 1IN', 'TAPA BREAKER 1/2'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'cable_thhn',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'THHN',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'wire', 'complete_pack'],
    patterns: ['CABLE THHN NEGRO 12AWG', '10 AWG THHN STRD'],
  ),
  WorkSupplyFixtureRecipe(
    slug: 'conduit_lb',
    caseType: 'clear_match',
    expectedTrade: 'Electrical',
    expectedNameContains: 'LB',
    tradeScope: 'Electrical',
    riskTags: ['spanish', 'electrical', 'conduit', 'complete_pack'],
    patterns: ['CUERPO LB PVC 3/4', 'COND BODY LB 1IN'],
  ),
  ...spanishElectricalProfessionalRecipes,
];
