part of '../../receipts/receipt_ocr_contract.dart';

extension ReceiptOcrParserHandoffContract on ReceiptOcrParserHandoff {
  Map<String, Object?> get privacySafeParserHandoffContract {
    return Map.unmodifiable({
      'schema': 'receipt_ocr_parser_handoff_v1',
      'privacyScope': 'summary_only_no_receipt_content',
      'lineCount': lines.length,
      'orderedLineIds': stableLineIds,
      'primaryFieldLineIds': primaryFieldLineIds,
      'lineIdsByRole': lineIdsByRole,
      'roleByLineId': roleByLineId,
      'parserBucketByLineId': parserBucketByLineId,
      'expenseFamilyByLineId': expenseFamilyByLineId,
      'parserHintByLineId': parserHintByLineId,
      'parserTaskLineIds': parserTaskLineIds,
      'parserTaskCounts': parserTaskCounts,
      'fieldReadinessCounts': fieldReadinessCounts,
      'lineCountsBySourceSection': lineCountsBySourceSection,
      'itemLineCountsBySourceSection': itemLineCountsBySourceSection,
      'sourceSectionCount': sourceSectionCount,
      'sourceSectionNumbersInOrder': sourceSectionNumbersInOrder,
      'uniqueSourceSectionNumbers': uniqueSourceSectionNumbers,
      'sourceSectionContinuityStatus': sourceSectionContinuityStatus,
      'sourceSectionContinuityReviewNeeded': needsSourceSectionContinuityReview,
      'lineIdsBySourceSection': lineIdsBySourceSection,
      'parserReadyLineIdsBySourceSection': parserReadyLineIdsBySourceSection,
      'parserReviewLineIdsBySourceSection': parserReviewLineIdsBySourceSection,
      'lineNumberByLineId': lineNumberByLineId,
      'proofLineReferenceLabelByLineId': proofLineReferenceLabelByLineId,
      'customerProofDefaultVisibilityByLineId':
          customerProofDefaultVisibilityByLineId,
      'customerProofReviewLineIds': customerProofReviewLineIds,
      'customerProofRedactByDefaultLineIds':
          customerProofRedactByDefaultLineIds,
      'customerProofNeedsManualDecisionLineIds':
          customerProofNeedsManualDecisionLineIds,
      'customerProofVisibilityCounts': customerProofVisibilityCounts,
      'customerProofContract': privacySafeCustomerProofContract,
      'clientProofRedactionStatus': clientProofRedactionStatus,
      'clientProofVisibilityCounts': clientProofVisibilityCounts,
      'clientProofTelemetryContract': privacySafeClientProofTelemetryContract,
      'requiredParserFieldStatusCounts': requiredParserFieldStatusCounts,
      'requiredParserFieldStatusLabel': requiredParserFieldStatusLabel,
      'headerRecoveryStatus': headerRecoveryStatus,
      'headerRecoveryDiagnostics': headerRecoveryDiagnostics,
      'missingVendorRecoveryEvidenceLineIds':
          missingVendorRecoveryEvidenceLineIds,
      'vendorReviewStatus': vendorReviewStatus,
      'vendorReviewDiagnostics': vendorReviewDiagnostics,
      'parserReadinessStatus': parserReadinessStatus,
      'merchantIndependentStructureStatus': merchantIndependentStructureStatus,
      'merchantIndependentStructureDiagnostics':
          merchantIndependentStructureDiagnostics,
      'mixedClassificationReadinessStatus': mixedClassificationReadinessStatus,
      'mixedClassificationEvidenceLabel': mixedClassificationEvidenceLabel,
      'mixedClassificationEvidenceDiagnostics':
          mixedClassificationEvidenceDiagnostics,
      'itemExpenseFamilyStatus': itemExpenseFamilyStatus,
      'itemExpenseFamilySummaryLabel': itemExpenseFamilySummaryLabel,
      'itemExpenseFamilyDiagnostics': itemExpenseFamilyDiagnostics,
      'downstreamReadinessStatus': downstreamReadinessStatus,
      'leanLocalOcrReadinessStatus': leanLocalOcrReadinessStatus,
      'leanLocalOcrReadinessCounts': leanLocalOcrReadinessCounts,
      'leanLocalOcrReadinessLabel': leanLocalOcrReadinessLabel,
      'receiptStructureStatus': receiptStructureStatus,
      'lineSequenceStatus': lineSequenceStatus,
      'summaryMathStatus': summaryMathStatus,
      'summaryMathReconciled': summaryMathReconciled,
      'itemAmountLineIds': itemAmountsByLineId.keys.toList(growable: false),
      'parserReadyItemLineIds': parserReadyItemLineIds,
      'reviewItemLineIds': reviewItemLineIds,
      'inventoryPrepLineIds': inventoryPrepLineIds,
      'materialCandidateLineIds': materialCandidateLineIds,
      'fuelCandidateLineIds': fuelCandidateLineIds,
      'fuelReadyLineIds': fuelReadyLineIds,
      'fuelQuantitySignalLineIds': fuelQuantitySignalLineIds,
      'fuelUnitPriceSignalLineIds': fuelUnitPriceSignalLineIds,
      'fuelDetailReadyLineIds': fuelDetailReadyLineIds,
      'vehicleSupplyCandidateLineIds': vehicleSupplyCandidateLineIds,
      'itemLineIdsByExpenseFamily': itemLineIdsByExpenseFamily,
      'presentExpenseFamilies': presentExpenseFamilies,
      'dominantExpenseFamily': dominantExpenseFamily,
      'knownMerchantHeaderCandidateLineIds':
          knownMerchantHeaderCandidateLineIds,
      'unknownMerchantHeaderCandidateLineIds':
          unknownMerchantHeaderCandidateLineIds,
      'timeCandidateLineIds': timeCandidateLineIds,
      'separatorlessMoneyInferenceLineIds': separatorlessMoneyInferenceLineIds,
      'splitCentsMoneyInferenceLineIds': splitCentsMoneyInferenceLineIds,
      'privacySafeLineSummaries': privacySafeLineSummaryMaps,
    });
  }
}
