import '../../../shared/document_engine/document_engine_core.dart';
import 'invoice_ledger_models.dart';
import 'invoice_pdf_template_renderer.dart';
import 'invoice_record.dart';
import 'invoice_template_catalog.dart';

class InvoicePdfPreviewFactory {
  const InvoicePdfPreviewFactory({
    this.renderer = const InvoicePdfTemplateRenderer(),
  });

  final InvoicePdfTemplateRenderer renderer;

  Future<AppGeneratedPdfDocument> buildInvoicePreview() async {
    final createdAt = DateTime.now();
    final template = InvoiceTemplateCatalog.byId('structured-logo');
    final bytes = await renderer.buildDocumentBytes(
      createdAt: createdAt,
      title: 'Invoice',
      documentNumber: 'INV-2409',
      totalLabel: r'$937.74',
      template: template,
    );
    return AppGeneratedPdfDocument(
      kind: AppGeneratedPdfKind.invoice,
      title: 'Time & Materials Invoice Preview',
      fileName: 'maintainiac_invoice_preview.pdf',
      bytes: bytes,
      createdAt: createdAt,
      sourceModule: MaintainiacDocumentSourceModule.invoices,
      shareSubject: 'Maintainiac invoice preview',
      shareText:
          'Invoice PDF generated by Maintainiac. Review before sending to a customer.',
    );
  }

  Future<AppGeneratedPdfDocument> buildRecordPreview({
    required InvoiceRecord record,
  }) async {
    final template = InvoiceTemplateCatalog.byId(record.templateId);
    final bytes = await renderer.buildRecordDocumentBytes(
      record: record,
      template: template,
    );
    final title = record.documentType == InvoiceDocumentType.estimate
        ? 'Estimate ${record.invoiceNumber}'
        : 'Invoice ${record.invoiceNumber}';
    final prefix = record.documentType == InvoiceDocumentType.estimate
        ? 'estimate'
        : 'invoice';
    return AppGeneratedPdfDocument(
      kind: record.documentType == InvoiceDocumentType.estimate
          ? AppGeneratedPdfKind.estimate
          : AppGeneratedPdfKind.invoice,
      title: title,
      fileName: 'maintainiac_${prefix}_${record.invoiceNumber}.pdf',
      bytes: bytes,
      createdAt: record.meta.updatedAt,
      sourceModule: MaintainiacDocumentSourceModule.invoices,
      sourceRecordId: record.id,
      shareSubject: 'Maintainiac $prefix ${record.invoiceNumber}',
      shareText:
          'Document generated by Maintainiac. Review before sending to a customer.',
    );
  }

  Future<AppGeneratedPdfDocument> buildEstimatePreview() async {
    final createdAt = DateTime.now();
    final template = InvoiceTemplateCatalog.byId('structured-logo');
    final bytes = await renderer.buildDocumentBytes(
      createdAt: createdAt,
      title: 'Estimate',
      documentNumber: 'EST-2409',
      totalLabel: r'$937.74',
      template: template,
    );
    return AppGeneratedPdfDocument(
      kind: AppGeneratedPdfKind.estimate,
      title: 'Time & Materials Estimate Preview',
      fileName: 'maintainiac_estimate_preview.pdf',
      bytes: bytes,
      createdAt: createdAt,
      sourceModule: MaintainiacDocumentSourceModule.invoices,
      shareSubject: 'Maintainiac estimate preview',
      shareText:
          'Estimate PDF generated by Maintainiac. Review before sending to a customer.',
    );
  }

  Future<AppGeneratedPdfDocument> buildTemplateSamplePreview({
    required InvoiceTemplateDefinition template,
  }) async {
    final createdAt = DateTime(2026, 6, 15, 10, 30);
    final bytes = await renderer.buildDocumentBytes(
      createdAt: createdAt,
      title: 'Invoice',
      documentNumber: 'INV-1017',
      totalLabel: r'$1,247.62',
      template: template,
    );
    return AppGeneratedPdfDocument(
      kind: AppGeneratedPdfKind.invoice,
      title: '${template.name} Sample Invoice',
      fileName: 'maintainiac_${template.id}_sample.pdf',
      bytes: bytes,
      createdAt: createdAt,
      sourceModule: MaintainiacDocumentSourceModule.invoices,
      shareSubject: 'Maintainiac invoice template sample',
      shareText: 'Sample invoice template generated by Maintainiac.',
    );
  }
}
