part of 'maintainiac_firestore_documents.dart';

Map<String, Object?> _sanitizeExpenseTelemetryMap(Map<String, Object?> source) {
  const allowed = {
    'schema',
    'summaryId',
    'summaryScope',
    'uploadShape',
    'rawEventUploadCount',
    'generatedAtUtc',
    'healthLabel',
    'totalEventCount',
    'pendingUploadCount',
    'uploadedEventCount',
    'eventCounts',
    'platformCounts',
    'deviceTierCounts',
    'storageModeCounts',
    'planStatusCounts',
    'connectionStatusCounts',
    'screenOpenCount',
    'averageTimeSpentSeconds',
    'addExpenseStartedCount',
    'addExpenseCompletedCount',
    'addExpenseAbandonedCount',
    'addExpenseCompletionRate',
    'addExpenseAbandonmentRate',
    'validationErrorCount',
    'saveFailureCount',
    'imageAttachSuccessCount',
    'imageAttachFailureCount',
    'imageAttachFailureRate',
    'ocrStartedCount',
    'ocrCompletedCount',
    'ocrFailedCount',
    'ocrSuccessRate',
    'parserStartedCount',
    'parserCompletedCount',
    'parserNeedsReviewCount',
    'parserFailedCount',
    'parserSuccessRate',
    'parserReviewRate',
    'parserFailureRate',
    'parserCategoryCounts',
    'parserNeedsReviewCategoryCounts',
    'parserFailedCategoryCounts',
    'parserFieldConfidenceCounts',
    'parserCategoryHealthCounts',
    'parserRequiredFieldStatusCounts',
    'parserDownstreamReadinessStatusCounts',
    'parserDownstreamReadinessCounts',
    'ocrParserTaskCounts',
    'ocrFieldReadinessCounts',
    'ocrSourceHandoffStatusCounts',
    'ocrSourceHandoffSignalCounts',
    'ocrSourceStitchSignalCounts',
    'ocrSourceScannerDecisionCounts',
    'ocrSourcePhotoQualityRiskCounts',
    'clientProofRedactionStatusCounts',
    'clientProofVisibilityCounts',
    'receiptSelectedLinePurposeCounts',
    'receiptSelectedLineCountTotal',
    'receiptExcludedLineCountTotal',
    'receiptClientProofReviewLineCountTotal',
    'receiptRedactedLineCountTotal',
    'clientProofRedactionPlanStatusCounts',
    'clientProofVisibleLineCountTotal',
    'clientProofHiddenLineCountTotal',
    'clientProofPlanReviewLineCountTotal',
    'topParserCategory',
    'topParserNeedsReviewCategory',
    'topParserFailedCategory',
    'topParserCategoryHealth',
    'topParserRequiredFieldStatus',
    'topParserDownstreamReadinessStatus',
    'topParserDownstreamReadiness',
    'topOcrParserTask',
    'topOcrFieldReadiness',
    'topOcrSourceHandoffStatus',
    'topOcrSourceHandoffSignal',
    'topOcrSourceStitchSignal',
    'topOcrSourceScannerDecision',
    'topOcrSourcePhotoQualityRisk',
    'topClientProofRedactionStatus',
    'topClientProofVisibility',
    'topReceiptSelectedLinePurpose',
    'topClientProofRedactionPlanStatus',
    'receiptPhotoCoverageStatusCounts',
    'receiptPhotoCoverageReasonCounts',
    'receiptPhotoCoverageNeedsMoreCount',
    'receiptPhotoCoverageNeedsMoreRate',
    'topReceiptPhotoCoverageStatus',
    'topReceiptPhotoCoverageReason',
    'savedPhotoWarningCounts',
    'savedPhotoWarningCauseCounts',
    'savedPhotoWarningSeverityCounts',
    'savedPhotoWarningActionCounts',
    'savedPhotoParserRiskCounts',
    'savedPhotoQualityWarningCount',
    'savedPhotoQualityWarningRate',
    'savedPhotoCriticalWarningCount',
    'savedPhotoCriticalWarningRate',
    'topSavedPhotoWarning',
    'topSavedPhotoWarningCause',
    'topSavedPhotoWarningSeverity',
    'topSavedPhotoWarningActionCode',
    'topSavedPhotoWarningAction',
    'topSavedPhotoParserRisk',
    'preCaptureExposureDecisionCounts',
    'preCaptureExposureAdjustmentCount',
    'preCaptureExposureAdjustmentRate',
    'topPreCaptureExposureDecision',
    'autoExposureDecisionCounts',
    'autoExposureBrightnessCounts',
    'autoExposureCandidateCounts',
    'exposureAssistStatusCounts',
    'autoExposureCandidateFrameCount',
    'manualBrightnessChangeCount',
    'topAutoExposureDecision',
    'topAutoExposureBrightness',
    'topAutoExposureCandidate',
    'topExposureAssistStatus',
    'acceptedPhotoQualityOutcomeCounts',
    'topAcceptedPhotoQualityOutcome',
    'capturedPhotoBrightnessCounts',
    'capturedPhotoSharpnessCounts',
    'capturedPhotoExposureMismatchCounts',
    'capturedPhotoQualitySignalCounts',
    'capturedPhotoBottomBrightnessCounts',
    'capturedPhotoBottomEdgeScoreCounts',
    'capturedPhotoVerticalQualitySignalCounts',
    'topCapturedPhotoBrightness',
    'topCapturedPhotoSharpness',
    'topCapturedPhotoExposureMismatch',
    'topCapturedPhotoQualitySignal',
    'topCapturedPhotoBottomBrightness',
    'topCapturedPhotoBottomEdgeScore',
    'topCapturedPhotoVerticalQualitySignal',
    'nativeCameraEngineCounts',
    'nativeReceiptCameraSurfaceActualCounts',
    'nativeReceiptCameraSurfaceVerificationCounts',
    'nativeCameraIdentityCounts',
    'nativeSettingsContractVersionCounts',
    'nativeControlContractVersionCounts',
    'receiptCloudAssistPlanCounts',
    'receiptLocalOcrModeCounts',
    'receiptParserDepthCounts',
    'receiptParserPackCodeCounts',
    'receiptOptionalLocalParserPackCodeCounts',
    'receiptCloudFallbackParserPackCodeCounts',
    'receiptParserPackAccuracyBandCounts',
    'receiptEstimatedOptionalLocalPackBytesTotal',
    'receiptEstimatedOptionalLocalPackBytesMax',
    'receiptCloudOcrOptionalCount',
    'receiptCloudInventoryOptionalCount',
    'topReceiptParserPackDisclosureLabel',
    'nativeDevicePolicyCounts',
    'nativeCameraWorkloadTierCounts',
    'nativeCameraResolutionTierCounts',
    'nativeRecoveryResumeStatusCounts',
    'nativeRecoveryFreshnessCounts',
    'nativeRecoveryStorageStatusCounts',
    'nativeRecoveryRecoveredPhotoCount',
    'nativeRecoveryMultipleSectionCount',
    'nativeTapFocusControlExpectedCount',
    'nativeContinuousFocusExpectedCount',
    'nativePinchZoomControlExpectedCount',
    'nativeExposureSliderControlExpectedCount',
    'nativeExposureResetControlExpectedCount',
    'nativeSettingsControlExpectedCount',
    'nativeBackControlExpectedCount',
    'nativeTorchControlExpectedCount',
    'nativeSettingsOpenCount',
    'nativePreCaptureExposureAbortCount',
    'nativePreCaptureExposureAbortReasonCounts',
    'nativeZoomGestureStartCount',
    'nativeZoomChangeCount',
    'nativeZoomUnavailableCount',
    'nativeZoomStatusCounts',
    'nativeBackDispatchPathCounts',
    'topNativeCameraEngine',
    'topNativeReceiptCameraSurfaceActual',
    'topNativeReceiptCameraSurfaceVerification',
    'topNativeCameraIdentity',
    'topNativeSettingsContractVersion',
    'topNativeControlContractVersion',
    'topReceiptCloudAssistPlan',
    'topReceiptLocalOcrMode',
    'topReceiptParserDepth',
    'topReceiptParserPackCode',
    'topReceiptOptionalLocalParserPackCode',
    'topReceiptCloudFallbackParserPackCode',
    'topReceiptParserPackAccuracyBand',
    'topNativeDevicePolicy',
    'topNativeCameraWorkloadTier',
    'topNativeCameraResolutionTier',
    'topNativeRecoveryResumeStatus',
    'topNativeRecoveryFreshness',
    'topNativeRecoveryStorageStatus',
    'topNativeRecoveryAction',
    'topNativePreCaptureExposureAbortReason',
    'topNativeZoomStatus',
    'topNativeBackDispatchPath',
    'capabilityPolicyCodeCounts',
    'topCapabilityPolicyCode',
    'nativeCaptureSourcePolicyCounts',
    'topNativeCaptureSourcePolicy',
    'stitchStatusCounts',
    'stitchFallbackReasonCounts',
    'stitchConfidenceBucketCounts',
    'stitchPairDiagnosticCounts',
    'topStitchStatus',
    'topStitchFallbackReason',
    'topStitchConfidenceBucket',
    'topStitchPairDiagnostic',
    'topOcrStoragePolicy',
    'topOcrUsesPreparedSourceBeforeSavedProof',
    'topOcrUsesSavedProofFallback',
    'topReceiptBrainLocalFirstReadiness',
    'topReceiptBrainLocalFirstReadinessAction',
    'topReceiptBrainFirstInstallBoundary',
    'topReceiptBrainFirstInstallBoundaryAction',
    'topReceiptInstallRecommendedDistribution',
    'topReceiptInstallLowStorageImpact',
    'topReceiptLocalOnlyAcceptanceStatus',
    'topReceiptLocalOnlyAcceptanceAction',
    'topNativeLocalOnlyCapturePolicy',
    'parserCategoryReviewActionCounts',
    'parserPackPressureStatusCounts',
    'receiptBrainParserLimitOutcomeCounts',
    'receiptBrainLowStorageDownloadRiskCounts',
    'receiptBrainFullOfflineMustStayOptionalCounts',
    'receiptBrainFullOfflineExceedsBaseGuardrailCounts',
    'receiptBrainBaseLocalReadingAvailableCounts',
    'receiptBrainBaseWorksWithoutCloudAssistCounts',
    'receiptBrainLocalFirstReadinessCounts',
    'receiptBrainLocalFirstReadinessActionCounts',
    'receiptBrainLocalFirstReadinessSummaryCounts',
    'receiptBrainFirstInstallBoundaryCounts',
    'receiptBrainFirstInstallBoundaryActionCounts',
    'receiptBrainFirstInstallCanRunLowStorageCounts',
    'receiptBrainFirstInstallRequiresBaseCapabilityCounts',
    'receiptBrainFirstInstallBoundarySummaryCounts',
    'receiptInstallRequiredSegmentCounts',
    'receiptInstallFullOfflineSegmentCounts',
    'receiptInstallLowStorageImpactCounts',
    'receiptInstallRecommendedDistributionCounts',
    'receiptInstallCameraShellParserFreeCounts',
    'receiptInstallBaseUsefulOnTinyPhonesCounts',
    'receiptInstallOptionalPacksRequireConsentCounts',
    'receiptLocalOnlyAcceptanceStatusCounts',
    'receiptLocalOnlyAcceptanceActionCounts',
    'receiptLocalOnlyBaseFlowCanRunCounts',
    'receiptLocalOnlyBlocksLowStorageCounts',
    'receiptLocalOnlyEvidenceCounts',
    'nativeLocalOnlyCapturePolicyCounts',
    'nativeLocalOnlyBaseFlowCanRunCounts',
    'nativeLocalOnlyHeavyPacksMayBlockCaptureCounts',
    'nativeLocalOnlyCloudAssistMayBlockCaptureCounts',
    'receiptRequiredBaseFootprintStatusCounts',
    'receiptRequiredBaseFootprintCanShipCounts',
    'receiptRequiredBaseFootprintReviewCounts',
    'receiptRequiredBaseFootprintBlockingReasonCounts',
    'receiptRequiredBaseFootprintReviewReasonCounts',
    'ocrStoragePolicyCounts',
    'ocrUsesPreparedSourceBeforeSavedProofCounts',
    'ocrUsesSavedProofFallbackCounts',
    'parserReviewRootCauseCounts',
    'localReceiptParserRoutingCounts',
    'localReceiptParserKeptLocalCount',
    'localReceiptParserOptionalPackOfferCount',
    'localParserEvidenceOutcomeCounts',
    'ocrSourceCaptureSourceSignalCounts',
    'ocrSourceQualityReviewStatusCounts',
    'ocrSourceQualityReviewActionCounts',
    'topParserCategoryReviewAction',
    'topParserPackPressureStatus',
    'topReceiptBrainParserLimitOutcome',
    'topReceiptBrainLowStorageDownloadRisk',
    'topReceiptRequiredBaseFootprintStatus',
    'topReceiptRequiredBaseFootprintBlockingReason',
    'topReceiptRequiredBaseFootprintReviewReason',
    'topParserReviewRootCause',
    'topLocalReceiptParserRouting',
    'topLocalParserEvidenceOutcome',
    'topOcrSourceCaptureSourceSignal',
    'topOcrSourceQualityReviewStatus',
    'topOcrSourceQualityReviewAction',
    'ocrCorrectionOpenedCount',
    'appFilledReceiptLineConfirmedCount',
    'appFilledReceiptLineCorrectedCount',
    'appFilledReceiptLineCorrectionRate',
    'userCorrectionCount',
    'cloudBackupSuccessCount',
    'cloudBackupFailureCount',
    'cloudBackupFailureRate',
    'syncPendingCount',
    'syncedCount',
    'syncFailedCount',
    'syncFailureRate',
    'expenseSummaryQueuedCount',
    'expenseSummaryOcrContractQueuedCount',
    'expenseSummaryOcrContractSkippedCount',
    'expenseSummaryOcrContractSourceCounts',
    'topExpenseSummaryOcrContractSource',
    'expenseSummaryOcrContractSkippedReasonCounts',
    'topExpenseSummaryOcrContractSkippedReason',
    'exportStartedCount',
    'exportCompletedCount',
    'exportBlockedCount',
    'exportFailedCount',
    'exportCompletionRate',
    'exportFailureRate',
    'ocrFailureCauseCounts',
    'topOcrFailureCause',
    'ocrFailureSourceCounts',
    'topOcrFailureSource',
    'topOcrFailureSourceAction',
    'ocrFailureStageCounts',
    'topOcrFailureStage',
    'topOcrFailureStageLabel',
    'failureBreakdowns',
    'recentFailureDetails',
    'eventId',
    'queuedAtUtc',
    'event',
    'featureArea',
    'featureLabel',
    'workflowStep',
    'workflowStepLabel',
    'failedAt',
    'failedAtLabel',
    'confirmedCause',
    'causeLabel',
    'causeStatus',
    'causeStatusLabel',
    'evidence',
    'evidenceLabel',
    'missingEvidence',
    'missingEvidenceLabel',
    'recommendedAction',
    'actionSummary',
    'ocrFailureSource',
    'ocrFailureSourceAction',
    'count',
    'retryCount',
    'abandoned',
    'abandonedCount',
    'platform',
    'deviceTier',
    'appVersion',
    'appVersionCounts',
  };
  return {
    for (final entry in source.entries)
      if (allowed.contains(entry.key))
        entry.key: _sanitizeExpenseTelemetryValue(entry.key, entry.value),
  };
}

Object? _sanitizeExpenseTelemetryValue(String key, Object? value) {
  if (value == null || value is bool) return value;
  if (value is int) {
    if (value < 0) {
      throw ArgumentError.value(value, key, 'Counts must be positive.');
    }
    return value;
  }
  if (value is double) {
    if (value.isNaN || value.isInfinite || value < 0) {
      throw ArgumentError.value(value, key, 'Rates must be finite.');
    }
    return double.parse(value.toStringAsFixed(4));
  }
  if (value is String) {
    if (key == 'generatedAtUtc' || key == 'queuedAtUtc') {
      return _safeIso(value);
    }
    if (key == 'topReceiptParserPackDisclosureLabel') {
      return _ExpenseTelemetryFirestoreRedactor.appGeneratedDisclosureText(
        value,
      );
    }
    if (key.endsWith('Label') ||
        key == 'recommendedAction' ||
        key == 'actionSummary' ||
        key == 'topNativeRecoveryAction') {
      return _ExpenseTelemetryFirestoreRedactor.readableText(value);
    }
    return _ExpenseTelemetryFirestoreRedactor.tokenFor(key, value);
  }
  if (value is Map) {
    final sanitized = <String, Object?>{};
    for (final entry in value.entries) {
      final countKey = _ExpenseTelemetryFirestoreRedactor.mapKeyFor(
        key,
        entry.key.toString(),
      );
      final countValue = entry.value;
      if (countValue is int && countValue >= 0) {
        sanitized[countKey] = countValue;
      }
    }
    return Map.unmodifiable(sanitized);
  }
  if (value is Iterable) {
    return [
      for (final item in value)
        if (item is Map)
          _sanitizeExpenseTelemetryMap(Map<String, Object?>.from(item)),
    ];
  }
  throw ArgumentError.value(value, key, 'Unsupported telemetry summary value.');
}
