class AppGeneratedPdfShareContent {
  const AppGeneratedPdfShareContent({
    required this.subject,
    required this.text,
  });

  final String subject;
  final String text;

  factory AppGeneratedPdfShareContent.invoicePreview() {
    return const AppGeneratedPdfShareContent(
      subject: 'Maintainiac invoice preview',
      text:
          'Invoice PDF generated by Maintainiac. Review before sending to a customer.',
    );
  }

  factory AppGeneratedPdfShareContent.estimatePreview() {
    return const AppGeneratedPdfShareContent(
      subject: 'Maintainiac estimate preview',
      text:
          'Estimate PDF generated by Maintainiac. Review before sending to a customer.',
    );
  }

  factory AppGeneratedPdfShareContent.invoiceRecord({
    required bool isEstimate,
    required String documentNumber,
  }) {
    final prefix = isEstimate ? 'estimate' : 'invoice';
    return AppGeneratedPdfShareContent(
      subject: 'Maintainiac $prefix $documentNumber',
      text:
          'Document generated by Maintainiac. Review before sending to a customer.',
    );
  }

  factory AppGeneratedPdfShareContent.templateSample() {
    return const AppGeneratedPdfShareContent(
      subject: 'Maintainiac invoice template sample',
      text: 'Sample invoice template generated by Maintainiac.',
    );
  }

  factory AppGeneratedPdfShareContent.expenseExport({
    required DateTime rangeStart,
    required DateTime rangeEnd,
    required int receiptCount,
    required int lineCount,
    required String total,
  }) {
    final range = '${_date(rangeStart)} - ${_date(rangeEnd)}';
    return AppGeneratedPdfShareContent(
      subject: 'Maintainiac expense export $range',
      text: [
        'Maintainiac expense export',
        'Date range: $range',
        'Receipts: $receiptCount',
        'Line items: $lineCount',
        'Total: $total',
      ].join('\n'),
    );
  }
}

String _date(DateTime day) => '${day.month}/${day.day}/${day.year}';
