Map<String, Object?> buildExpenseTelemetryCommandCenterOcrStartedMetadata() {
  return {
    'photoCoverageStatuses': {'likelyCutOff': 1, 'likelyComplete': 1},
    'photoCoverageReasons': {
      'native_cut_off_risk': 1,
      'framing_ok_readable': 1,
    },
    'photoCoverageNeedsMoreCount': 1,
    'savedPhotoWarningCounts': {'low_readability_after_save': 1},
    'savedPhotoWarningCauseCounts': {'missing_bottom_edge': 1},
    'savedPhotoWarningSeverityCounts': {'quality': 1},
    'savedPhotoWarningActionCounts': {'review_if_readable': 1},
    'savedPhotoParserRiskCounts': {'ocr_review_if_needed': 1},
    'hasSavedPhotoQualityWarning': true,
    'preCaptureExposureDecisionBuckets': {'brightening_before_capture': 1},
    'preCaptureExposureAdjustmentTotal': 1,
    'preCaptureExposureAbortTotal': 1,
    'preCaptureExposureAbortReasonBuckets': {'too_dark_after_assist': 1},
    'autoExposureDecisionBuckets': {'brightened_preview': 1},
    'autoExposureBrightnessBuckets': {'preview_dim': 1},
    'autoExposureCandidateBuckets': {'stable_receipt_text': 1},
    'exposureAssistStatuses': {'active': 1},
    'autoExposureCandidateFrameTotal': 4,
    'manualBrightnessChangeTotal': 1,
    'tapFocusControlExpectedCount': 0,
    'continuousFocusExpectedCount': 1,
    'pinchZoomControlExpectedCount': 1,
    'exposureSliderControlExpectedCount': 1,
    'exposureResetControlExpectedCount': 1,
    'settingsControlExpectedCount': 1,
    'backControlExpectedCount': 1,
    'torchControlExpectedCount': 1,
    'settingsOpenTotal': 2,
    'zoomGestureStartTotal': 2,
    'zoomChangeTotal': 1,
    'zoomUnavailableTotal': 1,
    'captureReadinessCodeCounts': {'manual_only_quality_review': 1},
    'zoomStatusBuckets': {'zoom_applied': 1},
    'backDispatchPathBuckets': {'top_bar_back_button': 1},
    'acceptedPhotoQualityOutcomeCounts': {'needs_review_before_ocr': 1},
    'capturedPhotoBrightnessBuckets': {'captured_dim': 1},
    'capturedPhotoSharpnessBuckets': {'captured_sharp': 1},
    'capturedPhotoExposureMismatches': {'live_ok_capture_dim': 1},
    'capturedPhotoQualitySignals': {'review_before_saving': 1},
    'capturedPhotoBottomBrightnessBuckets': {'bottom_dim': 1},
    'capturedPhotoBottomEdgeScoreBuckets': {'bottom_edge_usable': 1},
    'capturedPhotoVerticalQualitySignals': {'bottom_darker_than_upper': 1},
    'nativeCameraEngineBuckets': {'cameraX': 1},
    'nativeReceiptCameraSurfaceActual': 'native_fullscreen',
    'nativeReceiptCameraSurfaceVerification': 'verified_native',
    'nativeCameraIdentity': 'camera_x_receipt_surface',
    'nativeControlContractVersionBuckets': {'receipt_native_controls_v1': 1},
    'settingsContractVersion': 'receipt_native_camera_settings_v1',
    'cloudAssistPlan': 'local_ocr_cloud_ocr_cloud_inventory_optional',
    'localOcrMode': 'lean_local_ocr',
    'parserDepth': 'price_only',
    'parserPackCodes': ['core_receipt_text_v1'],
    'optionalLocalParserPackCodes': ['general_expense_lines_v1'],
    'cloudFallbackParserPackCodes': ['cloud_ocr_assist_v1'],
    'parserPackAccuracyBands': {
      'core_receipt_text_v1': 'ocr_text_95_99_when_photo_readable',
    },
    'estimatedOptionalLocalPackBytes': 25165824,
    'userFacingPackDisclosureLabel':
        'Optional local parser add-ons use about 24.0 MB. Cloud OCR/parser fallback needs internet and must be chosen by the user. Accuracy disclosures: core_receipt_text_v1: ocr_text_95_99_when_photo_readable.',
    'cloudOcrOptional': true,
    'cloudInventoryOptional': true,
    'receiptBrainBaseLocalReadingAvailableCounts': {
      'base_local_reader_available': 1,
    },
    'receiptBrainBaseWorksWithoutCloudAssistCounts': {
      'works_without_cloud_assist': 1,
    },
    'receiptBrainLocalFirstReadinessOutcome': 'local_first_ready',
    'receiptBrainLocalFirstReadinessActionOutcome': 'continue_local_first',
    'receiptBrainLocalFirstReadinessSummaryCounts': {
      'base_ready_optional_packs': 1,
    },
    'receiptBrainFirstInstallBoundaryOutcome': 'base_install_small',
    'receiptBrainFirstInstallBoundaryActionCounts': {
      'offer_optional_packs_later': 1,
    },
    'receiptBrainFirstInstallCanRunLowStorageCounts': {
      'can_run_low_storage': 1,
    },
    'receiptBrainFirstInstallRequiresBaseCapabilityCounts': {
      'requires_camera_and_local_ocr': 1,
    },
    'receiptBrainFirstInstallBoundarySummaryCounts': {
      'base_first_optional_after_consent': 1,
    },
    'receiptInstallRequiredSegmentOutcome': 'required_base',
    'receiptInstallFullOfflineSegmentOutcome': 'optional_full_offline',
    'receiptInstallLowStorageImpactOutcome': 'low_storage_safe',
    'receiptInstallRecommendedDistributionOutcome': 'base_plus_optional_packs',
    'receiptInstallCameraShellParserFreeCounts': {
      'camera_shell_parser_free': 1,
    },
    'receiptInstallBaseUsefulOnTinyPhonesCounts': {'tiny_phone_base_useful': 1},
    'receiptInstallOptionalPacksRequireConsentCounts': {
      'optional_packs_require_consent': 1,
    },
    'receiptLocalOnlyAcceptanceStatusOutcome': 'local_only_accepted',
    'receiptLocalOnlyAcceptanceActionOutcome': 'keep_local_only',
    'receiptLocalOnlyBaseFlowCanRunCounts': {'base_flow_can_run': 1},
    'receiptLocalOnlyBlocksLowStorageCounts': {'does_not_block_low_storage': 1},
    'receiptLocalOnlyEvidenceCounts': {'local_ocr_available': 1},
    'nativeLocalOnlyCapturePolicyOutcome': 'native_capture_local_only',
    'nativeLocalOnlyBaseFlowCanRunCounts': {'native_base_can_run': 1},
    'nativeLocalOnlyHeavyPacksMayBlockCaptureCounts': {
      'heavy_packs_optional': 1,
    },
    'nativeLocalOnlyCloudAssistMayBlockCaptureCounts': {
      'cloud_assist_optional': 1,
    },
    'receiptRequiredBaseFootprintStatusOutcome': 'base_within_guardrail',
    'receiptRequiredBaseFootprintCanShipCounts': {'can_ship': 1},
    'receiptRequiredBaseFootprintReviewCounts': {'review_passed': 1},
    'receiptRequiredBaseFootprintBlockingReasonCounts': {'none': 1},
    'receiptRequiredBaseFootprintReviewReasonCounts': {'within_base_budget': 1},
    'ocrStoragePolicyOutcome': 'ocr_clear_source_before_saved_proof_copy',
    'ocrUsesPreparedSourceBeforeSavedProofCounts': {'prepared_source_first': 1},
    'ocrUsesSavedProofFallbackCounts': {'saved_proof_fallback_unused': 1},
    'nativeDevicePolicyBuckets': {'storage_saver_receipt_camera': 1},
    'nativeCameraWorkloadTierBuckets': {'light': 1},
    'nativeCameraResolutionTierBuckets': {'medium': 1},
    'nativeRecoveryResumeStatusBuckets': {'resume_review_started': 1},
    'nativeRecoveryFreshnessBuckets': {'stale': 1},
    'nativeRecoveryStorageStatusBuckets': {'partial_photos_available': 1},
    'nativeRecoveryRecoveredPhotoTotal': 2,
    'nativeRecoveryMultipleSectionCount': 1,
    'capabilityPolicyCodeCounts': {'storage_constrained_small_proofs': 1},
    'nativeCaptureSourcePolicyCounts': {'storage_saver_native': 1},
    'stitchStatus': 'stitched',
    'stitchFallbackReason': 'stitched',
    'stitchConfidenceBucket': 'high',
    'stitchPairDiagnosticCounts': {'zoom_adjusted': 1},
  };
}
