import 'package:maintaniac/shared/widgets/receipt_capture/receipt_native_camera_contract.dart';

ReceiptNativeCaptureResult acceptedNativeCaptureStagingFixture({
  required String sourcePath,
  required DateTime capturedAt,
}) {
  return ReceiptNativeCaptureResult(
    engine: ReceiptNativeCameraEngine.cameraX,
    originalPhotoPaths: [sourcePath],
    temporaryCaptureIds: const ['camera-cache-id'],
    capturedAt: capturedAt,
    captureDiagnostics: const {
      'engine': 'cameraX',
      'deviceTier': 'heavyweight',
      'devicePolicyLabel': 'flagship_receipt_camera',
      'capabilityPolicyCodes': [
        'storage_constrained_small_proofs',
        'heavy_cleanup_policy_limited',
      ],
      'cloudAssistPlan': 'local_ocr_cloud_ocr_cloud_inventory_optional',
      'ocrDecisionPolicy': 'local_default_cloud_optional',
      'localOcrAvailable': true,
      'localOcrMode': 'lean_local_ocr',
      'localOcrDefault': true,
      'cloudOcrOptional': true,
      'cloudInventoryOptional': true,
      'cloudAssistRequiresExplicitChoice': true,
      'cloudAssistRequiresInternet': true,
      'cameraCaptureCloudRequired': false,
      'receiptReviewCloudRequired': false,
      'parserDepth': 'inventoryMatching',
      'localParserScope': 'inventory_matching_local',
      'localCatalogMatchLimit': 250,
      'localInventoryCacheLimit': 1000,
      'cameraResolutionTier': 'max',
      'cameraWorkloadTier': 'flagship',
      'photoByteSize': 256,
      'photoByteSizeBucket': 'tiny_under_350kb',
      'latestCapturedPhotoWidth': 3024,
      'latestCapturedPhotoHeight': 4032,
      'latestCapturedAverageLuma': 102.4,
      'latestCapturedEdgeScore': 18.6,
      'latestCapturedMegapixelBucket': 'high_9mp_to_18mp',
      'latestCapturedByteBucket': 'normal_1mb_to_3mb',
      'latestCapturedBrightnessBucket': 'captured_dim',
      'latestCapturedSharpnessBucket': 'captured_sharp',
      'latestCapturedQualitySignal': 'review_before_saving',
      'latestCapturedExposureMismatch': 'live_ok_capture_dim',
      'torchOn': false,
      'captureQualityMode': 'maximizeQuality',
      'analysisGapMs': 380,
      'readyHoldMs': 520,
      'assistedShotCount': 5,
      'bestShotCandidateCount': 5,
      'maxLiveAnalysisPixels': 2200000,
      'maxCleanupPixels': 14000000,
      'maxStitchOutputPixels': 18000000,
      'maxStitchOutputHeight': 24000,
      'latestBrightnessBucket': 'dark_assisted',
      'latestShadowScore': 164.0,
      'latestReadabilitySignal': 'shadow_risk',
      'exposureAssistStatus': 'auto_adjusted',
      'previewExposurePolicy':
          'receipt_paper_metering_safe_auto_lift_manual_slider',
      'preCaptureExposurePolicy':
          'receipt_paper_metering_dim_rescue_v2_manual_slider',
      'lastAutoExposureDecision': 'waiting_for_receipt_target',
      'lastPreCaptureExposureDecision': 'brightening_before_capture',
      'preCaptureExposureAdjustmentCount': 1,
      'preCaptureExposureAbortCount': 1,
      'lastPreCaptureExposureAbortReason': 'camera_surface_inactive',
      'lastAutoExposureBrightnessBucket': 'dark_assisted',
      'lastAutoExposureCandidate': 'brighten',
      'autoExposureCandidateFrameCount': 2,
      'latestFramingConfidence': 'usable_edges',
      'latestEdgeCoverage': 0.64,
      'latestPerspectiveReadiness': 'perspective_ready_safe_bounds',
      'edgeDetectionEnabled': true,
      'edgeOverlayEnabled': true,
      'shadowWarningEnabled': true,
      'textTooSmallWarningEnabled': true,
      'autoCropSuggestionEnabled': true,
      'grayscalePreviewEnabled': true,
      'contrastBoostEnabled': true,
      'shadowReductionEnabled': true,
      'orientationCorrectionEnabled': true,
      'tapFocusCount': 0,
      'tapFocusSuppressedAfterZoomCount': 0,
      'zoomChangeCount': 3,
      'manualExposureChangeCount': 1,
      'lastFocusStatus': 'continuous_focus',
      'sessionMinZoom': 1.0,
      'sessionMaxZoom': 8.0,
      'sessionMinExposureOffset': -2.0,
      'sessionMaxExposureOffset': 2.0,
      'nativeCameraSurfaceContractVersion': 'receipt_native_surface_v1',
      'captureSurface': 'maintainiac_native_android',
      'captureSurfaceExpected': 'maintainiac_native_android',
      'nativeCameraIdentity': 'maintainiac_in_app_receipt_camera',
      'nativeCameraIdentityExpected': 'maintainiac_in_app_receipt_camera',
      'nativeCaptureUiContract': 'maintainiac_custom_receipt_capture_ui_v1',
      'nativeCaptureUiContractExpected':
          'maintainiac_custom_receipt_capture_ui_v1',
      'nativePreviewOwnership': 'maintainiac_owns_preview_and_controls',
      'stockCameraUiAllowed': false,
      'stockCameraUiUsed': false,
      'nativeTouchControlPolicy':
          'continuous_focus_readability_and_pinch_zoom_v1',
      'readabilityGuidanceCoordinateSpace': 'preview_metering_point_factory',
      'pinchZoomPolicy': 'cameraX_zoom_ratio_clamped_to_capability',
      'nativeControlContractVersion': 'receipt_native_controls_v1',
      'controlDiagnosticsPrivacyScope': 'summary_only_no_receipt_content',
      'visibleControlSet':
          'back|settings|manual_shutter|status|light|brightness|long_receipt_done|section_ghost_guide|edge_guide',
      'previewDominanceTarget': 'receipt_preview_75_80_percent',
      'manualCapturePolicy': 'guidance_advisory_manual_shutter_always_allowed',
      'tapFocusControlExpected': false,
      'pinchZoomControlExpected': true,
      'exposureSliderControlExpected': true,
      'exposureResetControlExpected': true,
      'settingsControlExpected': true,
      'backControlExpected': true,
      'torchControlExpected': true,
      'focusLockControlExpected': false,
      'exposureLockControlExpected': false,
      'whiteBalanceLockControlExpected': false,
      'tapFocusEnabled': false,
      'pinchZoomEnabled': true,
      'exposureSliderEnabled': true,
      'exposureResetEnabled': true,
      'focusLockEnabled': false,
      'exposureLockEnabled': false,
      'whiteBalanceLockEnabled': false,
      'focusMode': 'continuous',
      'exposureMode': 'auto',
      'whiteBalanceMode': 'auto',
      'focusLockAttemptCount': 0,
      'focusLockSuccessCount': 0,
      'exposureLockSuccessCount': 0,
      'whiteBalanceLockAttemptCount': 0,
      'whiteBalanceLockSuccessCount': 0,
      'whiteBalanceLockStatus': 'not_requested',
      'autoCaptureTriggerCount': 1,
      'latestAutoCaptureStatus': 'capturing',
      'captureReadinessCode': 'auto_capture_ready',
      'captureReadinessLabel': 'Receipt looks steady. Taking photo.',
      'manualCaptureAllowed': true,
      'stableFrameCount': 3,
      'requiredStableFrames': 3,
      'closeAction': 'done_returned_captured_sections',
      'closeRetryCount': 1,
      'lastBackDispatchPath': 'top_bar_back_button',
      'pendingCloseAfterCapture': true,
      'closeResultDelivered': true,
      'autoCaptureAllowed': true,
      'autoCaptureCurrentlyAllowed': true,
      'closingCamera': false,
      'storageSafetyLevel': 'maximum',
      'storageConstrained': true,
      'storageSafetyReason': 'tight_storage_tiny_proofs',
      'maxLocalPhotoBytes': 6291456,
      'nativeCaptureMemoryPolicy':
          'tiny_local_proof_temporary_source_for_ocr_then_cleanup',
      'receiptLocalOnlyAcceptanceStatusCode':
          'ready_local_first_optional_packs_deferred',
      'receiptLocalOnlyAcceptanceActionCode':
          'ship_base_capture_save_review_before_optional_packs',
      'receiptLocalOnlyBaseFlowCanRunNow': true,
      'receiptLocalOnlyCanCaptureReceipt': true,
      'receiptLocalOnlyCanSaveReceiptProof': true,
      'receiptLocalOnlyCanOpenBasicReview': true,
      'receiptLocalOnlyRequiresHeavyPackBeforeCapture': false,
      'receiptLocalOnlyRequiresCloudBeforeCapture': false,
      'receiptLocalOnlyOptionalPacksDeferredBeforeCapture': true,
      'receiptLocalOnlyBlocksLowStorageUsers': false,
      'receiptLocalOnlyEvidenceCodes': [
        'capture_available_in_base',
        'proof_save_available_in_base',
        'basic_local_review_available_in_base',
      ],
      'receiptLocalOnlyUserFacingSummary':
          'Base receipt flow can run locally before optional packs.',
      'localOnlyCapturePolicy':
          'capture_save_basic_review_now_optional_packs_later',
      'localOnlyBaseFlowCanRunNow': true,
      'localOnlyHeavyPacksMayBlockCapture': false,
      'localOnlyCloudAssistMayBlockCapture': false,
      'localOnlyCameraMustStayAvailableBeforePacks': true,
      'localOnlyProofSaveMustStayAvailableBeforePacks': true,
      'localOnlyBasicReviewMustStayAvailableBeforePacks': true,
      'receiptBrainFirstInstallBoundaryCode':
          'ready_base_first_cloud_assist_optional_later',
      'receiptBrainFirstInstallBoundaryActionCode':
          'ship_base_then_offer_optional_cloud_assist',
      'receiptBrainFirstInstallCanRunOnLowStoragePhones': true,
      'receiptBrainFirstInstallBoundarySummary':
          'Required receipt install stays lean.',
      'receiptText': 'LOWE PRIVATE TEXT',
    },
  );
}
