part of 'trip_stop_debounce_policy.dart';

extension TripStopDebounceDecisionDashboardSummary on TripStopDebounceDecision {
  Map<String, Object?> toSafeDashboardMap() => {
    'schemaVersion': 1,
    'status': status.name,
    'reasonCode': _safeReason(reasonCode),
    'classification': classification.toSafeSummary(),
    'evidenceDigest': evidenceDigest.toSafeDashboardMap(),
    'vehicleOnlyDwell': vehicleOnlyDwell?.toSafeDashboardMap(),
    'falsePositiveGuard': TripStopFalsePositiveGuard.evaluate(
      profile: profile,
      status: status.name,
      classification: classification.toSafeSummary(),
      vehicleOnlyDwell: vehicleOnlyDwell?.toSafeDashboardMap(),
      needsWalkingReview: needsWalkingReview,
      protectedTrafficControl: protectedTrafficControl,
      canOpenReview: canOpenReview,
    ).toSafeDashboardMap(),
    'needsWalkingReview': needsWalkingReview,
    'protectedTrafficControl': protectedTrafficControl,
    'shouldContinueSampling': shouldContinueSampling,
    'canOpenReview': canOpenReview,
    'gpsAssistedOnly': true,
    'mapsRequiredForStopDebounce': false,
    ..._stopDebounceRemoteAuthorityClaims,
    ..._stopDebounceWalkingAuthorityClaims,
    ..._stopDebounceVehicleDwellAuthorityClaims,
    ..._stopDebounceMileageAuthorityClaims,
    'rawSamplesIncluded': false,
    'coordinatesIncluded': false,
    'routeGeometryIncluded': false,
    'tokensIncluded': false,
  };
}

const _stopDebounceRemoteAuthorityClaims = {
  'mapboxCanCreateStop': false,
  'mapboxCanConfirmStop': false,
  'mapboxDirectionsCanConfirmStop': false,
  'mapboxMatrixCanConfirmStop': false,
  'mapboxMapMatchingCanReplaceMileage': false,
  'mapboxOptimizationCanCreateStopOrder': false,
  'mapboxTrafficSignalCanCreateStop': false,
  'mapboxGeocodeCanConfirmStopAddress': false,
  'firestoreCanCreateStop': false,
  'cloudFunctionCanCreateStop': false,
  'remoteDebounceCanOverrideLocalTrip': false,
  'remoteDebounceCanOpenReview': false,
  'remoteDebounceCanEndTrip': false,
  'importedDebounceCanOpenReview': false,
  'dashboardCacheCanOpenReview': false,
  'authenticatedUserStillNeedsAuthorization': true,
  'localTripLogRequiredForReview': true,
  'malformedStopDebounceObservationFailsClosed': true,
  'stopReviewCannotCommitWithoutUserAction': true,
};

const _stopDebounceWalkingAuthorityClaims = {
  'walkingEvidenceCanOnlySuggestReview': true,
  'walkingEvidenceRequiresUserSensorOptIn': true,
  'walkingEvidenceRequiresCurrentDeviceSensor': true,
  'walkingEvidenceCannotBeReplayedFromCloud': true,
  'walkingEvidenceCannotBeImportedFromFile': true,
  'walkingEvidenceCannotCommitStop': true,
  'poorGpsCannotOpenStopReview': true,
  'interruptedGpsCannotOpenStopReview': true,
  'missingGpsCannotOpenStopReview': true,
  'unsafeGpsCannotOpenStopReview': true,
  'reducedGpsCanOnlyOpenReviewWithCorroboration': true,
  'currentVehicleSpeedMustAllowStopReview': true,
  'movingVehicleCannotOpenStopReview': true,
};

const _stopDebounceVehicleDwellAuthorityClaims = {
  'vehicleOnlyDwellCanOnlySuggestManualFallback': true,
  'vehicleOnlyDwellCanCreateOfficialStop': false,
  'vehicleOnlyDwellCannotInferAddress': true,
  'manualFallbackCannotInferAddress': true,
  'manualFallbackCannotConfirmMileage': true,
  'longStoplightCannotCreateOfficialStop': true,
  'longStoplightCannotInferAddress': true,
  'gridlockCannotCreateOfficialStop': true,
  'gridlockCannotInferAddress': true,
  'twoPersonDeliveryRequiresManualConfirmation': true,
  'driverProfileThresholdsAreLocalPolicy': true,
  'activityRecognitionCanCreateOfficialStop': false,
};

const _stopDebounceMileageAuthorityClaims = {
  'stopEvidenceCanCreateCalibration': false,
  'walkingEvidenceCanCreateCalibration': false,
  'trafficControlCanCreateCalibration': false,
  'stopEvidenceCanSetGlobalTruth': false,
  'stopEvidenceCanConfirmOfficialMileage': false,
  'stopEvidenceCanChangeOfficialMileage': false,
  'walkingEvidenceCanConfirmOfficialMileage': false,
  'trafficControlCanConfirmOfficialMileage': false,
  'calibrationRequiresTrustedGpsWindow': true,
  'poorGpsDaysExcludedFromCalibration': true,
  'stopReviewRequiredForOfficialStop': true,
  'odometerRemainsOfficialMileageTruth': true,
  'odometerIsGlobalTruth': true,
  'physicalOdometerRequiredForOfficialMileage': true,
  'confirmedOdometerOverridesExternalMileage': true,
  'externalMileageCannotBecomeGlobalTruth': true,
  'gpsDistanceCanOnlyAdviseMileageReview': true,
  'mapMatchingCanOnlyAdviseMileageReview': true,
  'optimizationCannotChangeOfficialMileage': true,
};
